import {textureCanvas} from './texture-canvas.js';
import * as THREE from 'three';
import {rooms,chapters} from './content.js';
import {episodes} from './episodes.js';
import {StoryDirector} from './story-engine.js';
import {bindScenePointer} from './touch-input.js';
import {touchDevice,pixelBudget,batchStatic} from './render-budget.js';
import {createSceneEntry} from './scene-entry.js';
const $=s=>document.querySelector(s);
let camera,renderer,scene,director,activeChapter,currentRoom=-2,yaw=0,pitch=0,locked=false,dragging=false,dragDistance=0,lastPointer,activeTarget=null,started=false,audioCtx,gain,sound=false;
const keys=new Set(),colliders=[],targets=[],animated=[],ray=new THREE.Raycaster(),clock=new THREE.Clock();
const world=$('#world');let pointer=new THREE.Vector2();
const houseLights=[];let entry,renderFault=false,contextLost=false,recoverChapter=1;const tablet=touchDevice();
const roomPosition=i=>({x:i%2===0?-7:7,z:-Math.floor(i/2)*12});
const modalOpen=()=>!!entry?.pending||!!document.querySelector('dialog[open]');
function pause(){keys.clear();dragging=false;if(document.pointerLockElement)document.exitPointerLock();}
function showDialog(id){pause();document.querySelectorAll('dialog[open]').forEach(d=>d.close());$(id).showModal();}
function textSafe(s){return s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');}
function status(t){$('#subtitle').textContent=t;$('#subtitle').style.opacity='1';clearTimeout(status.timer);status.timer=setTimeout(()=>$('#subtitle').style.opacity='0',8500);}
function renderMap(){$('#roomGrid').innerHTML=rooms.map((r,i)=>'<button class="room-card" data-room="'+i+'"><span>0'+(i+1)+' / '+r.period+'</span><h3>'+r.name+'</h3><p>'+r.concept+'</p><small>'+episodes.slice(i*3,i*3+3).map(e=>e.title).join(' · ')+'</small></button>').join('');$('#roomGrid').querySelectorAll('button').forEach(b=>b.onclick=()=>travel(Number(b.dataset.room)));}
function renderJournal(){$('#journalList').innerHTML=episodes.map(e=>'<button data-chapter="'+e.n+'"><img loading="lazy" src="'+import.meta.env.BASE_URL+'art/event-'+String(e.n).padStart(2,'0')+'.jpg" alt=""><span><b>事件 '+String(e.n).padStart(2,'0')+'</b>'+e.title+' · 连续三维演出'+'<small>'+e.steps.map(s=>s.title).join(' / ')+'</small></span></button>').join('');$('#journalList').querySelectorAll('button').forEach(b=>b.onclick=()=>openChapter(Number(b.dataset.chapter)));}
function travel(i){director?.close();started=true;document.querySelectorAll('dialog[open]').forEach(d=>d.close());const p=roomPosition(i);if(camera){camera.position.set(p.x,1.7,p.z+1.7);yaw=0;pitch=-.12;}currentRoom=-2;updateLocation();status(rooms[i].whisper);}
function openChapter(n){activeChapter=chapters.find(c=>c.n===n);if(!activeChapter)return;pause();document.querySelectorAll('dialog[open]').forEach(d=>d.close());if(director&&!contextLost)entry.start(n);else showArchive(n);}
function leaveEntry(){renderFault=contextLost;keys.clear();try{director?.close()}catch(error){console.error(error)}$('#filmHud').hidden=true;document.body.classList.remove('in-story','in-film','film-walking');$('#bookTools').hidden=true;$('#filmAudio').disabled=false;$('#filmPause').disabled=false;}
function recoverScene(error,n=director?.chapter||activeChapter?.n||1){console.error(error);const state=director?.film?.state||'loading',phase=director?.film?.phase;$('#recoveryDetails').textContent=['事件 '+n+(Number.isInteger(phase)?' / 段落 '+(phase+1):''),'阶段：'+state,String(error?.message||error),'版本：canvas-budget-2',navigator.userAgent].join('\n');$('#recoveryDebug').open=false;recoverChapter=n;leaveEntry();renderFault=true;$('#recoveryMessage').textContent=contextLost?'画面暂时中断了。可以先阅读这段记述，或等待画面恢复后重新进入。':'这一段暂时没能展开。可以重新进入，也可以回到房子。';showDialog('#recovery');}
entry=createSceneEntry({schedule:callback=>requestAnimationFrame(callback),paint:n=>{recoverChapter=n;$('#filmHud').hidden=false;$('#filmHud').dataset.state='loading';$('#filmTitle').textContent=episodes.find(e=>e.n===n).title;$('#filmCaption').textContent='正在走进这段往事…';$('#filmHint').textContent='';$('#filmThought').textContent='';$('#filmFact').textContent='';$('#filmAudio').disabled=true;$('#filmPause').disabled=true;$('#filmExit').onclick=()=>entry.cancel();document.body.classList.add('in-story','in-film');},open:n=>{renderFault=false;try{director.open(n)}finally{$('#filmAudio').disabled=false;$('#filmPause').disabled=false;}},fail:recoverScene,cancel:leaveEntry});
$('#recoverScene').onclick=()=>openChapter(recoverChapter);$('#recoverHouse').onclick=()=>{entry.cancel();$('#recovery').close();};$('#recoverRead').onclick=()=>showArchive(recoverChapter);
function showArchive(n){const c=chapters.find(c=>c.n===n),e=episodes.find(e=>e.n===n);$('#chapterMeta').textContent='原书第 '+c.n+' 章 · 中文原创转述';$('#chapterTitle').textContent=e.title;$('#readerBody').innerHTML='<p class="scene-note">原书事件 · 详尽转述</p>'+c.story.map(t=>'<p>'+textSafe(t)+'</p>').join('')+'<div class="principle"><p class="scene-note">解释与归纳</p><p>'+textSafe(c.principle)+'</p></div><p class="fine">原文定位：'+e.steps.map(s=>textSafe(s.anchor)).join('；')+'</p>';showDialog('#reader');$('#reader').scrollTop=0;}
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());
document.querySelectorAll('dialog').forEach(d=>{d.addEventListener('close',()=>keys.clear());d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close();}});});
$('#mapBtn').onclick=()=>{renderMap();showDialog('#atlas');};$('#journalBtn').onclick=()=>{renderJournal();showDialog('#journal');};$('#helpBtn').onclick=()=>showDialog('#help');$('#introMap').onclick=$('#mapBtn').onclick;$('#home').onclick=e=>{e.preventDefault();showDialog('#intro');};$('#begin').onclick=()=>{if(new URL(location.href).searchParams.get('sample')==='1901'){openChapter(3);return;}started=true;$('#intro').close();status('走进房间，触碰物件。也可以从事件目录直接进入任何一段故事。');};
$('#sampleBegin').onclick=()=>openChapter(3);$('#bookBegin').onclick=()=>openChapter(1);
$('#walkBtn').onclick=async()=>{if(!renderer)return;try{await world.requestPointerLock();}catch{status('按住场景拖动，然后用 W A S D 移动。');}};
document.addEventListener('pointerlockchange',()=>{locked=document.pointerLockElement===world;$('#walkBtn').textContent=locked?'Esc 退出步行模式':'进入步行模式';});
$('#interactBtn').onclick=()=>{if(activeTarget)openChapter(activeTarget.userData.chapter);};
document.addEventListener('keydown',e=>{if(modalOpen())return;if(director?.film.active){director.film.keyDown(e);return;}if(director?.active){if(e.code==='Escape')director.close();if(e.target.matches('input,[role=button]'))return;if(e.code==='ArrowRight')director.next();if(e.code==='ArrowLeft'&&director.phase>0)director.showPhase(director.phase-1);return;}if(['KeyW','KeyA','KeyS','KeyD','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space'].includes(e.code)){e.preventDefault();keys.add(e.code);}if(e.code.startsWith('Shift'))keys.add('Shift');if(e.code==='KeyM')$('#mapBtn').click();if(e.code==='KeyJ')$('#journalBtn').click();if(e.code==='KeyE'&&activeTarget)openChapter(activeTarget.userData.chapter);});
document.addEventListener('keyup',e=>{if(director?.film.active)director.film.keyUp(e);keys.delete(e.code);if(e.code.startsWith('Shift'))keys.delete('Shift');});window.addEventListener('blur',()=>{pause();if(director?.film.active)director.film.setPaused(true);});document.addEventListener('visibilitychange',()=>{if(document.hidden){pause();if(director?.film.active)director.film.setPaused(true);}});
const resetScenePointer=bindScenePointer(world,{blocked:modalOpen,
 down:e=>{if(modalOpen())return;if(director?.film.active){director.film.pointerDown(e.clientX,e.clientY);return;}dragging=true;dragDistance=0;lastPointer={x:e.clientX,y:e.clientY};},
 move:e=>{if(modalOpen())return;if(director?.film.active){director.film.pointerMove(e.clientX,e.clientY);return;}let dx=0,dy=0;if(locked){dx=e.movementX;dy=e.movementY;}else if(dragging&&lastPointer){dx=e.clientX-lastPointer.x;dy=e.clientY-lastPointer.y;lastPointer={x:e.clientX,y:e.clientY};dragDistance+=Math.abs(dx)+Math.abs(dy);}if(director?.active){director.pointer(e.clientX,e.clientY,dx,dy);return;}yaw-=dx*.003;pitch=THREE.MathUtils.clamp(pitch-dy*.003,-1.15,1.15);},
 up:e=>{if(modalOpen())return;if(director?.film.active){director.film.pointerUp(e.clientX,e.clientY);return;}if(director?.active){if(dragDistance<8)director.pointer(e.clientX,e.clientY);}else if(dragDistance<8){if(locked){if(activeTarget)openChapter(activeTarget.userData.chapter);}else if(camera){pointer.set(e.clientX/window.innerWidth*2-1,-e.clientY/window.innerHeight*2+1);const hit=findTarget(pointer);if(hit)openChapter(hit.userData.chapter);}}dragging=false;lastPointer=null;},
 cancel:()=>{dragging=false;lastPointer=null;if(director?.film.active){director.film.drag=null;director.film.keyHeld=false;}}
});
document.querySelectorAll('[data-move]').forEach(b=>{let target=null,owner=null;const release=()=>{if(target)target.keyUp({code:b.dataset.move});keys.delete(b.dataset.move);target=null;owner=null;};b.addEventListener('pointerdown',e=>{if(owner!==null)return;e.preventDefault();owner=e.pointerId;if(director?.film.active){if(director.film.state!=='epilogue'){owner=null;return;}target=director.film;target.keyDown({code:b.dataset.move,preventDefault(){}});}else keys.add(b.dataset.move);b.setPointerCapture(e.pointerId);});for(const evt of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(evt,e=>{if(e.pointerId===owner)release();});window.addEventListener('blur',release);document.addEventListener('visibilitychange',()=>{if(document.hidden)release();});});
window.addEventListener('blur',resetScenePointer);document.addEventListener('visibilitychange',()=>{if(document.hidden)resetScenePointer();});
function chime(){if(!audioCtx||!sound)return;const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type='sine';o.frequency.setValueAtTime(440,audioCtx.currentTime);o.frequency.exponentialRampToValueAtTime(220,audioCtx.currentTime+.5);g.gain.setValueAtTime(.06,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+.8);o.connect(g).connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+.8);}
$('#soundBtn').onclick=()=>{sound=!sound;try{if(!audioCtx){audioCtx=new(window.AudioContext||window.webkitAudioContext)();gain=audioCtx.createGain();gain.gain.value=0;gain.connect(audioCtx.destination);[55,82.41,110].forEach((f,i)=>{const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type='sine';o.frequency.value=f;g.gain.value=.035/(i+1);o.connect(g).connect(gain);o.start();});}audioCtx.resume();gain.gain.setTargetAtTime(sound?1:0,audioCtx.currentTime,.4);$('#soundBtn').textContent=`声音 · ${sound?'开':'关'}`;$('#soundBtn').setAttribute('aria-pressed',String(sound));}catch{sound=false;status('此窗口暂时无法播放声音。');}};

function material(color,extra={}){return new THREE.MeshStandardMaterial({color,roughness:.78,...extra});}
const mats={wood:material(0x39261a),darkWood:material(0x211a14),brass:material(0xb3975a,{metalness:.6,roughness:.4}),paper:material(0xe4d8b8),iron:material(0x35393b,{metalness:.5}),red:material(0x6c3030),green:material(0x304b3e),cotton:material(0xd5cbbb),black:material(0x101715)};
function meshBox(parent,w,h,d,x,y,z,mat,solid=false){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat);m.position.set(x,y,z);parent.add(m);if(solid){m.updateWorldMatrix(true,false);colliders.push({box:new THREE.Box3().setFromObject(m),mesh:m});}return m;}
function cylinder(parent,r1,r2,h,x,y,z,mat){const m=new THREE.Mesh(new THREE.CylinderGeometry(r1,r2,h,24),mat);m.position.set(x,y,z);parent.add(m);return m;}
function sphere(parent,r,x,y,z,mat){const m=new THREE.Mesh(new THREE.SphereGeometry(r,16,12),mat);m.position.set(x,y,z);parent.add(m);return m;}
function label(txt,w=2.5,h=.65,size=56,color='#e3cca0'){const height=Math.round(1024*h/w),{canvas:c,context:ct}=textureCanvas(1024,height,tablet);ct.fillStyle=color;ct.font=`${size}px "Microsoft YaHei",serif`;ct.textAlign='center';ct.textBaseline='middle';ct.fillText(txt,512,height/2,1000);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;if(tablet){t.generateMipmaps=false;t.minFilter=THREE.LinearFilter;}const s=new THREE.Sprite(new THREE.SpriteMaterial({map:t,transparent:true,depthWrite:false}));s.scale.set(w,h,1);return s;}
function plaque(parent,txt,x,y,z,w=2.5){meshBox(parent,w,.56,.08,x,y,z,mats.darkWood);const l=label(txt,w,.45,70);l.position.set(x,y,z+.07);parent.add(l);}
function bookshelf(p,x,z,rotation=0){const g=new THREE.Group();g.position.set(x,0,z);g.rotation.y=rotation;p.add(g);meshBox(g,2.1,3,.35,0,1.5,0,mats.darkWood);for(let k=0;k<4;k++){meshBox(g,2.1,.08,.65,0,.3+k*.72,.12,mats.wood);for(let j=0;j<9;j++){const bookMat=[mats.red,mats.green,mats.wood,mats.paper][(k+j)%4];const b=meshBox(g,.14,.38+(j%3)*.1,.28,-.84+j*.2,.57+k*.72,.22,bookMat);b.rotation.z=(j%4===0?.08:0);meshBox(g,.145,.025,.29,-.84+j*.2,.55+k*.72,.23,mats.brass);}}}
function desk(parent,x,z,w=2){meshBox(parent,w,.12,1.1,x,.92,z,mats.wood,true);for(const dx of [-w*.42,w*.42])for(const dz of [-.42,.42])meshBox(parent,.09,.87,.09,x+dx,.435,z+dz,mats.darkWood);}
function lamp(parent,x,z){cylinder(parent,.2,.25,.08,x,1.03,z,mats.brass);cylinder(parent,.025,.025,.42,x,1.28,z,mats.brass);cylinder(parent,.21,.3,.21,x,1.55,z,material(0xc5a96b,{emissive:0xb08439,emissiveIntensity:.65}));}
function makeObject(c,parent,x,z){const g=new THREE.Group();g.position.set(x,1.03,z);parent.add(g);const kind=c.kind;
if(kind==='book'||kind==='paper'||kind==='ticket'||kind==='letter'){for(let k=0;k<3;k++){const m=meshBox(g,.66,.055,.49,k*.045,k*.065,0,kind==='book'&&k===0?mats.red:mats.paper);m.rotation.y=k*.08;}for(let j=0;j<4;j++)meshBox(g,.39,.006,.012,0,.192,-.14+j*.075,mats.darkWood);}
else if(kind==='board'){meshBox(g,1.65,1.15,.12,0,.62,0,mats.darkWood);meshBox(g,1.48,.98,.02,0,.62,.075,mats.green);for(let j=0;j<3;j++){const l=label(['STEEL  90⅛','SUGAR  112','UP     155'][j],1.3,.21,50,'#eee7cf');l.position.set(0,.93-j*.3,.1);g.add(l);}}
else if(kind==='clock'){cylinder(g,.5,.5,.14,0,.58,0,mats.brass).rotation.x=Math.PI/2;const f=cylinder(g,.44,.44,.16,0,.58,.02,mats.paper);f.rotation.x=Math.PI/2;const hand=meshBox(g,.025,.32,.025,0,.72,.12,mats.black);hand.rotation.z=-.6;meshBox(g,.25,.02,.025,.1,.58,.12,mats.black);meshBox(g,1,.08,.35,0,.05,0,mats.darkWood);}
else if(kind==='ship'){meshBox(g,1.35,.22,.4,0,.16,0,mats.wood);meshBox(g,.7,.22,.35,0,.36,0,mats.paper);cylinder(g,.025,.025,1.1,0,.77,0,mats.brass);const sail=meshBox(g,.55,.63,.02,.25,.85,0,mats.paper);sail.rotation.y=.15;}
else if(kind==='cotton'){meshBox(g,.8,.5,.6,0,.25,0,mats.cotton);for(let j=0;j<7;j++)sphere(g,.13,-.28+(j%3)*.24,.53+Math.floor(j/3)*.035,-.18+(j%2)*.34,mats.paper);for(const xx of [-.25,.25])meshBox(g,.025,.53,.62,xx,.27,0,mats.wood);}
else if(kind==='phone'){cylinder(g,.28,.37,.12,0,.08,0,mats.black);cylinder(g,.055,.065,.65,0,.45,0,mats.brass);const horn=cylinder(g,.17,.07,.3,0,.84,0,mats.brass);horn.rotation.z=Math.PI/3;const receiver=cylinder(g,.09,.17,.35,.32,.55,0,mats.black);receiver.rotation.z=.3;}
else if(kind==='safe'){meshBox(g,.9,.9,.7,0,.45,0,mats.iron);meshBox(g,.73,.72,.06,0,.45,.39,mats.darkWood);const dial=cylinder(g,.12,.12,.09,0,.5,.46,mats.brass);dial.rotation.x=Math.PI/2;meshBox(g,.035,.25,.07,.22,.46,.48,mats.brass);}
else if(kind==='scale'){meshBox(g,.8,.08,.35,0,.04,0,mats.wood);cylinder(g,.03,.03,.9,0,.53,0,mats.brass);meshBox(g,1.1,.045,.04,0,.95,0,mats.brass);for(const xx of [-.45,.45]){meshBox(g,.012,.4,.012,xx,.75,0,mats.brass);cylinder(g,.23,.12,.08,xx,.54,0,mats.brass);}}
else if(kind==='press'){meshBox(g,.85,.14,.65,0,.09,0,mats.black);for(const xx of [-.34,.34])meshBox(g,.08,.8,.08,xx,.52,0,mats.brass);meshBox(g,.8,.08,.14,0,.92,0,mats.iron);cylinder(g,.055,.055,.6,0,.7,0,mats.brass);meshBox(g,.62,.12,.42,0,.37,0,mats.iron);meshBox(g,.52,.025,.4,0,.23,0,mats.paper);}
else if(kind==='mirror'){meshBox(g,.95,1.2,.1,0,.62,0,mats.brass);meshBox(g,.82,1.06,.03,0,.62,.07,material(0x829c99,{metalness:1,roughness:.18}));}
else if(kind==='suitcase'){meshBox(g,.95,.58,.34,0,.3,0,mats.wood);for(const xx of [-.3,.3])meshBox(g,.045,.59,.36,xx,.3,0,mats.brass);meshBox(g,.3,.07,.07,0,.64,0,mats.darkWood);}
else{cylinder(g,.35,.42,.13,0,.12,0,mats.brass);sphere(g,.26,0,.42,0,mats.paper);}
g.userData.chapter=c.n;g.traverse(o=>o.userData.chapter=c.n);targets.push(g);const halo=new THREE.Mesh(new THREE.RingGeometry(.38,.43,40),material(0xd8bb7b,{emissive:0xd8bb7b,emissiveIntensity:1,side:THREE.DoubleSide,transparent:true,opacity:.55}));halo.rotation.x=-Math.PI/2;halo.position.set(x,.992,z);parent.add(halo);const l=label(`${c.roman} · ${c.object}`,1.9,.34,48);l.position.set(x,1.95,z);parent.add(l);animated.push({group:g,halo,label:l,n:c.n,base:g.position.y,activeUntil:0});}
function roomTableau(i,g,side){
// Each room has a different spatial mnemonic, beyond its three readable objects.
if(i===0){meshBox(g,3.1,1.8,.13,side*4.8,2.15,1.8,mats.green).rotation.y=Math.PI/2;const t=label('数字，是我的第一种语言。',3.1,.6,56);t.position.set(side*3.1,2.6,1.8);g.add(t);}
if(i===1){for(let j=0;j<3;j++){const x=-1.5+j*1.5;meshBox(g,.85,.12,.85,x,.5,1.8,mats.green);meshBox(g,.85,1.1,.12,x,1.02,2.2,mats.darkWood);for(const dx of [-.34,.34])for(const dz of [-.34,.34])meshBox(g,.07,.5,.07,x+dx,.25,1.8+dz,mats.wood);}const t=label('位置，比一时的差价更难找回。',4,.55,58);t.position.set(0,2.35,2.4);g.add(t);}
if(i===2){meshBox(g,4,.025,2.5,0,.07,2,material(0x254e58,{metalness:.55,roughness:.3}));for(let j=0;j<10;j++){meshBox(g,3.5,.025,.025,0,.09,1+j*.22,material(0x739698,{emissive:0x34545f,emissiveIntensity:.2}));}const t=label('钱消失的那天，所有人都在找岸。',4,.55,55);t.position.set(0,2.5,2.6);g.add(t);}
if(i===3){for(let j=0;j<7;j++){const x=side*(2.5+(j%2)*.9),z=.5+Math.floor(j/2)*.9;meshBox(g,.75,.7,.65,x,.38,z,mats.cotton);for(const dx of [-.23,.23])meshBox(g,.035,.73,.69,x+dx,.39,z,mats.wood);}const t=label('我知道，却没有做到。',3.7,.6,65);t.position.set(0,2.5,1.9);g.add(t);}
if(i===4){for(let j=0;j<6;j++)meshBox(g,.07,3,.07,-2+j*.8,1.5,3.6,mats.iron);meshBox(g,4.2,.08,.08,0,2.9,3.6,mats.iron);const t=label('债务使每一刻，都像最后的机会。',4,.55,55);t.position.set(0,2.35,3.5);g.add(t);}
if(i===5){for(let j=0;j<7;j++){const m=meshBox(g,.52,.025,.38,-2.3+j*.72,1.6+Math.sin(j)*.3,2.8,mats.paper);m.rotation.z=Math.sin(j)*.15;}const t=label('秘密经过七个人，仍只有一个源头。',4.4,.55,55);t.position.set(0,2.7,2.7);g.add(t);}
if(i===6){meshBox(g,4.5,.24,2.2,0,.12,2.4,mats.darkWood);for(const x of [-2.2,2.2])for(let k=0;k<4;k++)cylinder(g,.13,.13,2.9,x+k*.15*(x<0?1:-1),1.55,3.1,material(0x632c38));const t=label('幕布升起时，谁正在退场？',4,.55,58);t.position.set(0,2.4,2.8);g.add(t);}
if(i===7){desk(g,0,2.7,3.2);for(let j=0;j<5;j++){meshBox(g,.5,.03,.4,-1.1+j*.55,1.03,2.7,mats.paper);}const t=label('最后一个判断，留给你。',4,.6,65);t.position.set(0,2.3,3.2);g.add(t);}
}
function buildRoom(i){const p=roomPosition(i),g=new THREE.Group();g.position.set(p.x,0,p.z);scene.add(g);const wallMat=material(rooms[i].color);const side=i%2===0?-1:1;
meshBox(g,10,.2,10,0,-.1,0,mats.wood);for(let j=0;j<12;j++)meshBox(g,.025,.012,10,-5+j*.85,.015,0,mats.darkWood);
meshBox(g,10,4,.2,0,2,-5,wallMat,true);meshBox(g,10,4,.2,0,2,5,wallMat,true);meshBox(g,.2,4,10,side*5,2,0,wallMat,true);
for(const z of [-3.25,3.25])meshBox(g,.2,4,3.5,-side*5,2,z,wallMat,true);meshBox(g,.2,1.2,3,-side*5,3.4,0,wallMat);
for(const z of [-4.86,4.86]){meshBox(g,10,1,.08,0,.5,z,mats.darkWood);meshBox(g,10,.06,.1,0,1.04,z,mats.brass);for(let j=0;j<7;j++)meshBox(g,.04,.78,.12,-4.5+j*1.5,.5,z,mats.wood);}
for(const z of [-4,0,4])meshBox(g,10,.14,.2,0,3.95,z,mats.darkWood);
meshBox(g,2.5,2,.08,side*4.86,2.45,-1.7,material(0x587875,{emissive:0x527871,emissiveIntensity:.4}));for(let j=0;j<4;j++)meshBox(g,.07,2,.1,side*4.8,2.45,-2.8+j*.73,mats.darkWood);meshBox(g,.12,.08,2.6,side*4.78,2.4,-1.7,mats.darkWood);
const rug=meshBox(g,6,.015,4.4,0,.025,.5,material(i%2===0?0x463127:0x283c35));meshBox(g,5.7,.017,.05,0,.035,-1.56,mats.brass);meshBox(g,5.7,.017,.05,0,.035,2.56,mats.brass);
bookshelf(g,side*3.5,4.5);bookshelf(g,side*1.2,4.5);plaque(g,rooms[i].name,0,2.95,-4.83,3.7);
const positions=[[-2.8,-3.7],[0,-3.7],[2.8,-3.7]];chapters.filter(c=>Math.floor((c.n-1)/3)===i).forEach((c,j)=>{const [x,z]=positions[j];desk(g,x,z,2.15);makeObject(c,g,x,z);if(j===1)lamp(g,x+.8,z+.28);});
desk(g,side*3.3,1.8,1.5);lamp(g,side*3.3,1.8);meshBox(g,.7,.1,.7,side*3.3,.5,2.8,mats.green);meshBox(g,.7,.9,.08,side*3.3,.95,3.1,mats.darkWood);
roomTableau(i,g,side);
const light=new THREE.PointLight(0xffd49a,19,15,2);light.position.set(0,3.3,-1);g.add(light);cylinder(g,.4,.65,.24,0,3.25,-1,material(0xc2a36b,{emissive:0xe4bb70,emissiveIntensity:.9}));cylinder(g,.02,.02,.5,0,3.6,-1,mats.brass);
}
function initWorld(){scene=new THREE.Scene();scene.background=new THREE.Color(0x101c18);scene.fog=new THREE.FogExp2(0x101c18,.026);camera=new THREE.PerspectiveCamera(67,innerWidth/innerHeight,.05,90);camera.position.set(0,1.7,7);camera.rotation.order='YXZ';renderer=new THREE.WebGLRenderer({canvas:world,antialias:!tablet,powerPreference:tablet?'low-power':'high-performance'});renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(pixelBudget(innerWidth,innerHeight,tablet));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.4;scene.add(new THREE.HemisphereLight(0xb9d5d0,0x6e4c2c,1.5));
meshBox(scene,4,.2,56,0,-.1,-18,mats.darkWood);for(let j=0;j<29;j++){meshBox(scene,3.7,.015,.04,0,.01,8-j*2,mats.wood);}meshBox(scene,3,.02,54,0,.025,-18,material(0x273b33));for(const x of [-1.48,1.48])meshBox(scene,.025,.023,54,x,.04,-18,mats.brass);
for(let row=0;row<4;row++){const z=-row*12;for(const x of [-2,2]){meshBox(scene,.2,4,3,x,2,z+4.5,material(0x22382c),true);meshBox(scene,.2,4,3,x,2,z-4.5,material(0x22382c),true);for(const dz of [-1.65,1.65])meshBox(scene,.25,3.2,.15,x,1.6,z+dz,mats.wood);meshBox(scene,.3,.18,3.5,x,3.1,z,mats.brass);}
const l=new THREE.PointLight(0xe3cb91,13,13,2);l.position.set(0,3,z);scene.add(l);const pendant=cylinder(scene,.22,.38,.2,0,3.1,z,material(0xf0d299,{emissive:0xc5a568,emissiveIntensity:1}));cylinder(scene,.015,.015,.9,0,3.65,z,mats.brass);
}
for(const z of [9,-45])meshBox(scene,4,4,.2,0,2,z,material(0x22382c),true);plaque(scene,'每一次代价，都留下一个房间。',0,2.9,-44.83,3.6);rooms.forEach((r,i)=>buildRoom(i));batchStatic(scene,new Set([...targets,...colliders.map(c=>c.mesh),...animated.map(a=>a.group)]));scene.traverse(o=>{if(o.isPointLight)houseLights.push({light:o,position:o.getWorldPosition(new THREE.Vector3())});});
const motes=new THREE.BufferGeometry(),arr=[];for(let j=0;j<180;j++)arr.push((Math.random()-.5)*22,Math.random()*3.5,-Math.random()*48+7);motes.setAttribute('position',new THREE.Float32BufferAttribute(arr,3));scene.add(new THREE.Points(motes,new THREE.PointsMaterial({size:.025,color:0xdeb976,transparent:true,opacity:.45})));
const ribbon=label('价格变了。人却还是那样。',4.5,.7,65,'#dbc58d');ribbon.position.set(0,2.15,-5);scene.add(ribbon);
window.addEventListener('resize',()=>{resetScenePointer();keys.clear();director?.film.keys?.clear();renderer.setPixelRatio(pixelBudget(innerWidth,innerHeight,tablet));camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);});world.addEventListener('webglcontextlost',e=>{e.preventDefault();contextLost=true;recoverScene(new Error('Graphics context lost'));});world.addEventListener('webglcontextrestored',()=>{contextLost=false;renderFault=false;$('#recoveryMessage').textContent='画面已恢复，可以重新进入这段往事。';});animate();}
function collides(x,z){if(x<-11.65||x>11.65||z>8.65||z<-44.65)return true;return colliders.some(c=>x>c.box.min.x-.23&&x<c.box.max.x+.23&&z>c.box.min.z-.23&&z<c.box.max.z+.23&&c.box.max.y>.3&&c.box.min.y<1.8);}
function findTarget(p){ray.setFromCamera(p,camera);const hits=ray.intersectObjects(targets,true);const h=hits.find(h=>h.distance<5.5);if(!h)return null;const blocking=ray.intersectObjects(colliders.map(c=>c.mesh),false)[0];if(blocking&&blocking.distance<h.distance-.05)return null;return h.object;}
function updateLocation(){if(!camera)return;const p=camera.position;let i=-1;for(let n=0;n<8;n++){const r=roomPosition(n);if(Math.abs(p.x-r.x)<4.95&&Math.abs(p.z-r.z)<4.95){i=n;break;}}if(i===currentRoom)return;currentRoom=i;if(i<0){$('#roomNumber').textContent='序章 / THE LONG HALLWAY';$('#roomTitle').textContent='所有错误，都还住在这里。';$('#roomConcept').textContent='走进两侧的房间，靠近发光的物件。';}else{$('#roomNumber').textContent=`0${i+1} / ${rooms[i].period}`;$('#roomTitle').textContent=rooms[i].name;$('#roomConcept').textContent=rooms[i].concept;status(rooms[i].whisper);}}
function animate(){requestAnimationFrame(animate);if(renderFault||contextLost||entry?.pending){clock.getDelta();return;}try{const dt=Math.min(clock.getDelta(),.05);if(director?.active){director.update(modalOpen()?0:dt);return;}if(!modalOpen()){camera.rotation.set(pitch,yaw,0,'YXZ');let vx=0,vz=0;if(keys.has('KeyW')||keys.has('ArrowUp'))vz-=1;if(keys.has('KeyS')||keys.has('ArrowDown'))vz+=1;if(keys.has('KeyA')||keys.has('ArrowLeft'))vx-=1;if(keys.has('KeyD')||keys.has('ArrowRight'))vx+=1;const len=Math.hypot(vx,vz)||1,spd=(keys.has('Shift')?4.5:2.6)*dt;const dx=(vx*Math.cos(yaw)+vz*Math.sin(yaw))/len*spd,dz=(-vx*Math.sin(yaw)+vz*Math.cos(yaw))/len*spd;if(!collides(camera.position.x+dx,camera.position.z))camera.position.x+=dx;if(!collides(camera.position.x,camera.position.z+dz))camera.position.z+=dz;updateLocation();activeTarget=findTarget(new THREE.Vector2(0,0));$('#interact').hidden=!activeTarget;if(activeTarget){const c=chapters.find(c=>c.n===activeTarget.userData.chapter);$('#targetName').textContent=c?.object||'';}}
if(tablet){houseLights.sort((a,b)=>a.position.distanceToSquared(camera.position)-b.position.distanceToSquared(camera.position));houseLights.forEach((l,i)=>l.light.visible=i<2);}const now=performance.now();animated.forEach((a,i)=>{a.halo.material.opacity=.3+Math.sin(now*.0015+i)*.18;a.group.rotation.y=a.activeUntil>now?Math.sin(now*.004)*.13:0;});renderer.render(scene,camera);}catch(error){recoverScene(error)}}
try{initWorld();director=new StoryDirector(renderer,{onClose:()=>keys.clear(),onArchive:showArchive});}catch(e){console.error(e);$('#error').hidden=false;$('#walkBtn').disabled=true;}
showDialog('#intro');
