import * as THREE from 'three';
import {EffectComposer} from 'three/addons/postprocessing/EffectComposer.js';
import {RenderPass} from 'three/addons/postprocessing/RenderPass.js';
import {UnrealBloomPass} from 'three/addons/postprocessing/UnrealBloomPass.js';
import {OutputPass} from 'three/addons/postprocessing/OutputPass.js';
import {batchStatic,pixelBudget} from './render-budget.js';
import {TickerFilm} from './ticker-film.js';
import {storyFor,paginate} from './novel-scores.js';
const $=s=>document.querySelector(s),clamp=THREE.MathUtils.clamp,lerp=THREE.MathUtils.lerp;
const ease=x=>{x=clamp(x,0,1);return x*x*(3-2*x)};
const BASE=import.meta.env?.BASE_URL||'./';
const paper=0xe5d7b5,wood=0x553624,brass=0xc1a262;

export class NovelFilm extends TickerFilm{
 open(n){this.work=storyFor(n);this.phase=0;this.language='zh';this.page=0;this.english=[];this.notePages=paginate(this.work.notes);this.originalPages=[];this.sourceRequest=(this.sourceRequest||0)+1;const request=this.sourceRequest;super.open();this.setState('arrival');$('#filmTitle').textContent=this.work.phases[0].title;$('#world').setAttribute('aria-label',this.work.title+'：直接触碰物件的连续三维故事');
  if(typeof window!=='undefined')fetch(`${BASE}manuscripts/${String(n).padStart(2,'0')}.json`).then(r=>{if(!r.ok)throw Error('Manuscript unavailable');return r.json()}).then(data=>{if(request!==this.sourceRequest)return;this.english=data.paragraphs;this.originalPages=paginate(this.english,true);if(this.state==='book'&&this.language==='en')this.showBook(0)}).catch(()=>{if(request===this.sourceRequest)this.manuscriptError=true});
 }
 build(){this.scene=new THREE.Scene();this.scene.background=new THREE.Color(0x102121);this.scene.fog=new THREE.FogExp2(0x172a2b,.022);this.targets=[];this.actors=[];this.materials=[];this.textures=[];this.matCache=new Map();this.motions=[];this.lastWidth=0;this.sceneStats=null;this.progress=0;this.dispatching=false;this.bales=null;this.certificates=null;this.quotePanel=null;this.boardWritten=false;this.stitch=null;this.displayFlip=0;this.held=null;this.drag=null;this.paperLoops=[];this.environment=new THREE.Group();this.scene.add(this.environment);this.dynamic=new THREE.Group();this.scene.add(this.dynamic);this.wood=this.mat(0xbca58a,{map:this.woodTexture()});this.brass=this.mat(brass,{metalness:.6,roughness:.3});
  this.scene.add(new THREE.HemisphereLight(0xb5d1d6,0x30261a,1.6));this.sun=new THREE.DirectionalLight(0xffd8a2,3.1);this.sun.position.set(-5,9,2);this.sun.castShadow=!this.lightweight;this.sun.shadow.mapSize.set(512,512);this.sun.shadow.camera.left=-10;this.sun.shadow.camera.right=10;this.sun.shadow.camera.top=10;this.sun.shadow.camera.bottom=-10;this.sun.shadow.normalBias=.035;this.scene.add(this.sun);this.lampLight=new THREE.PointLight(0xffca8c,10,14);this.lampLight.position.set(-2,3,1);this.scene.add(this.lampLight);
  this.makeSpace(this.work.phases[this.phase].space);this.makeObject(this.work.phases[this.phase].object);this.home=this.prop.position.clone();this.homeRotation=this.prop.rotation.clone();this.propBase=this.prop.position.clone();this.target(this.prop,'object');
  const desk=new THREE.Group();desk.position.set(-2.7,0,1.2);this.environment.add(desk);this.box(desk,1.5,.1,1,0,.9,0,this.wood);for(const x of[-.6,.6])this.box(desk,.08,.9,.8,x,.4,0,this.wood);
  this.book=this.card(['私人记述','保存在这里的细节','拉里 · 利文斯顿'],['PRIVATE ACCOUNT']);this.book.position.set(-2.7,.97,1.2);this.book.scale.setScalar(.9);this.scene.add(this.book);this.bookPage=this.book.userData.front;this.target(this.book,'book');
  this.bookmark=new THREE.Group();this.bookmark.position.set(-2.08,1.03,1.2);this.scene.add(this.bookmark);this.placard(this.bookmark,['另一册','English'],.28,.18,0,0,0).rotation.x=-Math.PI/2;this.target(this.bookmark,'language');
  this.exit=new THREE.Group();this.exit.position.set(3.5,0,3.2);this.scene.add(this.exit);this.box(this.exit,1.35,2.9,.1,0,1.45,0,this.wood);this.placard(this.exit,['回到房子'],1,.3,0,1.7,.07);this.target(this.exit,'door');this.nextDoor=new THREE.Group();this.nextDoor.position.set(-3.5,0,3.2);this.scene.add(this.nextDoor);this.box(this.nextDoor,1.35,2.9,.1,0,1.45,0,this.wood);this.placard(this.nextDoor,[this.work.n===24?'回到房子':'走向下一段往事'],1.2,.3,0,1.7,.07);this.target(this.nextDoor,'next');
  this.hand=this.buildHand();this.camera.add(this.hand);this.scene.add(this.camera);
  const dust=new THREE.BufferGeometry(),positions=[];for(let i=0;i<160;i++)positions.push((i*37%100)/10-5,(i*17%100)/25,(i*29%100)/8-6);dust.setAttribute('position',new THREE.Float32BufferAttribute(positions,3));this.dust=new THREE.Points(dust,new THREE.PointsMaterial({color:0xe9d9b1,size:.02,transparent:true,opacity:.3,depthWrite:false}));this.materials.push(this.dust.material);this.scene.add(this.dust);
  // Existing literary illustrations are physical pictures in the room, never
  // animated backgrounds. The architecture and consequences are real geometry.
  if(this.renderer.isWebGLRenderer){const frame=new THREE.Group();frame.position.set(-4.8,2.4,-3);frame.rotation.y=.45;this.environment.add(frame);this.box(frame,2.5,1.55,.12,0,0,0,this.wood);const texture=new THREE.TextureLoader().load(`${BASE}art/event-${String(this.work.n).padStart(2,'0')}.jpg`);texture.colorSpace=THREE.SRGBColorSpace;this.textures.push(texture);const material=new THREE.MeshBasicMaterial({map:texture});this.materials.push(material);const picture=new THREE.Mesh(new THREE.PlaneGeometry(2.3,1.35),material);picture.position.z=.08;frame.add(picture);
   this.savedPixelRatio=this.renderer.getPixelRatio();this.savedShadow=this.renderer.shadowMap.enabled;this.renderer.setPixelRatio(pixelBudget(innerWidth,innerHeight,this.lightweight));this.renderer.shadowMap.enabled=!this.lightweight;if(!this.lightweight){this.composer=new EffectComposer(this.renderer);this.composer.addPass(new RenderPass(this.scene,this.camera));this.composer.addPass(new UnrealBloomPass(new THREE.Vector2(innerWidth,innerHeight),.2,.3,.8));this.composer.addPass(new OutputPass());}$('#filmHud').dataset.quality=this.lightweight?'light':'full';this.fpsFrames=0;this.fpsStart=performance.now();}
  this.sceneStats=batchStatic(this.environment,new Set([this.quotePanel]));
 }
 makeSpace(type){const g=this.environment,dark=this.mat(0x173b34),white=this.mat(paper),iron=this.mat(0x263639,{metalness:.5});this.space=type;
  if(type==='harbor'){this.box(g,30,.1,30,0,-.25,-6,this.mat(0x214b59,{metalness:.4,roughness:.18}));for(let z=-1;z<6;z+=.4)this.box(g,5,.12,.37,0,0,z,this.wood);for(let i=0;i<12;i++){const wave=this.box(this.dynamic,5,.015,.08,-5+i*.9,-.15,-5-i*.7,0x87b3b5);this.motions.push((t)=>{wave.position.y=-.15+Math.sin(t+i)*.035;wave.scale.x=1+Math.sin(t*.7+i)*.2})}for(let i=0;i<5;i++){const ship=new THREE.Group();ship.position.set(-7+i*3,0,-5-i%2*3);g.add(ship);this.box(ship,2.1,.35,.75,0,.18,0,wood);this.cylinder(ship,.025,2.8,0,1.7,0,this.brass);const sail=this.placard(ship,[''],1.1,1.6,.58,2,0);sail.material.color.setHex(0xd8cfaa);ship.userData.keepDynamic=true;this.motions.push(t=>ship.rotation.z=Math.sin(t*.65+i)*.018);}this.sun.color.setHex(this.work.n===24?0xffbc7f:0xc6e2ed);}
  else {for(let z=-7;z<7;z+=.5)this.box(g,12,.1,.47,0,-.08,z,this.wood);if(type!=='street'&&type!=='rail'&&type!=='station'){this.box(g,12,5,.15,0,2.4,-6,dark);for(const x of[-6,6])this.box(g,.15,5,13,x,2.4,0,dark);for(const x of[-3,0,3]){this.box(g,1.8,2.7,.09,x,2.7,-5.85,0x789fa2);for(let i=0;i<3;i++)this.box(g,.07,2.7,.12,x-.8+i*.8,2.7,-5.72,this.wood);this.box(g,1.9,.07,.12,x,2.7,-5.7,this.wood);}}
  }
  if(['board','counter','wire'].includes(type)){this.box(g,8,1.2,.7,0,.6,-3,this.wood);this.box(g,8.2,.1,.9,0,1.25,-3,this.wood);this.quotePanel=this.placard(g,['正在等待报价','判断还没有成为成交'],3.5,1.8,-3,2.9,-5.6,true);for(let i=0;i<4;i++)this.actors.push(this.person(-2+i*1.4,0,-4.1,i));if(type==='wire')for(let i=0;i<7;i++){const cable=this.box(g,.015,.015,8,-3+i,3.4,-.5,this.brass);cable.rotation.x=.12;} }
  if(['station','rail'].includes(type)){for(const x of[-3.5,3.5]){this.box(g,.065,.09,30,x,-.01,-6,iron);for(let z=-13;z<7;z+=.6)this.box(g,1.3,.1,.17,x,0,z,this.wood);}this.train=new THREE.Group();this.train.position.set(3.5,0,-7);g.add(this.train);this.box(this.train,2.2,2.2,8,0,1.6,0,0x244036);for(let z=-3;z<4;z+=1.2){this.box(this.train,2.25,.65,.6,0,2.1,z,0x94b1a9);for(const x of[-1,1])this.cylinder(this.train,.38,.15,x,.45,z,iron).rotation.z=Math.PI/2;}for(const x of[-5,5])this.box(g,.16,4,.16,x,2,-2,this.brass);this.box(g,11,.2,5,0,4,-2,iron);this.train.userData.keepDynamic=true;this.motions.push(t=>{this.train.position.z=-7+(this.state==='perform'?Math.min(10,this.time*.3):['epilogue','transition'].includes(this.state)?10:Math.sin(t*.2)*.1)})}
  if(type==='study'){for(const x of[-4,4]){for(let y=.4;y<4;y+=.75){this.box(g,1.3,.07,3,x,y,-2,this.wood);for(let i=0;i<10;i++)this.box(g,.09,.5,.5,x-.48+i*.105,y+.29,-1.3+(i%3)*-.5,0x4c5b47);} }const a=this.person(1.6,0,-2,2);this.actors.push(a);}
  if(type==='cotton'||type==='grain'){this.bales=[];for(let i=0;i<24;i++){const bale=this.box(g,.72,.55,.8,-4+(i%4)*.85,.3+Math.floor(i/8)*.57,-2-Math.floor(i/4)%2,type==='cotton'?paper:0xb8974d);bale.userData.keepDynamic=true;this.bales.push(bale);}for(let i=0;i<3;i++)this.box(g,.2,5,.2,-4+i*4,2.4,-4,this.wood);this.box(g,10,.15,.4,0,4,-4,this.wood);}
  if(type==='industry'){for(let i=0;i<5;i++){this.cylinder(g,.65,2.8,-4+i*2,1.4,-3,iron);this.cylinder(g,.12,5,-4+i*2,2.5,-3,this.brass);}for(let i=0;i<20;i++){const spark=this.sphere(this.dynamic,.025,-3+i*.23,1,-2,0xffc175);this.motions.push(t=>{spark.position.y=1+(t*.7+i*.13)%2;spark.position.x=-3+i*.23+Math.sin(t+i)*.2})}}
  if(type==='street'){for(const x of[-5,5])for(let i=0;i<5;i++){const height=3+i%3;this.box(g,2,height,1.8,x,height/2,-5+i*2,0x3b5352);this.placard(g,['BANK'],1,.45,x,2.2,-3.98+i*2,true);}for(let i=0;i<8;i++)this.actors.push(this.person(-3+i*.8,0,-3+(i%3),i));}
  if(type==='theatre'){this.box(g,10,.4,4,0,.2,-2,this.wood);for(const x of[-4.7,4.7])this.box(g,1,4,.3,x,2.3,-4,0x642d28);this.certificates=[];for(let i=0;i<24;i++){const p=this.box(this.dynamic,.32,.02,.45,-3+i%6,.55+Math.floor(i/6)*.06,-2.2,paper);this.certificates.push(p);}for(let i=0;i<6;i++)this.actors.push(this.person(-3+i*1.2,0,2.5,i));}
  if(type==='press'){for(let i=0;i<3;i++){const machine=new THREE.Group();machine.position.set(-4+i*4,0,-3);g.add(machine);this.box(machine,1.5,1.1,1,0,.6,0,iron);const roll=this.cylinder(machine,.22,1.4,0,1.3,0,this.brass);roll.rotation.z=Math.PI/2;roll.userData.keepDynamic=true;this.motions.push(t=>roll.rotation.x=t*2);this.placard(machine,['业绩出色','前景乐观'],1.1,.75,0,1.7,.2);}}
  if(type==='tailor'){this.box(g,2,.12,1,0,.95,-2,this.wood);const cloth=this.box(g,1.7,.02,.9,0,1.03,-1.9,0x8e5265);cloth.userData.keepDynamic=true;this.motions.push(t=>cloth.rotation.y=Math.sin(t*.3)*.01);this.actors.push(this.person(1.4,0,-2,2));}
 }
 makeObject(kind){this.kind=kind;this.prop=new THREE.Group();this.prop.position.set(0,1,0);this.scene.add(this.prop);this.isPaper=['telegram','newspaper','report','contract','letter','order','tickets'].includes(kind);this.mechanism=null;
  if(this.isPaper){this.scene.remove(this.prop);this.prop=this.card([this.work.phases[this.phase].title,...this.work.phases[this.phase].cue.split(' · ')],['记录留下的另一面',...this.work.phases[this.phase].beats.slice(0,1).flatMap(t=>{const a=[];for(let i=0;i<Math.min(t.length,68);i+=17)a.push(t.slice(i,i+17));return a;})]);this.prop.position.set(0,1.05,0);this.scene.add(this.prop);if(kind==='tickets')for(let i=0;i<6;i++)this.box(this.environment,.46,.01,.65,.55+i*.12,1+i*.008,.15,0xc78f89);}
  else if(kind==='suitcase'){this.box(this.prop,1.25,.35,.7,0,0,0,wood);const lid=new THREE.Group();lid.position.set(0,.16,-.35);this.prop.add(lid);this.box(lid,1.25,.08,.7,0,.02,.35,0x6f4831);this.mechanism=lid;this.placard(this.prop,['NEW YORK','$2,500'],.55,.35,0,.19,0).rotation.x=-Math.PI/2;}
  else if(kind==='safe'||kind==='drawer'){this.box(this.prop,1.2,1.15,.8,0,.05,-.3,0x273c36);const door=new THREE.Group();door.position.set(-.6,.05,.12);this.prop.add(door);this.box(door,1.15,1.05,.09,.57,0,0,this.brass);const wheel=this.cylinder(door,.18,.07,.6,0,.08,wood);wheel.rotation.x=Math.PI/2;this.mechanism=door;this.closingSafe=kind==='safe'&&/合上|锁|关/.test(this.work.phases[this.phase].action);if(this.closingSafe)door.rotation.y=-1.6;this.placard(this.prop,[kind==='safe'?'不再伸手':'现金'],.7,.3,0,.7,.16);}
  else if(kind==='clock'){this.cylinder(this.prop,.55,.18,0,.5,0,this.brass).rotation.x=Math.PI/2;this.placard(this.prop,['Ⅻ','Ⅸ     Ⅲ','Ⅵ'],.9,.9,0,.5,.12);this.mechanism=this.box(this.prop,.035,.4,.04,0,.7,.15,0x172c28);}
  else if(kind==='chair'){this.box(this.prop,.8,.1,.8,0,0,0,this.wood);this.box(this.prop,.8,.9,.1,0,.55,-.35,this.wood);for(const x of[-.3,.3])for(const z of[-.3,.3])this.box(this.prop,.08,.7,.08,x,-.35,z,this.wood);const actor=this.person(0,0,-.4,2);this.actors.push(actor);}
  else if(kind==='phone'){this.cylinder(this.prop,.3,.1,0,0,0,this.brass);this.cylinder(this.prop,.045,.7,0,.35,0,this.brass);const receiver=new THREE.Group();receiver.position.set(.2,.7,0);this.prop.add(receiver);this.cylinder(receiver,.06,.3,0,0,0,wood);for(const y of[-.18,.18])this.cylinder(receiver,.11,.08,0,y,0,wood);this.mechanism=receiver;}
  else if(kind==='wheel'){this.cylinder(this.prop,.48,.06,0,.4,0,this.brass).rotation.x=Math.PI/2;for(let i=0;i<8;i++){const spoke=this.box(this.prop,.05,.7,.05,0,.4,.04,wood);spoke.rotation.z=i*Math.PI/4;}this.mechanism=this.prop;}
  else if(kind==='coin'||kind==='weight'){for(let i=0;i<(kind==='coin'?5:3);i++)this.cylinder(this.prop,.16,.06,0,i*.065,0,this.brass);}
  else if(kind==='cotton'||kind==='grain'||kind==='coffee'){this.box(this.prop,.9,.55,.8,0,.2,0,kind==='cotton'?paper:0x937648);for(const x of[-.35,.35])this.box(this.prop,.035,.6,.84,x,.2,0,wood);this.placard(this.prop,[kind==='cotton'?'棉花':kind==='grain'?'玉米 / 燕麦':'COFFEE'],.6,.3,0,.22,.415);}
  else if(kind==='cat'){this.sphere(this.prop,.18,0,.2,0,0x121b18).scale.set(1,1.6,.6);this.sphere(this.prop,.13,0,.52,0,0x121b18);for(const x of[-.08,.08]){const ear=new THREE.Mesh(new THREE.ConeGeometry(.055,.16,8),this.mat(0x121b18));ear.position.set(x,.64,0);this.prop.add(ear);this.sphere(this.prop,.014,x*.5,.53,.11,0xedd78d);}}
  else if(kind==='oil'){this.cylinder(this.prop,.38,1,0,.35,0,0x273738);for(const y of[0,.6])this.cylinder(this.prop,.4,.035,0,y,0,this.brass);}
  else if(kind==='mirror'||kind==='glass'){for(const x of[-.65,.65]){this.box(this.prop,1.05,1.5,.08,x,.5,-.05,this.wood);const face=this.placard(this.prop,[x<0?'希望':'恐惧'],.95,1.35,x,.5,.02);face.material.color.setHex(x<0?0x8aacb0:0xc1a786);}this.mechanism=this.prop;}
  else if(kind==='curtain'){this.box(this.prop,2.2,2.2,.12,0,.5,0,0x763a37);this.mechanism=this.prop;}
  else if(kind==='needle'){this.box(this.prop,.9,.04,.7,0,0,0,0x915c6c);this.mechanism=this.cylinder(this.prop,.014,.4,0,.3,0,this.brass);this.mechanism.rotation.z=.35;this.stitch=this.box(this.prop,.6,.008,.009,0,.026,0,paper);this.stitch.scale.x=.01;}
  else if(kind==='wire'){this.box(this.prop,1,.1,.6,0,0,0,this.wood);this.mechanism=this.box(this.prop,.08,.08,.55,0,.15,0,this.brass);}
  else if(kind==='chalk'){this.mechanism=this.cylinder(this.prop,.035,.45,0,0,0,paper);this.mechanism.rotation.z=Math.PI/2;}
  else if(kind==='transfer'){for(const x of[-.6,.6])this.box(this.prop,.7,.5,.6,x,.2,0,x<0?0xb99a50:paper);this.mechanism=this.box(this.prop,.4,.04,.3,-.6,.55,0,this.brass);}
  else {this.box(this.prop,.9,.08,.6,0,0,0,this.wood);this.mechanism=this.box(this.prop,.05,.8,.05,0,.4,0,this.brass);this.sphere(this.prop,.1,0,.85,0,0x253a34);}
  if(['chalk','coin','needle'].includes(kind)){const touchMaterial=new THREE.MeshBasicMaterial({transparent:true,opacity:0,depthWrite:false});this.materials.push(touchMaterial);const touch=new THREE.Mesh(new THREE.BoxGeometry(.85,.24,.4),touchMaterial);touch.position.y=.08;this.prop.add(touch);}
  if(!['chair','mirror','curtain'].includes(kind))this.box(this.environment,1.6,.1,1.1,0,.86,0,this.wood);
  this.slot=new THREE.Group();this.slot.position.set(0,1.35,-2);this.scene.add(this.slot);this.box(this.slot,1,.08,.65,0,0,0,this.brass);this.placard(this.slot,['送到这里'],.8,.3,0,.15,-.1);this.target(this.slot,'slot');this.slot.visible=this.work.phases[this.phase].mode==='dispatch';
 }
 setState(name){this.state=name;this.time=0;this.lookX=0;this.lookY=0;$('#filmHud').dataset&&( $('#filmHud').dataset.state=name);$('#filmHint').textContent=this.hint();if(name==='perform'){this.beat=0;this.beatTime=0;this.displayFlip=this.flip;this.tick(170,.06,.1);}if(name==='epilogue'){this.held=null;this.hand.visible=false;this.prop.position.copy(this.home);this.prop.rotation.copy(this.homeRotation);this.prop.scale.setScalar(1);this.freePos.set(0,1.65,4);this.freeYaw=0;this.freePitch=-.17;} }
 hint(){if(this.state==='wait')return this.isPaper?'拿起眼前的纸 · 翻开另一面':'触碰眼前的'+({chalk:'粉笔',chair:'椅子',clock:'钟',phone:'听筒',wheel:'船舵',cat:'黑猫',needle:'针',safe:'柜门',cotton:'棉花包',suitcase:'箱盖'}[this.kind]||'物件');if(this.state==='holding')return this.work.phases[this.phase].mode==='dispatch'?'把手里的物件递到铜盘 · 拖放或按 E':'拖动翻纸，读它的另一面 · 也可按住 E';if(this.state==='working')return this.work.phases[this.phase].action+' · 拖动物件，或按住 E';if(this.state==='epilogue')return '桌上账册可以翻阅。拖动环顾，WASD 走动。两扇门通向下一段往事与房子；R 重走这段往事。';if(this.state==='book')return '点右页往后、左页往前 · E 翻页 / Shift+E 回翻 · L 换册 · 空格放回';return '';}
 hit(x,y){if(this.state==='holding'&&this.work.phases[this.phase].mode==='dispatch'&&this.held){this.held.visible=false;const result=super.hit(x,y);this.held.visible=true;return result;}return super.hit(x,y);}
 pointerDown(x,y){if(this.paused)return;this.initAudio();const id=this.hit(x,y);if(this.state==='arrival'&&id==='object')this.setState('wait');this.drag={x,y,lastX:x,lastY:y,id,total:0};if(this.state==='book'){if(id==='language'){this.switchBook();return;}if(id==='book'){this.drag.bookGesture=true;return;}this.putBook();return;}if(id==='next'&&this.state==='epilogue'){this.onNext?.(this.work.n+1);return;}if(id==='door'&&this.state==='epilogue'){this.onExit?.();return;}if(id==='book'&&this.state==='epilogue'){this.pick(this.book);this.setState('book');this.showBook(0);return;}if(id==='language'&&this.state==='epilogue'){this.pick(this.book);this.setState('book');this.switchBook();return;}if(this.state==='holding'&&id==='slot'){this.beginPerformance();return;}if(this.state!=='wait'||id!=='object')return;
  this.progress=0;if(this.isPaper||this.work.phases[this.phase].mode==='dispatch'){this.pick(this.prop);this.setState('holding');}else{this.setState('working');if(['examine','stamp'].includes(this.work.phases[this.phase].mode))this.beginPerformance();}}
 pointerMove(x,y){this.aim.set(clamp(x/innerWidth*2-1,-1,1),clamp(y/innerHeight*2-1,-1,1));if(this.paused||!this.drag)return;if(this.state==='book'&&this.drag.bookGesture){this.drag.lastX=x;this.drag.lastY=y;return;}const dx=x-this.drag.lastX,dy=y-this.drag.lastY;this.drag.lastX=x;this.drag.lastY=y;this.drag.total+=Math.hypot(dx,dy);if(this.state==='holding'&&this.work.phases[this.phase].mode!=='dispatch'){this.flip=clamp(this.flip+(Math.abs(dx)+Math.abs(dy)*.5)/(innerWidth*.4),0,1);if(this.flip>.95){this.flip=1;this.beginPerformance();}}else if(this.state==='working'){this.progress=clamp(this.progress+(Math.abs(dx)+Math.abs(dy))/(innerHeight*.4),0,1);if(this.progress>.95)this.beginPerformance();}else if(!this.held){if(this.state==='epilogue'){this.freeYaw-=dx*.003;this.freePitch=clamp(this.freePitch-dy*.002,-.65,.65);}else {this.lookX=clamp(this.lookX-dx*.003,-.7,.7);this.lookY=clamp(this.lookY+dy*.002,-.3,.3);}} }
 pointerUp(x,y){if(this.paused){this.drag=null;return;}if(this.state==='book'&&this.drag?.bookGesture){this.finishBookGesture(x,y);return;}if(this.state==='holding'&&this.work.phases[this.phase].mode==='dispatch'&&this.hit(x,y)==='slot')this.beginPerformance();this.drag=null;}
 beginPerformance(){this.progress=1;this.dispatching=this.work.phases[this.phase].mode==='dispatch';this.dispatchStart=this.prop.position.clone();this.setState('perform');this.drag=null;}
 keyDown(e){if(e.code==='Escape'){this.onExit?.();return;}if(e.code==='KeyP'){e.preventDefault();this.setPaused(!this.paused);return;}if(this.paused)return;if(e.code==='KeyR'){this.close();this.open(this.work.n);return;}if(this.state==='epilogue'&&['KeyW','KeyA','KeyS','KeyD'].includes(e.code)){this.keys.add(e.code);e.preventDefault();return;}if(e.code==='KeyL'&&['book','epilogue'].includes(this.state)){e.preventDefault();if(this.state==='epilogue'){this.pick(this.book);this.setState('book');}this.switchBook();return;}if(e.code==='Space'&&this.state==='book'){e.preventDefault();this.putBook();return;}if(['KeyE','Space'].includes(e.code)){e.preventDefault();if(e.repeat)return;this.initAudio();this.keyHeld=true;if(this.state==='book')this.showBook(this.page+(e.shiftKey?-1:1));else if(this.state==='epilogue'){this.pick(this.book);this.setState('book');this.showBook(0);}else if(this.state==='wait'){this.progress=0;if(this.isPaper||this.work.phases[this.phase].mode==='dispatch'){this.pick(this.prop);this.setState('holding');}else{this.setState('working');if(['examine','stamp'].includes(this.work.phases[this.phase].mode))this.beginPerformance();}}else if(this.state==='holding'&&this.work.phases[this.phase].mode==='dispatch')this.beginPerformance();}}
 keyUp(e){if(['KeyE','Space'].includes(e.code))this.keyHeld=false;this.keys?.delete(e.code);}
 switchBook(){this.language=this.language==='en'?'zh':'en';this.showBook(0);}
 showBook(page){const pages=this.language==='en'?this.originalPages:this.notePages;this.page=clamp(page,0,Math.max(0,pages.length-1));const lines=pages[this.page]||[this.manuscriptError?'另一册暂时没有送到。':'另一册正在送来。','按 L 返回私人记述。'];const old=this.bookPage.material.map;const texture=this.canvasTexture((c,w,h)=>{c.fillStyle='#e5d6b4';c.fillRect(0,0,w,h);c.strokeStyle='#917b56';c.lineWidth=3;c.strokeRect(35,35,w-70,h-70);c.fillStyle='#25382d';c.textAlign='center';c.font='28px Georgia';c.fillText(this.language==='en'?'PRIVATE ACCOUNT':'私人记述',w/2,90);c.textAlign='left';c.font=(this.language==='en'?'36px Georgia':'48px Microsoft YaHei')+',serif';lines.forEach((line,i)=>c.fillText(line,82,195+i*(this.language==='en'?82:100),w-164));c.textAlign='center';c.font='25px Georgia';c.fillText(`${this.page+1} / ${pages.length||1}`,w/2,h-60);},1024,1447);this.bookPage.material.map=texture;this.bookPage.material.emissiveMap=texture;this.bookPage.material.emissiveIntensity=.22;if(old){old.dispose();this.textures=this.textures.filter(t=>t!==old);}this.flip=0;this.tick(210,.045,.06);}
 putBook(){this.held=null;this.hand.visible=false;this.book.position.set(-2.7,.97,1.2);this.book.rotation.set(0,0,0);this.book.scale.setScalar(.9);this.setState('epilogue');}
 update(dt){if(!this.active)return;this.resize();if(!this.paused&&dt>0){this.time+=dt;this.elapsed+=dt;this.updateState(dt);this.updateScene(dt);this.narration();}this.render();}
 updateState(dt){if(this.state==='arrival'&&this.time>8)this.setState('wait');if(this.keyHeld&&this.state==='working'){this.progress=clamp(this.progress+dt*.6,0,1);if(this.progress>=1)this.beginPerformance();}if(this.keyHeld&&this.state==='holding'&&!this.dispatching&&this.work.phases[this.phase].mode!=='dispatch'){this.flip=clamp(this.flip+dt*.65,0,1);if(this.flip>=1)this.beginPerformance();}if(this.state==='perform'){this.beatTime+=dt;const beat=this.work.phases[this.phase].beats[this.beat];if(this.beatTime>Math.max(5.5,beat.length/6.5)){this.beatTime=0;this.beat++;if(this.beat>=this.work.phases[this.phase].beats.length){this.held=null;this.hand.visible=false;this.setState(this.phase<2?'transition':'epilogue');}}}if(this.state==='transition'&&this.time>1.2){this.dispose();this.phase++;this.build();this.setState('arrival');$('#filmTitle').textContent=this.work.phases[this.phase].title;} }
 narration(){const p=this.work.phases[this.phase];$('#filmCaption').textContent=this.state==='perform'?p.beats[Math.min(this.beat,p.beats.length-1)]:this.state==='arrival'||this.state==='wait'?p.title:this.state==='epilogue'?this.work.chapter.quote:'';$('#filmHint').textContent=this.hint();const clue=this.state==='perform'&&!this.held&&this.beatTime>1;$('#filmThought').textContent=clue?p.cue:'';$('#filmFact').textContent=clue&&this.beatTime>2.2?['观察留下了什么','指令改变了什么','结果没有替我省掉下一次判断'][this.phase]:'';$('#filmThought').style.opacity=String(ease(this.beatTime/1.2));$('#filmFact').style.opacity='1';}
 updateScene(dt){const s=this.state,t=this.time,p=this.progress;for(const f of this.motions)f(this.elapsed);for(const a of this.actors){const walk=['street','theatre'].includes(this.space),cycle=this.elapsed*(s==='perform'?2:1)+a.seed;a.head.rotation.y=Math.sin(cycle*.4)*.17;a.root.position.x=a.base.x+(walk?Math.sin(cycle*.3)*.5:0);for(let i=0;i<2;i++){a.arms[i].arm.rotation.x=-.4+Math.sin(cycle+i*Math.PI)*.15;a.arms[i].fore.rotation.x=-.4-Math.sin(cycle)*.12;a.legs[i].rotation.x=walk?Math.sin(cycle+i*Math.PI)*.25:0;}}
  if(this.mechanism){if(this.kind==='suitcase')this.mechanism.rotation.x=lerp(this.mechanism.rotation.x,-p*1.8,1-Math.exp(-dt*6));if(['safe','drawer'].includes(this.kind))this.mechanism.rotation.y=lerp(this.mechanism.rotation.y,-1.6*(this.closingSafe?1-p:p),1-Math.exp(-dt*6));if(this.kind==='clock')this.mechanism.rotation.z-=dt*(s==='perform'?.7:.04);if(['lever','gate','wire'].includes(this.kind))this.mechanism.rotation.z=lerp(.5,-.5,p);if(this.kind==='phone'){this.mechanism.position.y=lerp(this.mechanism.position.y,.7+p*.3,1-Math.exp(-dt*6));this.mechanism.rotation.z=lerp(this.mechanism.rotation.z,p*.5,1-Math.exp(-dt*6));}if(this.kind==='wheel')this.prop.rotation.z=p*1.5+Math.sin(this.elapsed*.3)*.06;if(this.kind==='transfer')this.mechanism.position.x=lerp(-.6,.6,ease(p));if(this.kind==='curtain')this.prop.position.y=lerp(this.prop.position.y,1+p*2,1-Math.exp(-dt*5));if(this.kind==='needle'){const sewn=s==='perform'?ease(t/18):p;this.mechanism.position.x=lerp(-.3,.3,sewn);this.mechanism.position.y=.2+Math.sin(this.elapsed*8)*.1;if(this.stitch){this.stitch.scale.x=Math.max(.01,sewn);this.stitch.position.x=-.3+sewn*.3;}}if(this.kind==='chalk'){this.mechanism.position.x=lerp(-.35,.35,p);this.mechanism.position.z=Math.sin(this.elapsed*1.3)*.15;} }
  if(s==='perform'&&this.quotePanel&&!this.boardWritten&&t>3){this.boardWritten=true;const old=this.quotePanel.material.map;const lines=this.work.phases[this.phase].cue.split(' · ');const map=this.canvasTexture((c,w,h)=>{c.fillStyle='#172d27';c.fillRect(0,0,w,h);c.fillStyle='#e5dab9';c.textAlign='center';c.font='42px Microsoft YaHei';lines.forEach((line,i)=>c.fillText(line,w/2,85+i*70,w-70));},768,384);this.quotePanel.material.map=map;if(old){old.dispose();this.textures=this.textures.filter(x=>x!==old);}}
  if(s==='perform'&&this.kind==='chalk'){const v=ease(t/2);this.prop.position.lerpVectors(this.home,new THREE.Vector3(-3+Math.sin(t*2)*.65,2.8+Math.cos(t*1.5)*.2,-5.45),v);}
  if(s==='perform'&&this.bales&&this.kind==='cotton')this.bales.forEach((b,i)=>b.position.y=.3+Math.floor(i/8)*.57+ease(t/25)*(i%3)*.7);
  if(s==='perform'&&this.certificates)this.certificates.forEach((c,i)=>{const v=ease((t-i*.4)/12);c.position.z=lerp(-2.2,2.1,v);c.rotation.y=v*.4;});
  const position=this.desiredPosition.set(0,1.65,4.5),look=this.desiredLook.set(0,1.25,0);if(s==='arrival')position.z=lerp(6,3.8,ease(t/8));if(s==='perform'){const duration=Math.max(30,this.work.phases[this.phase].beats.reduce((sum,b)=>sum+Math.max(5.5,b.length/6.5),0)),v=ease(t/duration);position.set(Math.sin(v*Math.PI*1.5)*2.2,1.7+Math.sin(v*Math.PI)*.4,3.5+v*1.2);look.set(lerp(0,-.8,v),1.4,-.5);}if(s==='book'||this.held){position.set(0,1.65,3.8);look.set(0,1.4,0);}if(s==='epilogue'){const x=(this.keys.has('KeyD')?1:0)-(this.keys.has('KeyA')?1:0),z=(this.keys.has('KeyS')?1:0)-(this.keys.has('KeyW')?1:0),speed=dt*1.5/(Math.hypot(x,z)||1);this.freePos.x=clamp(this.freePos.x+(x*Math.cos(this.freeYaw)-z*Math.sin(this.freeYaw))*speed,-4.8,4.8);this.freePos.z=clamp(this.freePos.z+(x*Math.sin(this.freeYaw)+z*Math.cos(this.freeYaw))*speed,.7,5.5);position.copy(this.freePos);look.set(position.x+Math.sin(this.freeYaw)*3,position.y+Math.sin(this.freePitch)*3,position.z-Math.cos(this.freeYaw)*3);}
  look.x+=this.lookX*2;look.y+=this.lookY;const blend=1-Math.exp(-dt*3);this.cameraPosition.lerp(position,blend);this.cameraLook.lerp(look,blend);this.camera.position.copy(this.cameraPosition);this.camera.lookAt(this.cameraLook);
  if(this.held){const scale=innerWidth<600?.68:1.04,point=new THREE.Vector3(this.aim.x*.035,-.03,-.85);this.camera.localToWorld(point);this.held.position.lerp(point,1-Math.exp(-dt*8));this.held.quaternion.copy(this.camera.quaternion);this.held.rotateX(Math.PI/2);this.displayFlip=lerp(this.displayFlip,this.flip,1-Math.exp(-dt*12));this.held.rotateZ(this.displayFlip*Math.PI);this.held.scale.setScalar(scale);this.hand.position.set(.21,-.36,-.82);this.hand.visible=true;if(this.dispatching&&s==='perform'){this.held.position.lerpVectors(this.dispatchStart,new THREE.Vector3(0,1.4,-2),ease(t/2));if(t>2){this.held=null;this.hand.visible=false;}}else if(s==='perform'&&t>12){this.held.position.copy(this.home);this.held.rotation.copy(this.homeRotation);this.held.scale.setScalar(1);this.held=null;this.hand.visible=false;}}
  this.dust.rotation.y=this.elapsed*.01;this.audioTick+=dt;if(this.audioTick>.45){this.audioTick=0;this.tick(['harbor','study'].includes(this.space)?130:260,.04,.025);}const fade=s==='transition'?1-ease(t/1.1):s==='arrival'?ease(t/.8):1;this.sun.intensity=3.1*fade;this.lampLight.intensity=10*fade;this.scene.background.setScalar(.065*fade);$('#sceneFade').style.opacity=String(s==='transition'?ease(t/1.1):s==='arrival'?1-ease(t/.8):0);
 }
 close(){this.sourceRequest=(this.sourceRequest||0)+1;super.close();}
}
