import * as THREE from 'three';
import {episodes} from './episodes.js';
import {chapters} from './content.js';
const $=s=>document.querySelector(s);
const BASE=(import.meta.env?.BASE_URL || './');
const paper=0xe6d7b7,brass=0xbd985c,ink=0x17291f,wood=0x4d2e1c;
export class StoryDirector {
 constructor(renderer,{onClose,onArchive}){this.renderer=renderer;this.onClose=onClose;this.onArchive=onArchive;this.active=false;this.cache=new Map();this.loader=new THREE.TextureLoader();this.camera=new THREE.PerspectiveCamera(52,innerWidth/innerHeight,.1,120);this.ray=new THREE.Raycaster();this.clock=0;this.value=0;this.phase=0;this.orbit=0;this.playing=false;this.auto=false;this.held=false;this.reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
 $('#episodeClose').onclick=()=>this.close();$('#episodeNext').onclick=()=>this.next();$('#episodePrev').onclick=()=>{if(this.phase>0)this.showPhase(this.phase-1)};$('#episodeArchive').onclick=()=>this.onArchive(this.ep.n);$('#episodePlay').onclick=()=>{this.playing=!this.playing;this.auto=false;this.playTime=0;$('#episodePlay').textContent=this.playing?'暂停镜头':'播放镜头';};
 }
 open(n){this.ep=episodes.find(e=>e.n===n);if(!this.ep)return;this.active=true;this.playing=false;this.orbit=0;$('#episode').hidden=false;document.body.classList.add('in-story');this.showPhase(0);this.preload(n);}
 close(){this.active=false;this.playing=false;this.auto=false;this.held=false;$('#episode').hidden=true;document.body.classList.remove('in-story');this.disposeScene();this.onClose();}
 preload(n){const url=`${BASE}art/event-${String(n).padStart(2,'0')}.jpg`;if(!this.cache.has(n)){const texture=this.loader.load(url,()=>{},undefined,()=>{if(this.active&&this.ep.n===n)$('#artNote').textContent='画面载入失败，仍可操作实时场景与阅读事件。';});texture.colorSpace=THREE.SRGBColorSpace;this.cache.set(n,texture);while(this.cache.size>4){const old=this.cache.keys().next().value;this.cache.get(old).dispose();this.cache.delete(old);}}}
 showPhase(p){this.phase=p;this.clock=0;this.value=0;this.auto=false;this.held=false;this.playTime=0;this.step=this.ep.steps[p];this.disposeScene();this.buildScene();$('#episodeMeta').textContent=`原书 ${chapters.find(c=>c.n===this.ep.n).roman} · 事件 ${String(this.ep.n).padStart(2,'0')}`;$('#episodeTitle').textContent=this.ep.title;$('#momentTitle').textContent=this.step.title;$('#episodeNarration').textContent=this.step.text;$('#sourceAnchor').textContent=this.step.anchor;$('#episodePrev').disabled=p===0;$('#episodeNext').textContent=p===2?'回到长廊':'下一幕';$('#episodePlay').textContent=this.playing?'暂停镜头':'播放镜头';$('#artNote').textContent='原创文学画面 · 动作与镜头为实时演出';$('#stepTabs').innerHTML=this.ep.steps.map((s,i)=>`<button class="${i===p?'current':''}" data-phase="${i}" aria-current="${i===p?'step':'false'}"><span>0${i+1}</span>${s.title}</button>`).join('');$('#stepTabs').querySelectorAll('button').forEach(b=>b.onclick=()=>{this.playing=false;this.showPhase(Number(b.dataset.phase));});this.buildControls();this.setValue(0);}
 next(){if(this.phase<2)this.showPhase(this.phase+1);else this.close();}
 buildControls(){const s=this.step;let body='';if(['scrub','drag','dial','lever','transfer'].includes(s.mode))body=`<label class="gesture-label" for="gestureRange">${s.action}</label><input id="gestureRange" type="range" min="0" max="100" value="0"><div class="range-ends"><span>${s.mode==='transfer'?(this.ep.n===12?'盈利的小麦':'原处'):'开始'}</span><span>${s.mode==='transfer'?(this.ep.n===12?'亏损的棉花':'另一端'):'展开'}</span></div>`;else if(s.mode==='trace')body=`<span class="gesture-label">${s.action}</span><div id="traceSurface" role="button" tabindex="0" aria-label="${s.action}；也可按空格"><span>在这里划动 · 或按空格</span><svg viewBox="0 0 300 65" aria-hidden="true"><path id="traceInk" d="M15 48 L280 18" fill="none" stroke="#d8ba78" stroke-width="3" pathLength="100" stroke-dasharray="100" stroke-dashoffset="100"/></svg></div>`;else body=`<button id="gestureButton" class="gesture-button">${s.action}</button><p class="gesture-help">${s.mode==='hold'?'按住持续操作；点击可自动演出。':s.mode==='flip'?'翻开另一面，看被遮住的行动。':s.mode==='stamp'?'落下签章，观察它怎样改变场景。':'点击触发这一刻；也可以点击场景中的物件。'}</p>`;$('#episodeAction').innerHTML=body+`<div class="action-progress" aria-hidden="true"><i id="actionFill"></i></div><p id="actionCaption">你可以操作物件，也可以直接看下一幕。</p>`;
 const range=$('#gestureRange');if(range)range.oninput=()=>this.setValue(Number(range.value)/100);
 const button=$('#gestureButton');if(button){button.onpointerdown=()=>{if(s.mode==='hold')this.held=true;};for(const e of ['pointerup','pointercancel','pointerleave'])button.addEventListener(e,()=>this.held=false);button.onclick=()=>{if(s.mode==='hold')this.auto=true;else if(s.mode==='flip'){this.setValue(this.value<.5?1:0);}else this.auto=true;};button.onkeydown=e=>{if(e.code==='Space'){e.preventDefault();this.auto=true;}};}
 const trace=$('#traceSurface');if(trace){let last;trace.onpointerdown=e=>{last=e.clientX;trace.setPointerCapture(e.pointerId);};trace.onpointermove=e=>{if(last===undefined)return;this.setValue(this.value+Math.abs(e.clientX-last)/200);last=e.clientX;};for(const e of ['pointerup','pointercancel'])trace.addEventListener(e,()=>last=undefined);trace.onclick=()=>this.auto=true;trace.onkeydown=e=>{if(e.code==='Space'||e.code==='Enter'){e.preventDefault();this.auto=true;}};}
 }
 setValue(v){this.value=THREE.MathUtils.clamp(v,0,1);$('#actionFill').style.width=`${this.value*100}%`;if($('#traceInk'))$('#traceInk').style.strokeDashoffset=String(100-this.value*100);if($('#gestureRange'))$('#gestureRange').value=String(Math.round(this.value*100));$('#actionCaption').textContent=this.value>.95?'这一刻已经展开。可以继续、重放，或查看原书转述。':this.value>.05?'让物件继续动作，观察场景的变化。':'你可以操作物件，也可以直接看下一幕。';}
 pointer(x,y,dx=0,dy=0){if(dx||dy){this.orbit=THREE.MathUtils.clamp(this.orbit-dx*.003,-.7,.7);return;}this.ray.setFromCamera(new THREE.Vector2(x/innerWidth*2-1,-y/innerHeight*2+1),this.camera);if(this.ray.intersectObjects(this.objects.children,true).length)this.auto=true;}
 material(c,extra={}){return new THREE.MeshStandardMaterial({color:c,roughness:.65,...extra});}
 box(g,w,h,d,x,y,z,c){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),typeof c==='number'?this.material(c):c);m.position.set(x,y,z);g.add(m);return m;}
 cyl(g,r,h,x,y,z,c){const m=new THREE.Mesh(new THREE.CylinderGeometry(r,r,h,24),this.material(c));m.position.set(x,y,z);g.add(m);return m;}
 ball(g,r,x,y,z,c){const m=new THREE.Mesh(new THREE.SphereGeometry(r,18,12),this.material(c));m.position.set(x,y,z);g.add(m);return m;}
 label(g,text,x,y,z,w=3,h=.5,color='#f2dfb8'){const c=document.createElement('canvas');c.width=1024;c.height=Math.round(1024*h/w);const ct=c.getContext('2d');ct.font='54px Microsoft YaHei,serif';ct.textAlign='center';ct.textBaseline='middle';ct.fillStyle=color;ct.fillText(text,512,c.height/2,990);const texture=new THREE.CanvasTexture(c);texture.colorSpace=THREE.SRGBColorSpace;const m=new THREE.Sprite(new THREE.SpriteMaterial({map:texture,transparent:true,depthWrite:false}));m.scale.set(w,h,1);m.position.set(x,y,z);g.add(m);return m;}
 buildScene(){this.scene=new THREE.Scene();this.scene.background=new THREE.Color(0x0b1410);this.objects=new THREE.Group();this.scene.add(this.objects);this.motion=[];this.scene.add(new THREE.HemisphereLight(0xe5d4b4,0x1a3e31,2));const light=new THREE.PointLight(0xffd9a4,85,24,2);light.position.set(-3,6,4);this.scene.add(light);const rim=new THREE.PointLight(0x69a9b6,50,20,2);rim.position.set(4,3,-2);this.scene.add(rim);
 this.preload(this.ep.n);const texture=this.cache.get(this.ep.n);const art=new THREE.Mesh(new THREE.PlaneGeometry(24,13.5),new THREE.MeshBasicMaterial({map:texture,color:0xa8a59a}));art.position.set(0,4,-8);this.scene.add(art);this.art=art;
 const g=this.objects,p=this.phase;const floorColor=['station','panic','money','theatre'].includes(this.ep.stage)?0x26362e:wood;this.box(g,12,.16,7,0,-.1,0,floorColor);if(!['station','panic','theatre','chair'].includes(this.ep.stage)){this.box(g,8,.12,2.7,0,.85,.1,wood);for(const x of [-3.2,3.2])this.box(g,.15,.85,2.4,x,.4,.1,ink);}else if(this.ep.stage==='station'){for(const x of [-2,2]){this.box(g,.075,.035,6,x,0,0,brass);for(let j=0;j<8;j++)this.box(g,4.4,.025,.1,0,-.015,j*.6-2,wood);}}else if(this.ep.stage==='panic'){for(let j=0;j<4;j++)this.box(g,7,.14,1.3,0,j*.15,-1-j*.7,0x566158);}else if(this.ep.stage==='theatre'){for(let row=0;row<3;row++)for(let seat=0;seat<6;seat++)this.box(g,.65,.7,.65,(seat-2.5)*1.05,.4+row*.2,2+row*.75,0x522e31);}
 const stage=this.ep.stage;this.primary=new THREE.Group();g.add(this.primary);const a=this.primary;
 if(['chalk','ticker','absorb','credit','industry','reverse','rebuild'].includes(stage)){this.box(a,5.5,2.7,.2,0,2.5,-.7,wood);this.box(a,5.2,2.4,.05,0,2.5,-.55,ink);this.label(a,['chalk','ticker'].includes(stage)?(stage==='ticker'?'纸带报价  /  实际成交':'BURLINGTON  ·  STEEL  ·  SUGAR'):stage==='rebuild'?'BETHLEHEM   90 … 100':stage==='industry'?'IMPERIAL STEEL  /  PETROLEUM':'报价仍然在变',0,3.2,-.4,4.9,.5);this.columns=[];for(let i=0;i<14;i++){const h=.15+(i%5)*.22;const m=this.box(a,.2,h,.1,-2.1+i*.32,1.4+h/2,-.36,i%2?brass:0x6caa9b);this.columns.push(m);}this.marker=this.label(a,stage==='ticker'?'回报尚未到达':stage==='chalk'?'尚未写下观察':'等待市场回答',0,2.6,-.35,4.8,.55);this.motion.push(v=>{this.columns.forEach((m,i)=>{m.scale.y=1+v*(i+1)*.1+(stage==='ticker'?Math.sin(this.clock*3+i)*v*.5:0);});this.marker.material.opacity=.35+v*.65;});if(stage==='chalk')this.motion.push(v=>{this.columns.forEach((m,i)=>m.visible=i/14<v);});}
 if(['station','telegrams','telegraph','coffee','loan','newspaper','letter'].includes(stage)){this.pages=[];for(let i=0;i<9;i++){const m=this.box(a,1.25,.025,.8,(i%3-1)*1.6,1.05+Math.floor(i/3)*.065,0,paper);m.rotation.y=(i-4)*.04;this.pages.push(m);}const heading=stage==='coffee'?'咖啡合约 / 新的限制':stage==='loan'?'借款 / 人情 / 账户权限':stage==='telegrams'?'买入建议 / 卖出建议':stage==='newspaper'?'匿名解释 / 真实出售':stage==='letter'?'今天的佣金 / 明天的企业':'报价 / 建议 / 成交';this.label(a,heading,0,2.4,0,5,.6);this.motion.push(v=>{this.pages.forEach((m,i)=>{m.rotation.y=(i-4)*.04+v*(i%2?Math.PI:0);m.position.y=1.05+Math.floor(i/3)*.065+v*Math.sin(i)*.4;m.position.x=(i%3-1)*1.6+v*(i-4)*.08;});});if(['coffee','loan','telegrams'].includes(stage)){this.stamp=this.cyl(a,.24,.5,0,2.7,.15,brass);this.motion.push(v=>{this.stamp.position.y=2.7-Math.sin(v*Math.PI/2)*1.4;});}if(stage==='letter'){this.lines=[];for(let i=0;i<7;i++)this.lines.push(this.box(a,1.05,.006,.015,0,1.215,-.3+i*.085,ink));this.motion.push(v=>this.lines.forEach((m,i)=>m.visible=i/7<v));}}
 if(['cotton','grain','coffee'].includes(stage)){this.bales=new THREE.Group();a.add(this.bales);this.wheat=new THREE.Group();a.add(this.wheat);for(let i=0;i<18;i++){const x=(i%6-2.5)*.7,y=1.2+Math.floor(i/6)*.65;const b=this.box(this.bales,.64,.6,.6,x,y,-.2,stage==='coffee'?0x5f3825:paper);for(const dx of [-.18,.18])this.box(this.bales,.025,.63,.64,x+dx,y,-.2,wood);}for(let i=0;i<5;i++){this.ball(this.wheat,.32,-2+i*.42,1.2,.6,brass);}this.motion.push(v=>{this.bales.scale.setScalar(.35+v*.8);this.bales.position.z=v*(stage==='cotton'&&p>0?1.5:0);this.wheat.position.x=-v*4;this.wheat.scale.setScalar(1-v*.75);});this.label(a,stage==='cotton'?['专家的资料','小麦在盈利 / 棉花在亏损','棉花约十五万包'][p]:stage==='grain'?'玉米 / 燕麦 / 退出':'供给 / 运输 / 合约',0,3.4,0,5,.55);}
 if(stage==='chair'){this.box(a,1.6,.2,1.4,0,1.2,.2,0x2e5741);this.box(a,1.6,1.8,.2,0,2.1,-.4,0x2e5741);for(const x of [-.8,.8]){this.box(a,.12,1.1,1.5,x,1.3,.2,wood);this.box(a,.1,.9,.1,x,.5,.75,wood);}this.label(a,p===1?'不是工作。是位置。':'这是牛市。',0,3.5,-.2,4,.6);this.motion.push(v=>{a.rotation.y=v*.2;});}
 if(['panic','money','rebuild','credit','loan'].includes(stage)){this.safe=new THREE.Group();this.safe.position.set(2.3,1,.8);a.add(this.safe);this.box(this.safe,1.4,1.5,1.1,0,.7,0,ink);this.safeDoor=new THREE.Group();this.safeDoor.position.set(-.7,.7,.61);this.safe.add(this.safeDoor);this.box(this.safeDoor,1.38,1.45,.08,.69,0,0,0x43514c);const knob=this.cyl(this.safeDoor,.13,.1,.8,0,.1,brass);knob.rotation.x=Math.PI/2;this.motion.push(v=>{this.safeDoor.rotation.y=-v*1.8;});this.cash=[];for(let i=0;i<7;i++)this.cash.push(this.box(a,.65,.055,.32,-2,1.1+i*.075,.8,paper));this.motion.push(v=>this.cash.forEach((m,i)=>m.visible=i/7>v||stage==='rebuild'));if(stage==='loan'){this.bars=new THREE.Group();a.add(this.bars);for(let i=0;i<9;i++)this.box(this.bars,.065,4,.06,-3+i*.75,2,-.7,0x2a3436);this.motion.push(v=>{this.bars.position.z=p===0?-3+v:1+v;});}}
 if(['mirrors','breakfast'].includes(stage)){for(const x of [-2,2]){this.box(a,1.7,2.8,.14,x,2.4,-.2,brass);const m=this.box(a,1.5,2.6,.16,x,2.4,-.1,new THREE.MeshStandardMaterial({color:0x79948e,metalness:1,roughness:.18}));this.motion.push(v=>{m.material.emissive.setHex(x<0?0x925133:0x387263);m.material.emissiveIntensity=x<0?v:1-v;});}this.label(a,stage==='mirrors'?'希望 / 恐惧':'朋友的黑猫 / 我的观察',0,3.9,0,5,.55);if(stage==='breakfast'){const cat=new THREE.Group();cat.position.set(-.3,1.3,.6);a.add(cat);this.ball(cat,.22,0,0,0,0x101712);this.ball(cat,.15,.2,.2,0,0x101712);this.box(cat,.04,.2,.07,.15,.4,0,0x101712);this.motion.push(v=>{cat.position.x=-.3-v*3;});}}
 if(['phones','absorb','theatre'].includes(stage)){this.tokens=[];for(let i=0;i<18;i++){const m=this.box(a,.48,.018,.32,-3+(i%6)*1.1,1.2+Math.floor(i/6)*.25,-.25+(i%3)*.3,paper);this.tokens.push(m);}this.motion.push(v=>this.tokens.forEach((m,i)=>{m.position.x=-3+(i%6)*1.1+Math.sin(v*Math.PI)*(stage==='absorb'?i*.08:2);m.position.z=-.25+(i%3)*.3+v*Math.floor(i/6);m.rotation.y=v*Math.PI*.5;}));if(stage==='phones'){for(const x of [-2,0,2]){this.cyl(a,.28,.12,x,1.05,.6,ink);this.cyl(a,.045,.9,x,1.5,.6,brass);this.cyl(a,.18,.3,x,2.05,.6,brass).rotation.z=Math.PI/3;}this.label(a,'同一个源头，经过不同的嘴。',0,3.3,0,5,.55);}if(stage==='theatre'){this.curtains=[];for(const x of [-3.6,3.6])for(let j=0;j<4;j++)this.curtains.push(this.cyl(a,.22,4.3,x+j*.22*(x<0?1:-1),2.2,-.8,0x652c35));this.motion.push(v=>this.curtains.forEach((m,i)=>m.position.x=(i<4?-3.6:3.6)+(i%4)*.22*(i<4?1:-1)+(i<4?-1:1)*v*1.4));this.label(a,'台上的报价 / 台下的接手者',0,3.7,0,5,.55);}}
 if(stage==='dressmaker'){this.box(a,1.35,.15,.65,0,1.3,0,ink);this.box(a,.22,.85,.24,-.45,1.7,0,ink);this.box(a,1,.18,.24,0,2.1,0,ink);this.cyl(a,.035,.45,.48,1.87,0,brass);this.wheel=this.cyl(a,.37,.1,-.72,1.88,0,brass);this.wheel.rotation.z=Math.PI/2;this.box(a,2,.035,1.5,1,1.1,.2,0x667263);this.thread=this.box(a,1.7,.005,.025,1,1.13,.2,brass);this.motion.push(v=>{this.wheel.rotation.x=v*Math.PI*4;this.thread.scale.x=Math.max(.01,v);});this.label(a,'她买下的，是一个名字的许诺。',0,3.4,0,5,.55);}
 if(stage==='station'){this.suitcase=new THREE.Group();this.suitcase.position.set(0,1.3,.7);a.add(this.suitcase);this.box(this.suitcase,1.8,1.1,.5,0,0,0,wood);for(const x of [-.5,.5])this.box(this.suitcase,.07,1.14,.52,x,0,0,brass);this.motion.push(v=>{this.suitcase.position.z=.7-v*1.4;this.suitcase.rotation.y=v*.4;});this.label(a,'二十一岁 / 两千五百美元',0,3.2,0,5,.55);}
 if(stage==='ticker'){this.strips=[];for(let i=0;i<22;i++){const m=this.box(a,1.7,.015,.3,Math.sin(i*.5)*1.4,1.1+Math.floor(i/7)*.17,.7+i*.045,paper);m.rotation.y=i*.3;this.strips.push(m);}this.motion.push(v=>this.strips.forEach((m,i)=>{m.position.z=.7+i*.045+Math.sin(this.clock*(i%2?.4:2)+i)*v*.35;}));}
 if(stage==='reverse'){this.lever=new THREE.Group();this.lever.position.set(0,1.1,1);a.add(this.lever);this.box(this.lever,.07,1.2,.07,0,.6,0,brass);this.ball(this.lever,.17,0,1.2,0,ink);this.motion.push(v=>{this.lever.rotation.z=(v-.5)*1.4;});this.label(a,p===1?'153：回补一万股':p===2?'156：转为买入':'总体弱市 / 局部强势',0,2.3,.2,5,.55);}
 this.buildMoment();const dust=new THREE.BufferGeometry();const points=[];for(let i=0;i<100;i++)points.push((Math.random()-.5)*12,Math.random()*6,(Math.random()-.5)*8);dust.setAttribute('position',new THREE.Float32BufferAttribute(points,3));this.scene.add(new THREE.Points(dust,new THREE.PointsMaterial({size:.018,color:brass,transparent:true,opacity:.45})));
 }

 buildMoment(){const n=this.ep.n,p=this.phase,g=this.objects;const focus=new THREE.Group();g.add(focus);const sheet=(x,y,z,w=1.1)=>this.box(focus,w,.018,.8,x,y,z,paper);const caption=(t,x=0,y=3,z=.6,w=4)=>this.label(focus,t,x,y,z,w,.4);const animate=f=>this.motion.push(f);
 if(n===1){if(p===0){const chalk=this.box(focus,.09,.09,.65,-2,2.7,.55,paper);animate(v=>chalk.position.x=-2+v*4);}if(p===1){const coin=this.cyl(focus,.25,.05,0,1.3,1.3,brass);animate(v=>{coin.position.x=-2+v*4;coin.rotation.z=v*Math.PI;});caption('五美元 → 三美元十二美分',0,3.6);}if(p===2){for(let i=0;i<7;i++){const m=this.box(focus,.52,.018,.7,(i-3)*.7,1.25,1.4,0xe6a7aa);animate(v=>m.position.y=1.25+v*.3);}caption('七张 · 每张五百股',0,3.6);}}
 if(n===2&&p===1){const order=sheet(-2,2,.8);animate(v=>order.position.x=-2+v*4);caption('指令送出 ≠ 已经成交',0,3.8);}
 if(n===3){for(const [i,t]of['纸带报价','实际成交'].entries()){this.box(focus,5,.025,.025,0,2.8-i*.55,.7,brass);caption(t,-3.4,2.8-i*.55,.7,1.6);const dot=this.ball(focus,.11,-2.5,2.8-i*.55,.7,i?0xca7660:0x93b69b);animate(v=>{dot.position.x=-2.5+v*(i?5:2);});}if(p===2){const receipt=sheet(0,3.2,1.3);animate(v=>{receipt.position.y=3.2-v*2;receipt.rotation.y=v*.3;});}}
 if(n===4){for(const sign of[-1,1]){const t=sheet(0,2.1,1.2);t.material.color.setHex(sign<0?0x90b9a0:0xcd9b91);caption(sign<0?'买入电报':'卖出电报',sign*2,3,.9,2);animate(v=>{t.position.x=sign*v*2;t.rotation.y=sign*v*.5;});}}
 if(n===5&&p===2){const pos=sheet(0,2.6,.9);animate(v=>{pos.position.x=v*4.5;pos.position.y=2.6+v*.3;});caption('一旦离开，买回的机会不一定出现',0,3.9,0,5);}
 if(n===6){const wire=sheet(-2,2,.6);animate(v=>{wire.position.x=-2+v*4;wire.rotation.y=v*Math.PI;});caption(['地震已发生 / 反应仍滞后','友人的判断盖过了自己的观察','新事实改变方向'][p],0,4,.6,5);}
 if(n===7){const order=sheet(-2.5,2.6,1.3);animate(v=>{order.position.x=-2.5+v*5;order.scale.setScalar(1-v*.7);});caption(['卖出一万股','再卖一万股','回补两万 / 留下一万股多头'][p],0,4,.6,5);}
 if(n===8){const pendulum=this.ball(focus,.15,0,3,1,brass);animate(v=>pendulum.position.x=Math.sin(v*Math.PI*2)*2);caption(['信用先变紧','正确方向，也会付出等待的成本','一轮比一轮弱的反弹'][p],0,4,.6,5);}
 if(n===9){const newspaper=sheet(0,3,.5,2);animate(v=>{newspaper.rotation.x=v*1.2;newspaper.position.y=3-v*1.5;});caption(['船上：几行字，改变整个航程','街上：现金成为生存的条件','回补：卖空者也交出买单'][p],0,4,0,5);}
 if(n===10){caption(['损失二十万美元，仍推不动','1.14 → 等待 → 1.20','亏损时恐惧 / 获利时希望'][p],0,4,.6,5);}
 if(n===11){const oat=new THREE.Group();focus.add(oat);for(let i=0;i<8;i++)this.ball(oat,.12,-2+i*.2,1.5,.9,0xb39363);animate(v=>{oat.position.x=v*3;});caption(['一千万蒲式耳的玉米仓位','燕麦订单改变了对手的认知','皇冠来自消息误读'][p],0,4,.6,5);}
 if(n===12&&p===0){const report=sheet(2,2,.8,1.6);animate(v=>{report.position.x=2-v*2;report.position.y=2+v*.45;report.rotation.x=v*.8;});caption('同一份报告，渐渐遮住全部市场',0,4,.6,5);}
 if(n===13){for(let i=0;i<8;i++){const ring=new THREE.Mesh(new THREE.TorusGeometry(.12,.025,8,16),this.material(brass));ring.position.set(-1.3+i*.35,2.5,.8);focus.add(ring);animate(v=>{ring.rotation.y=i%2*Math.PI/2;ring.position.y=2.5-v*.7*Math.sin(i/7*Math.PI);});}caption(['二万五千美元 / 钱可以还，人情怎么办','订单上，多出另一双手','叙述者事后解释这份帮助'][p],0,4,.6,5);}
 if(n===14&&p===1){for(let week=0;week<6;week++){const m=sheet(-2+week*.8,2.6,.7,.5);animate(v=>m.rotation.x=Math.min(1,Math.max(0,v*6-week))*Math.PI);}caption('六周，等到价格越过一百',0,4,.6,5);}
 if(n===15){const ruling=this.box(focus,2,.03,1.2,0,2.6,1,0xd4b09d);animate(v=>ruling.position.y=2.6-v*1.1);caption(['供给判断 / 战争运输','申诉进入另一套制度','规则的纸，覆盖交易的纸'][p],0,4,.6,5);}
 if(n===16){for(let i=0;i<5;i++){const line=this.box(focus,.025,.025,1,-2+i,2.6,.8,brass);line.rotation.z=Math.PI/2;animate(v=>line.scale.z=Math.min(1,Math.max(0,v*5-i)));}}
 if(n===17&&p===1){for(const [i,color]of[0x779f8d,0x8e694a].entries()){const m=this.box(focus,.5,1,.5,-1.5+i*3,1.5,1.3,color);animate(v=>m.scale.y=i?1:1+v*1.4);}caption('钢铁继续 / 铜股停住',0,4,.6,5);}
 if(n===19){const cheque=sheet(-1,2.7,1.2,2);animate(v=>{cheque.position.x=-1+v*3;cheque.rotation.y=v*1.3;});caption(['融资的时钟开始转动','认证支票没有流回银行','缺钱的人，不能等到明天'][p],0,4,.6,5);}
 if(n===21){for(let i=0;i<3;i++){const m=this.cyl(focus,.23,2,-2.5+i*.5,1.8,-.6,0x5e6e69);animate(v=>{m.scale.y=p===0?1+v*.7:1-v*.15;});}for(let i=0;i<3;i++){const m=this.cyl(focus,.35,.7,1.5+i*.7,1.3,.6,0x443e31);animate(v=>{m.position.x=1.5+i*.7+(p===1?v*.3:v);});}caption(['钢铁：安静吸收供给','石油：另一种需求，另一种结果','报价财富 / 实际退出'][p],0,4,.6,5);}
 if(n===22&&p===2){const certificate=sheet(1,1.3,1.2,1.5);animate(v=>{certificate.rotation.y=v*.6;certificate.position.x=1-v*1.8;});}
 if(n===23){const newspaper=sheet(0,2.6,1.5,2.5);animate(v=>{newspaper.rotation.x=v*Math.PI/2;newspaper.position.y=2.6-v*.6;});caption(['名字不见了 / 信心被留下','翻开宣传，才看见出售','50 → 12 / 谁来承担解释'][p],0,4,.6,5);}
 if(n===24){const pen=this.box(focus,.025,.025,.8,-.8,1.4,1.2,brass);pen.rotation.y=.6;animate(v=>pen.position.x=-.8+v*1.6);caption(['佣金今天到账 / 公司明天还要营业','拿到的股票，改变了消息的讲法','没有下一条买卖指令'][p],0,4,.6,5);}
 }
 update(dt){if(!this.active)return;this.clock+=dt;if(this.auto||this.held)this.setValue(this.value+dt*(this.reduced?100:.55));if(this.value>=1)this.auto=false;if(this.playing&&!document.querySelector('dialog[open]')){this.playTime+=dt;this.setValue(Math.min(1,this.playTime/7));if(this.playTime>13){if(this.phase<2)this.showPhase(this.phase+1);else{this.playing=false;$('#episodePlay').textContent='播放镜头';}}}
 const v=this.value;for(const f of this.motion)f(v);this.camera.aspect=innerWidth/innerHeight;this.camera.updateProjectionMatrix();const swing=this.reduced?0:Math.sin(this.clock*.13)*.2;const px=Math.sin(this.orbit+swing)*5;this.camera.position.set(px,2.7+this.phase*.15,(8.5-v*.7)*Math.max(1,.85/this.camera.aspect));this.camera.lookAt(0,1.85,0);if(this.ep.stage==='ticker'&&this.phase===2&&!this.reduced)this.camera.position.x+=Math.sin(this.clock*22)*v*.035;this.art.material.color.setScalar(.62+v*.12);this.renderer.render(this.scene,this.camera);}
 disposeScene(){if(!this.scene)return;const keep=new Set(this.cache.values());this.scene.traverse(o=>{if(o.geometry)o.geometry.dispose();if(o.material){const mats=Array.isArray(o.material)?o.material:[o.material];for(const m of mats){if(m.map&&!keep.has(m.map))m.map.dispose();m.dispose();}}});this.scene=null;}
}
