import * as THREE from 'three';
import {EffectComposer} from 'three/addons/postprocessing/EffectComposer.js';
import {RenderPass} from 'three/addons/postprocessing/RenderPass.js';
import {UnrealBloomPass} from 'three/addons/postprocessing/UnrealBloomPass.js';
import {ShaderPass} from 'three/addons/postprocessing/ShaderPass.js';
import {mergeGeometries} from 'three/addons/utils/BufferGeometryUtils.js';
import {OutputPass} from 'three/addons/postprocessing/OutputPass.js';
const $=s=>document.querySelector(s),clamp=THREE.MathUtils.clamp,lerp=THREE.MathUtils.lerp;
const ease=t=>{t=clamp(t,0,1);return t*t*(3-2*t)};
const COLORS={wood:0x3b2419,green:0x183b31,brass:0xbe9251,paper:0xe4d4ad,ink:0x172720};
const filmShader={uniforms:{tDiffuse:{value:null},time:{value:0},fade:{value:1}},vertexShader:'varying vec2 vUv; void main(){vUv=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:'uniform sampler2D tDiffuse;uniform float time;uniform float fade;varying vec2 vUv;void main(){vec3 c=texture2D(tDiffuse,vUv).rgb;vec2 p=vUv*2.-1.;float vignette=1.-.28*dot(p,p);float noise=fract(sin(dot(vUv+time*.0001,vec2(12.9898,78.233)))*43758.5453)-.5;c*=vignette;c+=noise*.012;c=mix(c,vec3(dot(c,vec3(.299,.587,.114))),.07);gl_FragColor=vec4(c*fade,1.);}'};
export const FILM_SCRIPT={
 entrance:['纽约 · 1901年5月9日','那天早晨，我有近五万美元现金，手里没有股票。','我以为，先抓住下跌，再抓住反弹，两边都能挣钱。'],
 dispatch:['我把一批市价卖单送进了市场。','柜台另一端，他们正在处理比平时多得多的订单。'],
 falling:['行情纸带还在缓慢地吐出数字。','真正的成交，已经在另一个时间里。','报价一百。等我的订单成交时，价格已到八十。'],
 buyDispatch:['我在原本想买入的位置，卖出了股票。','我决定回补空头，并转为买入。'],
 recovery:['我的指令追着市场走，纸带仍落在后面。','等买单送到场内，成交又比我预想的高了平均十五点。'],
 ending:['市场的下跌和反弹，都发生了。','方向看对了。我仍然失去了所有本金。','我曾把纸带当作最可靠的朋友。那天，它说的是已经过去的事。']
};
export class TickerFilm {
 constructor(renderer,{onExit}={}){this.renderer=renderer;this.onExit=onExit;this.active=false;this.paused=false;this.time=0;this.elapsed=0;this.ray=new THREE.Raycaster();this.pointer=new THREE.Vector2(0,0);this.aim=new THREE.Vector2(0,0);this.targets=[];this.actors=[];this.materials=[];this.textures=[];this.motions=[];this.sounds=true;this.reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;this.camera=new THREE.PerspectiveCamera(54,innerWidth/innerHeight,.06,70);this.cameraPosition=new THREE.Vector3();this.cameraLook=new THREE.Vector3();this.desiredPosition=new THREE.Vector3();this.desiredLook=new THREE.Vector3();
 $('#filmExit').onclick=()=>this.onExit?.();$('#filmPause').onclick=()=>this.setPaused(!this.paused);$('#filmAudio').onclick=()=>{this.sounds=!this.sounds;$('#filmAudio').textContent=this.sounds?'声音 开':'声音 关';if(this.audio){this.audio.resume();this.ambient.gain.setTargetAtTime(this.sounds?.035:0,this.audio.currentTime,.2);}};}
 open(){this.active=true;this.paused=false;this.time=0;this.elapsed=0;this.pull=0;this.flip=0;this.aim.set(0,0);this.lookX=0;this.lookY=0;this.drag=null;this.keyHeld=false;this.held=null;this.hover=null;this.page=0;this.caption='';this.audioTick=0;this.keys=new Set();this.freeYaw=-.14;this.freePitch=-.2;this.freePos=new THREE.Vector3(-.15,1.6,2.5);this.build();this.state='entrance';if($('#filmHud').dataset)$('#filmHud').dataset.state='entrance';this.cameraPosition.set(0,1.65,6.8);this.cameraLook.set(0,1.4,-.7);this.camera.position.copy(this.cameraPosition);this.camera.lookAt(this.cameraLook);$('#filmHud').hidden=false;document.body.classList.add('in-film');$('#filmPause').textContent='暂停';$('#filmTitle').textContent='1901年5月9日';$('#filmHint').textContent='';$('#world').setAttribute('aria-label','1901年5月9日连续三维样片：直接操作桌上的订单、行情机纸带与成交回报');this.resize();}
 close(){this.active=false;this.paused=false;this.held=null;this.drag=null;$('#filmHud').hidden=true;document.body.classList.remove('in-film');$('#world').setAttribute('aria-label','可自由探索的三维记忆宫殿');this.dispose();if(this.audio)this.audio.suspend();}
 setPaused(v){this.paused=v;this.drag=null;this.keyHeld=false;this.keys?.clear();$('#filmPause').textContent=v?'继续':'暂停';$('#filmPause').setAttribute('aria-pressed',String(v));$('#filmHint').textContent=v?'时间停下了。继续，或按 Esc 返回房子。':this.hint();}
 mat(color,extra={}){const key=color+'|'+JSON.stringify({...extra,map:extra.map?.uuid});if(this.matCache?.has(key))return this.matCache.get(key);const m=new THREE.MeshStandardMaterial({color,roughness:.58,...extra});this.materials.push(m);this.matCache?.set(key,m);return m;}
 box(g,w,h,d,x,y,z,m){const o=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),typeof m==='number'?this.mat(m):m);o.position.set(x,y,z);o.castShadow=true;o.receiveShadow=true;g.add(o);return o;}
 cylinder(g,r,h,x,y,z,m,segments=32){const o=new THREE.Mesh(new THREE.CylinderGeometry(r,r,h,segments),typeof m==='number'?this.mat(m):m);o.position.set(x,y,z);o.castShadow=true;o.receiveShadow=true;g.add(o);return o;}
 sphere(g,r,x,y,z,m){const o=new THREE.Mesh(new THREE.SphereGeometry(r,24,16),typeof m==='number'?this.mat(m):m);o.position.set(x,y,z);o.castShadow=true;g.add(o);return o;}
 canvasTexture(draw,w=1024,h=768){const canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;draw(canvas.getContext('2d'),w,h);const texture=new THREE.CanvasTexture(canvas);texture.colorSpace=THREE.SRGBColorSpace;this.textures.push(texture);return texture;}
 print(lines,{w=1024,h=768,dark=false,title='HARDING BROTHERS',footer='NEW YORK · 1901'}={}){return this.canvasTexture((c,w,h)=>{c.fillStyle=dark?'#16342c':'#e5d6b4';c.fillRect(0,0,w,h);c.strokeStyle=dark?'#ad925c':'#8f7b53';c.lineWidth=3;c.strokeRect(38,35,w-76,h-70);c.fillStyle=dark?'#e7d6ae':'#263b32';c.textAlign='center';c.font='30px Georgia';c.fillText(title,w/2,88);c.fillRect(90,112,w-180,2);c.font='48px Microsoft YaHei,serif';lines.forEach((line,i)=>c.fillText(line,w/2,195+i*76,w-150));c.font='22px Georgia';c.fillText(footer,w/2,h-68);},w,h);}
 placard(g,lines,w,h,x,y,z,dark=false){const tex=this.print(lines,{dark,h:Math.round(1024*h/w)});const m=new THREE.MeshBasicMaterial({map:tex});this.materials.push(m);const o=new THREE.Mesh(new THREE.PlaneGeometry(w,h),m);o.position.set(x,y,z);g.add(o);return o;}
 card(front,back){const g=new THREE.Group();const edge=this.box(g,.46,.005,.65,0,0,0,COLORS.paper);const f=new THREE.Mesh(new THREE.PlaneGeometry(.46,.65),new THREE.MeshStandardMaterial({map:this.print(front),roughness:.95}));f.rotation.x=-Math.PI/2;f.position.y=.004;g.add(f);f.material.emissive.setHex(0xffffff);f.material.emissiveMap=f.material.map;f.material.emissiveIntensity=.14;const b=new THREE.Mesh(new THREE.PlaneGeometry(.46,.65),new THREE.MeshStandardMaterial({map:this.print(back),roughness:.95}));b.rotation.x=Math.PI/2;b.position.y=-.004;g.add(b);b.material.emissive.setHex(0xffffff);b.material.emissiveMap=b.material.map;b.material.emissiveIntensity=.14;this.materials.push(f.material,b.material);g.userData.edge=edge;return g;}
 target(g,id){g.traverse(o=>o.userData.filmTarget=id);this.targets.push(g);g.userData.id=id;return g;}
 woodTexture(){return this.canvasTexture((c,w,h)=>{c.fillStyle='#523724';c.fillRect(0,0,w,h);for(let j=0;j<850;j++){const y=j*h/850;c.strokeStyle=j%4?'#20140a22':'#e6a56015';c.lineWidth=.5+j%3;c.beginPath();c.moveTo(0,y);for(let x=0;x<=w;x+=32)c.lineTo(x,y+Math.sin(x*.007+j)*3);c.stroke();}},512,512);}
 build(){this.scene=new THREE.Scene();this.scene.background=new THREE.Color(0x102322);this.scene.fog=new THREE.FogExp2(0x142b28,.026);this.targets=[];this.actors=[];this.materials=[];this.textures=[];this.motions=[];this.matCache=new Map();this.lastTapePrice=null;this.lastWidth=0;
 const g=this.scene,wood=this.mat(0xb8a38a,{map:this.woodTexture()}),brass=this.mat(COLORS.brass,{metalness:.72,roughness:.28}),dark=this.mat(COLORS.green),paper=this.mat(COLORS.paper);this.brass=brass;this.wood=wood;
 this.scene.add(new THREE.HemisphereLight(0xa7c7d0,0x342115,1.05));this.sun=new THREE.DirectionalLight(0xffd6a0,3.4);this.sun.position.set(-4,7,-12);this.sun.castShadow=true;this.sun.shadow.mapSize.set(1024,1024);this.sun.shadow.camera.left=-9;this.sun.shadow.camera.right=9;this.sun.shadow.camera.top=9;this.sun.shadow.camera.bottom=-9;this.sun.shadow.normalBias=.03;g.add(this.sun);
 this.lampLight=new THREE.PointLight(0xffb45b,6,8,2);this.lampLight.position.set(-.8,1.9,.1);g.add(this.lampLight);const cold=new THREE.PointLight(0x7ea9bc,30,12,2);cold.position.set(3,3,-4);g.add(cold);
 for(let z=-7;z<7;z+=.42)this.box(g,12,.1,.4,0,-.06,z,wood);this.box(g,12,1.65,.25,0,.8,-7,dark);this.box(g,12,.65,.25,0,4.7,-7,dark);for(const x of[-5.8,-1.9,1.9,5.8])this.box(g,.65,3.2,.25,x,3,-7,dark);this.box(g,.25,5,14,6,2.45,0,dark);this.box(g,.25,5,14,-6,2.45,0,dark);this.box(g,12,.2,14,0,5,0,0x273c35);
 for(const x of[-5.9,5.9]){this.box(g,.08,1.2,14,x,.6,0,wood);for(let z=-6;z<=6;z+=1.4)this.box(g,.09,1.15,.035,x,.62,z,brass);}for(let x=-5;x<6;x+=1.5)this.box(g,.08,1.2,.06,x,.6,-6.82,brass);this.box(g,11.7,.07,.06,0,1.25,-6.8,brass);
 // Windows are actual geometry, with parallax outside rather than a background picture.
 for(let k=0;k<3;k++){const x=-3.8+k*3.8;const pane=this.box(g,2.4,2.35,.11,x,3,-6.66,this.mat(0x8aaeb1,{transparent:true,opacity:.14,roughness:.05}));pane.castShadow=false;for(const dx of[-1.3,0,1.3])this.box(g,.065,2.7,.16,x+dx,3,-6.58,wood);for(const y of[1.7,3,4.3])this.box(g,2.65,.055,.16,x,y,-6.58,wood);}
 for(let i=0;i<18;i++){const x=(i-8.5)*1.3;const h=2.2+(i*7%9)*.4;this.box(g,1.08,h,.8,x,h/2,-9-i%3,0x4d6663);for(let y=.5;y<h;y+=.55)for(const dx of[-.27,.27])this.box(g,.18,.25,.03,x+dx,y,-8.55-i%3,0xbeb49a);}
 this.door=new THREE.Group();this.door.position.set(-2.5,0,5.5);g.add(this.door);this.box(this.door,1.5,2.9,.15,.75,1.45,0,wood);this.sphere(this.door,.06,1.32,1.35,-.13,brass);this.target(this.door,'door');this.door.rotation.y=-.15;
 // An office with counter, work desks and continuously animated people.
 this.box(g,8,1.2,.9,0,.6,-3,wood);this.box(g,8.25,.12,1.08,0,1.22,-3,wood);for(let x=-3.5;x<4;x+=.7)this.box(g,.035,1.1,.035,x,.58,-2.52,brass);
 this.box(g,3,.13,1.4,0,.95,.2,wood);for(const x of[-1.28,1.28])for(const z of[-.32,.72])this.box(g,.09,.9,.09,x,.45,z,wood);this.box(g,1,.012,1.15,.12,1.022,.22,this.mat(0x15372d,{roughness:.95}));
 this.slot=new THREE.Group();this.slot.position.set(.38,1.28,-2.35);g.add(this.slot);this.box(this.slot,1,.1,.65,0,0,0,wood);this.box(this.slot,.86,.012,.5,0,.06,0,brass);this.placard(this.slot,['订单'],.62,.3,0,.23,-.12);this.target(this.slot,'slot');
 const lamp=new THREE.Group();lamp.position.set(-.8,1.02,.05);g.add(lamp);this.cylinder(lamp,.18,.055,0,0,0,brass);this.cylinder(lamp,.03,.68,0,.36,0,brass);const shade=new THREE.Mesh(new THREE.ConeGeometry(.3,.25,32,1,true),this.mat(0x285546,{side:THREE.DoubleSide}));shade.rotation.x=Math.PI;shade.position.set(0,.71,0);lamp.add(shade);
 this.sellCard=this.card(['市价卖出','不限定成交价格','先抓住下跌'],['五月九日 · 上午','现金近五万美元','手中没有股票']);this.sellCard.position.set(.12,1.072,.3);this.sellCard.rotation.y=-.16;g.add(this.sellCard);this.target(this.sellCard,'sell');
 this.buyCard=this.card(['回补空头','随后转为买入','市价指令'],['我以为八十附近','已是可以买入的低位','市场不会一直下跌']);this.buyCard.position.set(.12,1.08,.3);this.buyCard.visible=false;g.add(this.buyCard);this.target(this.buyCard,'buy');
 this.receipt=this.card(['卖出成交回报','实际成交：八十','原书解释性价格示例'],['纸带显示：一百','实际卖出：八十','晚了二十点']);this.receipt.position.set(.65,1.07,.55);this.receipt.visible=false;g.add(this.receipt);this.target(this.receipt,'receipt1');
 this.receipt2=this.card(['买入成交回报','成交比预期高','平均十五点'],['两次指令追赶行情','原书叙述：一天损失三十五点','本金全部失去']);this.receipt2.position.set(.4,1.08,.55);this.receipt2.visible=false;g.add(this.receipt2);this.target(this.receipt2,'receipt2');
 this.book=new THREE.Group();this.book.position.set(-.8,1.07,.55);this.book.rotation.y=.12;g.add(this.book);this.box(this.book,.5,.035,.65,0,0,0,dark);this.bookPage=this.placard(this.book,['五月九日','拉里 · 利文斯顿'],.46,.62,0,.023,0);this.bookPage.rotation.x=-Math.PI/2;this.target(this.book,'book');
 this.buildTicker(paper,brass);this.buildBoard();this.buildClock();
 for(let i=0;i<5;i++)this.actors.push(this.person(i-2,0,-4.2,i));this.actors.push(this.person(-4.3,0,1.6,5));this.actors.push(this.person(4.5,0,-.2,6));this.courier=this.person(2.65,0,-2.15,7);this.actors.push(this.courier);
 this.hand=this.buildHand();this.camera.add(this.hand);this.scene.add(this.camera);
 const particles=new THREE.BufferGeometry(),arr=[];for(let i=0;i<160;i++)arr.push((i*37%100)/10-5,(i*17%100)/22,(i*29%100)/8-6);particles.setAttribute('position',new THREE.Float32BufferAttribute(arr,3));this.dust=new THREE.Points(particles,new THREE.PointsMaterial({color:0xf4d099,size:.014,transparent:true,opacity:.22,depthWrite:false}));g.add(this.dust);
 this.mergeArchitecture();if(this.renderer.isWebGLRenderer){this.fpsStart=performance.now();this.fpsFrames=0;this.savedPixelRatio=this.renderer.getPixelRatio();this.renderer.setPixelRatio(Math.min(this.savedPixelRatio,innerWidth<650?1.25:1.5));this.savedShadow=this.renderer.shadowMap.enabled;this.renderer.shadowMap.enabled=true;this.composer=new EffectComposer(this.renderer);this.composer.addPass(new RenderPass(g,this.camera));this.bloom=new UnrealBloomPass(new THREE.Vector2(innerWidth,innerHeight),.22,.5,.82);this.composer.addPass(this.bloom);this.grade=new ShaderPass(filmShader);this.composer.addPass(this.grade);this.composer.addPass(new OutputPass());}
 }

 mergeArchitecture(){const groups=new Map();for(const o of this.scene.children){if(!o.isMesh||o===this.tape||this.paperLoops.includes(o))continue;const key=o.material.uuid+o.castShadow;if(!groups.has(key))groups.set(key,[]);groups.get(key).push(o);}for(const objects of groups.values()){if(objects.length<2)continue;const geo=objects.map(o=>{o.updateMatrix();return o.geometry.clone().applyMatrix4(o.matrix);});const merged=mergeGeometries(geo,false);if(!merged){geo.forEach(g=>g.dispose());continue;}const mesh=new THREE.Mesh(merged,objects[0].material);mesh.castShadow=objects[0].castShadow;mesh.receiveShadow=true;this.scene.add(mesh);for(const o of objects){this.scene.remove(o);o.geometry.dispose();}geo.forEach(g=>g.dispose());}}
 buildTicker(paper,brass){const g=new THREE.Group();g.position.set(1.2,1.02,.05);this.scene.add(g);this.machine=g;this.cylinder(g,.28,.08,0,0,0,brass);this.cylinder(g,.09,.2,0,.12,0,brass);this.cylinder(g,.19,.1,0,.28,0,brass);for(const x of[-.12,.12])this.cylinder(g,.025,.35,x,.29,.02,brass);this.wheel=this.cylinder(g,.14,.08,0,.42,0,brass);this.wheel.rotation.x=Math.PI/2;this.cylinder(g,.012,.25,0,.42,.01,brass).rotation.z=Math.PI/2;const glass=this.sphere(g,.29,0,.32,0,this.mat(0xb8dad0,{transparent:true,opacity:.12,roughness:.08,metalness:.12}));glass.scale.y=1.1;
 this.tapeCanvas=document.createElement('canvas');this.tapeCanvas.width=256;this.tapeCanvas.height=2048;this.tapeContext=this.tapeCanvas.getContext('2d');this.tapeTexture=new THREE.CanvasTexture(this.tapeCanvas);this.tapeTexture.colorSpace=THREE.SRGBColorSpace;this.tapeTexture.wrapT=THREE.RepeatWrapping;this.textures.push(this.tapeTexture);this.tapeMaterial=new THREE.MeshStandardMaterial({map:this.tapeTexture,side:THREE.DoubleSide,roughness:1});this.materials.push(this.tapeMaterial);
 this.tapeGeometry=new THREE.PlaneGeometry(.12,1.4,1,65);this.tape=new THREE.Mesh(this.tapeGeometry,this.tapeMaterial);this.tape.position.set(1.18,1.44,.05);this.scene.add(this.tape);this.target(this.tape,'tape');this.grip=this.sphere(this.scene,.16,1.18,1.28,.6,this.mat(0xffffff,{transparent:true,opacity:0,depthWrite:false}));this.grip.castShadow=false;this.target(this.grip,'tape');this.paperLoops=[];for(let i=0;i<8;i++){const loop=new THREE.Mesh(new THREE.TorusGeometry(.16+i*.016,.009,8,48,Math.PI*1.8),this.mat(COLORS.paper));loop.position.set(1.02+Math.sin(i)*.15,.12+i*.027,1.1+i*.06);loop.rotation.set(.7+i*.21,i*.19,.4);this.scene.add(loop);this.paperLoops.push(loop);}this.paintTape(100);}
 paintTape(value){const c=this.tapeContext;c.fillStyle='#e8dcbf';c.fillRect(0,0,256,2048);c.fillStyle='#273b31';c.font='30px Georgia';c.textAlign='center';for(let i=0;i<24;i++){c.fillText('N.Y.  '+String(value-i%3),128,75+i*84);c.fillRect(24,98+i*84,208,1);}this.tapeTexture.needsUpdate=true;}
 buildBoard(){this.board=new THREE.Group();this.board.position.set(-4.95,2.3,-2);this.board.rotation.y=Math.PI/2.9;this.scene.add(this.board);this.box(this.board,2.9,1.7,.13,0,0,0,this.wood);this.boardDisplay=this.placard(this.board,['交易所 · 此刻','市场正在开盘'],2.7,1.5,0,0,.09,true);this.boardLast='';}
 setBoard(lines){const key=lines.join('|');if(this.boardLast===key)return;this.boardLast=key;const old=this.boardDisplay.material.map;const tx=this.print(lines,{dark:true,h:570,title:'STOCK EXCHANGE',footer:'价格为原书解释性示例'});this.boardDisplay.material.map=tx;if(old){old.dispose();this.textures=this.textures.filter(t=>t!==old);}}
 buildClock(){const g=new THREE.Group();g.position.set(3.7,3.85,-6.45);this.scene.add(g);this.cylinder(g,.42,.12,0,0,0,this.brass).rotation.x=Math.PI/2;this.clockFace=this.placard(g,['Ⅻ','Ⅸ      Ⅲ','Ⅵ'],.76,.76,0,0,.085);this.clockLong=this.box(g,.018,.32,.025,0,.13,.11,0x1e2921);this.clockShort=this.box(g,.025,.21,.025,0,.085,.13,0x1e2921);}
 person(x,y,z,seed){const root=new THREE.Group();root.position.set(x,y,z);this.scene.add(root);const suit=this.mat(seed%2?0x26332f:0x373b35),skin=this.mat(seed%2?0xa88364:0xb69577),shirt=this.mat(0xdccfb1);this.box(root,.43,.62,.24,0,1.12,0,suit);this.box(root,.13,.36,.25,0,1.22,.018,shirt);this.box(root,.055,.3,.026,0,1.2,.155,0x3e261e);const head=this.sphere(root,.13,0,1.62,0,skin);head.scale.set(.84,1.1,.82);this.sphere(root,.13,0,1.69,-.015,this.mat(0x29221d)).scale.set(1,.47,1);this.box(root,.065,.07,.07,0,1.61,.11,skin);for(const dx of[-.045,.045])this.sphere(root,.012,dx,1.65,.106,this.mat(0x302a22));
 const arms=[],legs=[];for(const sign of[-1,1]){const arm=new THREE.Group();arm.position.set(sign*.25,1.36,0);root.add(arm);this.box(arm,.12,.3,.13,0,-.14,0,suit);const fore=new THREE.Group();fore.position.y=-.3;arm.add(fore);this.box(fore,.11,.28,.12,0,-.13,0,suit);this.sphere(fore,.066,0,-.3,0,skin);arms.push({arm,fore});const leg=new THREE.Group();leg.position.set(sign*.115,.8,0);root.add(leg);this.box(leg,.15,.73,.17,0,-.35,0,suit);this.box(leg,.17,.09,.29,0,-.73,.045,0x171f1b);legs.push(leg);}return{root,arms,legs,head,seed,base:new THREE.Vector3(x,y,z)};}
 buildHand(){const hand=new THREE.Group(),skin=this.mat(0xb69472),cuff=this.mat(0xe0d4b8),sleeve=this.mat(0x28382f);this.box(hand,.17,.35,.15,0,-.25,0,sleeve);this.box(hand,.18,.07,.15,0,-.045,0,cuff);this.sphere(hand,.105,0,.04,0,skin).scale.set(.8,1,.45);this.fingers=[];for(let i=0;i<4;i++){const finger=new THREE.Group();finger.position.set(-.06+i*.04,.095,-.015);hand.add(finger);this.cylinder(finger,.017,.09,0,.045,0,skin,12);const tip=this.cylinder(finger,.015,.065,0,.105,.018,skin,12);tip.rotation.x=.5;this.fingers.push(finger);}this.sphere(hand,.035,-.095,.03,.035,skin).scale.y=1.5;hand.position.set(.26,-.5,-.65);hand.visible=false;return hand;}
 resize(){if(this.lastWidth===innerWidth&&this.lastHeight===innerHeight)return;this.lastWidth=innerWidth;this.lastHeight=innerHeight;this.camera.aspect=innerWidth/innerHeight;this.camera.fov=innerWidth<600?65:54;this.camera.updateProjectionMatrix();if(this.composer)this.composer.setSize(innerWidth,innerHeight);}
 hit(x,y){this.pointer.set(x/innerWidth*2-1,-y/innerHeight*2+1);this.ray.setFromCamera(this.pointer,this.camera);const hits=this.ray.intersectObjects(this.targets,true);return hits.find(h=>{let o=h.object;while(o){if(!o.visible)return false;if(['holdingSell','holdingBuy'].includes(this.state)&&o===this.held)return false;o=o.parent;}return true;})?.object.userData.filmTarget||null;}
 actionable(id){return ({order:['sell'],holdingSell:['slot'],tape:['tape'],receipt:['receipt1'],inspectSell:['receipt1'],buy:['buy'],holdingBuy:['slot'],receiptBuy:['receipt2'],inspectBuy:['receipt2'],epilogue:['book','door'],book:['book','door']})[this.state]?.includes(id);}
 pointerDown(x,y){if(this.paused)return;this.initAudio();const id=this.hit(x,y);this.drag={x,y,lastX:x,lastY:y,id,total:0};if(this.state==='book'&&!id){this.putBook();return;}if(!this.actionable(id))return;
 if(id==='sell'){this.pick(this.sellCard);this.setState('holdingSell');}else if(id==='buy'){this.pick(this.buyCard);this.setState('holdingBuy');}else if(id==='slot'&&this.held){this.deliver();}else if(id==='receipt1'&&this.state==='receipt'){this.pick(this.receipt);this.flip=0;this.setState('inspectSell');}else if(id==='receipt2'&&this.state==='receiptBuy'){this.pick(this.receipt2);this.flip=0;this.setState('inspectBuy');}else if(id==='book'){if(this.state==='epilogue'){this.pick(this.book);this.setState('book');this.showBook(0);}else this.showBook((this.page+1)%4);}else if(id==='door')this.onExit?.();}
 pointerMove(x,y){this.aim.set(clamp(x/innerWidth*2-1,-1,1),clamp(y/innerHeight*2-1,-1,1));if(this.paused)return;if(this.drag){const dx=x-this.drag.lastX,dy=y-this.drag.lastY;this.drag.total+=Math.hypot(dx,dy);this.drag.lastX=x;this.drag.lastY=y;if(this.state==='tape'&&this.drag.id==='tape'){this.pull=clamp(this.pull+(Math.abs(dy)+Math.abs(dx)*.45)/(innerHeight*.38),0,1);if(this.pull>.94)this.setState('falling');}else if(['inspectSell','inspectBuy'].includes(this.state)){this.flip=clamp(this.flip+(Math.abs(dx)+Math.abs(dy)*.5)/(innerWidth*.42),0,1);if(this.flip>.93)this.inspected();}else if(!this.held){if(this.state==='epilogue'){this.freeYaw-=dx*.003;this.freePitch=clamp(this.freePitch-dy*.002,-.65,.65);return;}this.lookX=clamp(this.lookX-dx*.003,-.62,.62);this.lookY=clamp(this.lookY+dy*.002,-.22,.22);}}
 const id=this.hit(x,y);this.hover=this.actionable(id)?id:null;$('#world').style.cursor=this.hover?(this.drag?'grabbing':'grab'):'default';}
 pointerUp(x,y){if(this.paused){this.drag=null;return;}if(['holdingSell','holdingBuy'].includes(this.state)&&this.hit(x,y)==='slot')this.deliver();this.drag=null;}
 keyDown(e){if(this.state==='epilogue'&&['KeyW','KeyA','KeyS','KeyD'].includes(e.code)){e.preventDefault();this.keys.add(e.code);return;}if(e.code==='Space'&&this.state==='book'){e.preventDefault();this.putBook();return;}if(e.code==='Escape'){this.onExit?.();return;}if(e.code==='KeyP'){e.preventDefault();this.setPaused(!this.paused);return;}if(this.paused)return;if(e.code==='KeyE'||e.code==='Space'){e.preventDefault();this.keyHeld=true;if(e.repeat)return;this.initAudio();if(['holdingSell','holdingBuy'].includes(this.state))this.deliver();else if(this.state==='tape'){}else if(['inspectSell','inspectBuy'].includes(this.state)){}else if(this.state==='book')this.showBook((this.page+1)%4);else{const id={order:'sell',receipt:'receipt1',buy:'buy',receiptBuy:'receipt2',epilogue:'book'}[this.state];if(id)this.activateById(id);}}
 if(e.code==='KeyR'&&this.state==='epilogue'){this.dispose();this.open();}}
 activateById(id){if(id==='sell'){this.pick(this.sellCard);this.setState('holdingSell');}if(id==='buy'){this.pick(this.buyCard);this.setState('holdingBuy');}if(id==='receipt1'){this.pick(this.receipt);this.flip=0;this.setState('inspectSell');}if(id==='receipt2'){this.pick(this.receipt2);this.flip=0;this.setState('inspectBuy');}if(id==='book'){this.pick(this.book);this.setState('book');this.showBook(0);}}
 pick(obj){this.scene.attach(obj);this.held=obj;this.heldStart=obj.position.clone();this.pickTime=this.time;this.hand.visible=true;this.tick(170,.08,.08);}
 release(){if(this.held){this.held.visible=false;this.held=null;}this.hand.visible=false;}
 deliver(){if(!this.held)return;this.deliverObject=this.held;this.deliverStart=this.held.position.clone();this.held=null;this.hand.visible=false;this.setState(this.state==='holdingSell'?'dispatch':'buyDispatch');this.tick(105,.12,.1);}
 inspected(){if(this.state==='inspectSell')this.setState('sellRevelation');else if(this.state==='inspectBuy')this.setState('ending');this.tick(95,.12,.07);}
 setState(name){this.state=name;if($('#filmHud').dataset)$('#filmHud').dataset.state=name;this.time=0;this.lookX=0;this.lookY=0;if(!['holdingSell','holdingBuy','inspectSell','inspectBuy'].includes(name))this.drag=null;$('#filmHint').textContent=this.hint();if(name==='receipt'){this.receipt.visible=true;}if(name==='buy'){this.release();this.buyCard.visible=true;}if(name==='receiptBuy'){this.receipt2.visible=true;}if(name==='epilogue'){this.release();this.setBoard(['五月九日','收盘以后']);}this.cameraPath=null;}
 hint(){return ({order:'拿起桌上的卖单 · 鼠标或 E',holdingSell:'把手里的订单送到柜台铜盘 · 拖过去，或按 E',tape:'握住行情机伸出的纸带，向自己拉 · 也可按住 E',receipt:'柜台送来回报单。拿起它。',inspectSell:'手里这张纸还有另一面 · 拖动翻转，或按 E',buy:'桌上出现了新的指令。拿起它。',holdingBuy:'把回补与买入指令送到柜台铜盘',receiptBuy:'第二张回报到了。拿起来。',inspectBuy:'翻到另一面，看看这一天留下什么',epilogue:'桌上账册可以翻阅；拖动环顾，WASD 走动。门可以离开。R 重走这一天。',book:'点击账册翻页 · 或按 E。点桌面或空格放回。'})[this.state]||'';}
 putBook(){this.held=null;this.hand.visible=false;this.book.position.set(-.8,1.07,.55);this.book.rotation.set(0,.12,0);this.book.scale.setScalar(1);this.setState('epilogue');}
 showBook(p){this.page=p;const pages=[['原书第三章 · 转述','清晨，近五万美元现金。','他先按市价卖出股票。','纸带严重落后于交易所。'],['一百与八十','原书用这两个数解释偏差。','不是某只股票的逐笔复原。','卖出已发生在计划买入的低位。'],['回补，再转为买入','新指令成交又比预想高十五点。','原书叙述一天损失三十五点。','判断方向不能消除执行偏差。'],['小说化叙述者：拉里','依据 Edwin Lefèvre，1923','第三章 / morning of May ninth','场景、动作与旁白为原创改编。']];const old=this.bookPage.material.map;this.bookPage.material.map=this.print(pages[p],{title:'REMINISCENCES · III'});if(old){old.dispose();this.textures=this.textures.filter(t=>t!==old);}this.tick(220,.055,.035);}
 initAudio(){if(this.audio){if(this.sounds)this.audio.resume();return;}if(!this.sounds||typeof window==='undefined')return;try{this.audio=new(window.AudioContext||window.webkitAudioContext)();const count=this.audio.sampleRate*2,buffer=this.audio.createBuffer(1,count,this.audio.sampleRate),data=buffer.getChannelData(0);let prev=0;for(let i=0;i<count;i++){prev=(prev+Math.random()*.08-.04)*.98;data[i]=prev;}this.noise=this.audio.createBufferSource();this.noise.buffer=buffer;this.noise.loop=true;const filter=this.audio.createBiquadFilter();filter.type='lowpass';filter.frequency.value=400;this.ambient=this.audio.createGain();this.ambient.gain.value=.035;this.noise.connect(filter).connect(this.ambient).connect(this.audio.destination);this.noise.start();this.audio.resume();}catch{}}
 tick(freq=210,duration=.025,volume=.015){if(!this.audio||!this.sounds||this.paused)return;const o=this.audio.createOscillator(),gain=this.audio.createGain();o.type='triangle';o.frequency.setValueAtTime(freq,this.audio.currentTime);o.frequency.exponentialRampToValueAtTime(freq*.45,this.audio.currentTime+duration);gain.gain.setValueAtTime(volume,this.audio.currentTime);gain.gain.exponentialRampToValueAtTime(.0001,this.audio.currentTime+duration);o.connect(gain).connect(this.audio.destination);o.start();o.stop(this.audio.currentTime+duration);}
 narration(){let text='',s=this.state,t=this.time;if(FILM_SCRIPT[s]){const len={entrance:8,dispatch:9,falling:15,buyDispatch:9,recovery:15,ending:15}[s];const a=FILM_SCRIPT[s];text=a[Math.min(a.length-1,Math.floor(t/(len/a.length)))];}else text=({order:'纸上的计划看起来很清楚：先卖出，再在下跌后买回来。',tape:'我仍然相信纸带。它的数字，曾经让我一次次挣到钱。',receipt:'我的第一批卖单，终于有了回报。',inspectSell:'“一百”还在纸带上。回报却写着“八十”。',sellRevelation:'我卖空的位置，已经是我原本计划买入的低位。',buy:'我立即改变方向：回补，并转为买入。',receiptBuy:'另一张迟到的纸，从柜台递到了桌上。',inspectBuy:'当指令真正成交时，买入又比预想的高了十五点。',epilogue:'我看对了那一天的市场。却还没学会看清自己所处的时间。',book:''})[s]||'';if(text!==this.caption){this.caption=text;$('#filmCaption').textContent=text;}}
 update(dt){if(!this.active)return;this.resize();if(!this.paused&&dt>0){this.time+=dt;this.elapsed+=dt;this.updateState(dt);this.updateScene(dt);this.narration();}this.render();}
 keyUp(e){this.keys?.delete(e.code);if(e.code==='KeyE'||e.code==='Space')this.keyHeld=false;}
 updateState(dt=1/60){if(this.keyHeld&&this.state==='tape'){this.pull=Math.min(1,this.pull+dt*.6);if(this.pull>.94)this.setState('falling');}if(this.keyHeld&&['inspectSell','inspectBuy'].includes(this.state)){this.flip=Math.min(1,this.flip+dt*.65);if(this.flip>.94)this.inspected();}const s=this.state,t=this.time;const durations={entrance:8,dispatch:9,falling:15,sellRevelation:6,buyDispatch:9,recovery:15,ending:15};const next={entrance:'order',dispatch:'tape',falling:'receipt',sellRevelation:'buy',buyDispatch:'recovery',recovery:'receiptBuy',ending:'epilogue'};if(durations[s]&&t>=durations[s])this.setState(next[s]);}
 cameraPose(){const s=this.state,t=this.time;let pos=[0,1.6,3.4],look=[.15,1.1,.1];if(s==='entrance'){const v=ease(t/8);pos=[lerp(0,-.15,v),1.64,lerp(6.8,2.4,v)];look=[.12,lerp(1.5,1.13,v),.25];this.door.rotation.y=lerp(-.15,-1.5,ease(t/2));}if(['order','holdingSell','buy','holdingBuy'].includes(s)){pos=[-.08,1.62,2.4];look=[.12,1.07,.15];}if(['dispatch','buyDispatch'].includes(s)){const v=ease(t/7);pos=[lerp(-.08,.55,v),1.65,lerp(2.4,.2,v)];look=[.35,1.45,-3.2];}if(s==='tape'){pos=[1.0,1.55,1.8];look=[1.15,1.07,.35];}if(s==='falling'){const v=ease(t/15);pos=[lerp(1,-1.25,v),lerp(1.55,1.72,v),lerp(1.8,2.2,v)];look=[lerp(1.15,-2.4,v),lerp(1.07,2.05,v),lerp(.35,-2,v)];}if(['receipt','receiptBuy'].includes(s)){pos=[.12,1.5,1.65];look=[.55,1.07,.55];}if(['inspectSell','inspectBuy','sellRevelation','book'].includes(s)){pos=[.12,1.62,2.25];look=[.2,1.36,.3];}if(s==='recovery'){const v=ease(t/15);pos=[lerp(.55,-.3,v),1.7,lerp(.2,2.6,v)];look=[lerp(.3,-3.8,v),lerp(1.45,2.3,v),-2.4];}if(s==='ending'){const v=ease(t/15);pos=[.12,1.62,lerp(2.25,4.7,v)];look=[.18,1.18,.2];}if(s==='epilogue'){pos=this.freePos.toArray();look=[pos[0]+Math.sin(this.freeYaw)*Math.cos(this.freePitch)*3,pos[1]+Math.sin(this.freePitch)*3,pos[2]-Math.cos(this.freeYaw)*Math.cos(this.freePitch)*3];}this.desiredPosition.set(...pos);this.desiredLook.set(...look);this.desiredLook.x+=this.lookX*1.8;this.desiredLook.y+=this.lookY;}
 updateScene(dt){if(this.state==='epilogue'){const z=(this.keys.has('KeyS')?1:0)-(this.keys.has('KeyW')?1:0),x=(this.keys.has('KeyD')?1:0)-(this.keys.has('KeyA')?1:0);const speed=dt*1.7/(Math.hypot(x,z)||1);const nx=clamp(this.freePos.x+(x*Math.cos(this.freeYaw)-z*Math.sin(this.freeYaw))*speed,-5.2,5.2),nz=clamp(this.freePos.z+(x*Math.sin(this.freeYaw)+z*Math.cos(this.freeYaw))*speed,-2.2,5.2);if(!(Math.abs(nx)<1.65&&this.freePos.z>-.55&&this.freePos.z<1.05))this.freePos.x=nx;if(!(Math.abs(this.freePos.x)<1.65&&nz>-.55&&nz<1.05))this.freePos.z=nz;}const s=this.state,t=this.time,panic=['falling','receipt','inspectSell','sellRevelation','buy','holdingBuy','buyDispatch','recovery','receiptBuy','inspectBuy','ending'].includes(s);this.cameraPose();const blend=1-Math.exp(-dt*3.4);this.cameraPosition.lerp(this.desiredPosition,blend);this.cameraLook.lerp(this.desiredLook,blend);this.camera.position.copy(this.cameraPosition);this.camera.lookAt(this.cameraLook);this.wheel.rotation.z+=dt*(panic?11:3.5);this.clockLong.rotation.z=-this.elapsed*.025;this.clockShort.rotation.z=-this.elapsed*.003;
 const positions=this.tapeGeometry.attributes.position;for(let i=0;i<positions.count;i++){const x=i%2?.06:-.06,row=Math.floor(i/2)/65;const length=1.3+this.pull*.65;positions.setXYZ(i,x+Math.sin(row*Math.PI)*.035,-Math.pow(row,3)*1.3+Math.sin(row*Math.PI*2+this.elapsed*1.5)*.018,row*length); }positions.needsUpdate=true;this.tapeGeometry.computeVertexNormals();this.tapeGeometry.computeBoundingSphere();this.tape.rotation.x=0;this.tapeMaterial.map.offset.y=(this.elapsed*(panic?.018:.008))%1;
 this.paperLoops.forEach((o,i)=>{o.rotation.z+=dt*.03;const growth=panic?clamp(t/15,0,1):0;o.scale.setScalar(1+growth*.45);});
 for(const a of this.actors){const speed=panic?2.8:1.1,phase=this.elapsed*speed+a.seed;const walking=a.seed>=4;a.root.position.x=a.base.x+(walking?Math.sin(phase*.5)*(panic?.75:.35):Math.sin(phase*.4)*.035);a.root.position.y=Math.sin(phase*2)*(walking?.017:.004);a.root.rotation.y=walking?Math.sin(phase*.5)*.5:Math.sin(phase*.2)*.1;a.head.rotation.y=Math.sin(phase*.7)*.15;for(let i=0;i<2;i++){a.legs[i].rotation.x=walking?Math.sin(phase+i*Math.PI)*.28:0;a.arms[i].arm.rotation.x=walking?Math.sin(phase+i*Math.PI)*.25:-.5+Math.sin(phase)*.1;a.arms[i].fore.rotation.x=-.35-Math.sin(phase+i)*.25;}if(a.seed===2&&['dispatch','buyDispatch'].includes(s)){a.arms[0].arm.rotation.x=-ease(t/3)*1.35;a.arms[0].fore.rotation.x=-.65;}}

 if(['falling','recovery'].includes(s)&&t>9){const v=ease((t-9)/5.6),a=this.courier;a.root.position.lerpVectors(a.base,new THREE.Vector3(.95,0,.38),v);a.root.rotation.y=Math.PI;a.arms[0].arm.rotation.x=-.85;a.arms[0].fore.rotation.x=-.7;const card=s==='falling'?this.receipt:this.receipt2;card.visible=true;card.position.set(lerp(2.5,.65,v),lerp(1.28,1.08,ease((t-12.5)/2.2)),lerp(-1.85,.55,v));card.rotation.x=lerp(-.9,0,ease((t-12.5)/2.2));}
 if(['receipt','receiptBuy'].includes(s)){const a=this.courier;a.root.position.lerpVectors(new THREE.Vector3(.95,0,.38),a.base,ease(t/4));a.root.rotation.y=0;}
 if(this.held){const pick= ease((this.time)/.65);const inspecting=['inspectSell','inspectBuy','sellRevelation','ending','book'].includes(s);const heldScale=innerWidth<600?.7:inspecting?1.02:.68;const halfWidth=.85*Math.tan(this.camera.fov*Math.PI/360)*this.camera.aspect;const handX=inspecting?0:Math.min(.34,Math.max(.035,halfWidth-heldScale*.23-.04));const holder=new THREE.Vector3(clamp(handX+this.aim.x*.06,-Math.max(.01,halfWidth-heldScale*.23-.025),Math.max(.01,halfWidth-heldScale*.23-.025)),-.08-this.aim.y*.04,-.85);this.camera.localToWorld(holder);this.held.position.lerp(holder,1-Math.exp(-dt*8));this.held.quaternion.copy(this.camera.quaternion);this.held.rotateX(Math.PI/2);this.held.rotateZ(this.flip*Math.PI);this.held.scale.setScalar(heldScale);this.hand.position.set(handX+(inspecting?.21:.13)+this.aim.x*.04,-.36-this.aim.y*.025,-.81);this.hand.rotation.z=this.flip*.16;this.fingers.forEach(f=>f.rotation.x=-.45);}
 if(this.deliverObject&&['dispatch','buyDispatch'].includes(s)){const v=ease(t/1.9);this.deliverObject.position.lerpVectors(this.deliverStart,new THREE.Vector3(.38,1.4,-2.35),v);this.deliverObject.rotation.x=-v*.08;this.deliverObject.rotation.z=v*.1;if(t>2.3)this.deliverObject.visible=false;}
 const price=s==='falling'?Math.round(lerp(100,80,ease(t/8))):['recovery','receiptBuy','inspectBuy','ending','epilogue','book'].includes(s)?Math.round(lerp(80,95,s==='recovery'?ease(t/9):1)):100;this.setBoard(['交易所 · 此刻',String(price)]);const tapePrice=['recovery','receiptBuy','inspectBuy','ending','epilogue','book'].includes(s)?80:100;if(this.lastTapePrice!==tapePrice){this.lastTapePrice=tapePrice;this.paintTape(tapePrice);}
 this.sun.intensity=lerp(this.sun.intensity,s==='ending'?.65:panic?1.8:3.4,dt*.5);this.lampLight.intensity=lerp(this.lampLight.intensity,panic?4:6,dt);this.dust.rotation.y=this.elapsed*.003;if(this.grade){this.grade.uniforms.time.value=this.elapsed;this.grade.uniforms.fade.value=s==='entrance'?ease(t/1.8):s==='ending'?1-ease((t-9)/6)*.36:1;}
 this.audioTick+=dt;if(this.audioTick>(panic?.13:.38)){this.audioTick=0;this.tick(panic?320:230,.025,.012);}
 for(const obj of [this.sellCard,this.buyCard,this.receipt,this.receipt2]){const hovered=this.hover===obj.userData.id;obj.traverse(o=>{if(o.material?.emissiveMap)o.material.emissiveIntensity=hovered?.26:.14;});}
 const hint=this.hint();if($('#filmHint').textContent!==hint)$('#filmHint').textContent=hint;
 }
 render(){if(this.renderer.isWebGLRenderer){this.fpsFrames++;const now=performance.now();if(now-this.fpsStart>1500){$('#filmHud').dataset.fps=String(Math.round(this.fpsFrames*1000/(now-this.fpsStart)));this.fpsStart=now;this.fpsFrames=0;}}if(this.composer)this.composer.render();else this.renderer.render(this.scene,this.camera);}
 dispose(){if(this.composer){for(const p of this.composer.passes)p.dispose?.();this.composer.dispose();this.composer=null;}this.sun?.shadow.dispose();if(this.scene){this.scene.traverse(o=>o.geometry?.dispose());this.scene=null;}for(const m of this.materials)m.dispose();for(const t of this.textures)t.dispose();this.materials=[];this.textures=[];if(this.savedPixelRatio)this.renderer.setPixelRatio(this.savedPixelRatio);if(this.renderer.shadowMap)this.renderer.shadowMap.enabled=this.savedShadow??false;}
}
