import * as THREE from 'three';
import {touchDevice,pixelBudget} from './render-budget.js';
import {paginate} from './novel-scores.js';
import {EffectComposer} from 'three/addons/postprocessing/EffectComposer.js';
import {RenderPass} from 'three/addons/postprocessing/RenderPass.js';
import {UnrealBloomPass} from 'three/addons/postprocessing/UnrealBloomPass.js';
import {ShaderPass} from 'three/addons/postprocessing/ShaderPass.js';
import {mergeGeometries} from 'three/addons/utils/BufferGeometryUtils.js';
import {OutputPass} from 'three/addons/postprocessing/OutputPass.js';
const $=s=>document.querySelector(s),clamp=THREE.MathUtils.clamp,lerp=THREE.MathUtils.lerp;
const ease=t=>{t=clamp(t,0,1);return t*t*(3-2*t)};
const COLORS={wood:0x3b2419,green:0x183b31,brass:0xbe9251,paper:0xe4d4ad,ink:0x172720};
const filmShader={uniforms:{tDiffuse:{value:null},time:{value:0},fade:{value:1}},vertexShader:'varying vec2 vUv; void main(){vUv=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:'uniform sampler2D tDiffuse;uniform float time;uniform float fade;varying vec2 vUv;void main(){vec3 c=texture2D(tDiffuse,vUv).rgb;vec2 p=vUv*2.-1.;float vignette=1.-.28*dot(p,p);float noise=fract(sin(dot(vUv+time*.0001,vec2(12.9898,78.233)))*43758.5453)-.5;c*=vignette;c+=noise*.012;c=mix(c,vec3(dot(c,vec3(.299,.587,.114))),.07);gl_FragColor=vec4(c*fade,1.);}'};
export const FILM_DURATIONS={entrance:38,dispatch:24,falling:32,sellRevelation:18,buyDispatch:18,recovery:26,ending:38};
export const FILM_SCRIPT={
 entrance:['纽约。五月九日。昨天收盘后，整个世界都知道，一场金融巨头之间的争夺已经开始。','哈里曼与摩根的阵营，为北太平洋铁路的控制权迎面相撞。双方抢购，把这只股票逼进了轧空。','我却已把手中的一千股北太平洋普通股卖掉：约一百一十出手，赚了三十点。账户上留下近五万美元。','几个月前，我在这间经纪行里输光过一次。如今，这是我积累过的最大一笔钱。没有股票，只有现金。','我早就觉得许多股票涨到了买盘枯竭的地步。这一次，总该轮到下跌了：先卖空，再捡便宜货，反弹时两头获利。'],
 dispatch:['我送出了一批市价卖单。我要抓住市场的下跌，不想把自己锁在一个指定价格上。','开盘报价让我吃了一惊。跌势比想象中还猛烈；成交量极大，价格波动的幅度前所未见。','经纪人一直在忙。他们有能力，也尽责。问题是，这个办公室、场内经纪人和行情纸带，都被汹涌的交易挤在后面。'],
 falling:['我眼睛盯着的，仍是行情机印出来的数字。交易所里的价格，却已经先走了一大段。','假如纸带上报的是一百，我据此发出卖单；等订单在场内执行，成交却已经到了八十。','多跌了二十点。若从昨晚收盘算起，跌幅已经达到三十、四十点。回报还在路上，纸带也没有赶上。','我猜中了急跌，却没有卖在自己看见的位置。此刻卖出的这些股票，恰好已是我本来打算买入的便宜货。'],
 sellRevelation:['一百是我作决定时看到的报价。八十是我的卖单真正成交的位置。两个数字，属于两个不同的时刻。','市场总不至于一路跌穿地面。我立刻改主意：回补空头，再转为买入。反弹还可以把局面救回来。'],
 buyDispatch:['回补，再买入。我送出新的市价指令，想抓住眼前的低位。','可指令仍要穿过同一条拥堵的路：办公室、交易所、场内经纪人。它不会因为我改变方向，就突然赶上市场。'],
 recovery:['市场确实反弹了。一切大方向，都像我事先料想的一样。','经纪人为我买了股票。成交价却由场内经纪人接到订单时的市场决定，而不是由我改主意时看到的报价决定。','这一次，买入价平均比我的预计高了十五点。卖单迟到，买单也迟到；我追赶的始终是已经过去的行情。'],
 ending:['二十点，再加十五点。一天损失三十五点，超过了我能承受的限度。近五万美元本金，全没有了。','我一直把行情纸带当作最好的朋友。过去，我根据它告诉我的数字下注，也确实靠它挣过钱。','这一次，印出来的价格和实际成交的价格相差太远。害我的仍是以前那个问题，只是被这场恐慌放大到了极点。','后来回想，单会读纸带显然不够。我当时却连自己的问题都说不清，更没有看见解决的方法。','我甚至继续进进出出，仍不顾执行的差距。偶尔还能挣钱，又让我迟迟没能理解：我要判断的是市场的大变化，而不只是接下来的几个报价。']
};
const FILM_CLUES={
 entrance:[['五月八日 · 收盘以后','争夺已公开'],['北太平洋 · 控制权之争','哈里曼 ↔ 摩根'],['1,000 股 → 兑现','约 110 出手 / 获利 30 点'],['现金近 $50,000','股票：零'],['急跌 → 便宜货 → 反弹','我以为能抓住两头']],
 dispatch:[['判断 → 下单 → 场内执行','三个动作，三个时刻'],['市价指令','成交按抵达市场时的价格'],['成交量巨大','纸带与回报一起落后']],
 falling:[['眼前的报价 ≠ 此刻的成交','我在读过去'],['假如纸带：100','我的卖出：80'],['比判断位置又低 20 点','距昨夜收盘已跌 30—40 点'],['我卖出的低位','正是原先计划买入的位置']],
 sellRevelation:[['纸带 100 / 成交 80','两个不同的时刻'],['卖空 → 回补 → 买入','我立刻改变方向']],
 buyDispatch:[['方向变了','传递订单的路径没有变'],['办公室 → 场内经纪人','低位不会等我的指令']],
 recovery:[['急跌以后，确实反弹','方向判断成立'],['预计买价 → 实际买价','平均又高 15 点'],['卖单迟到 / 买单迟到','同一条拥堵的路']],
 ending:[['20 + 15 = 35 点','一天的损失'],['近 $50,000 → 全部失去','看对方向，仍被击倒'],['纸带上的价格 / 真正成交的价格','我一直混淆了两个时间'],['读懂纸带，还不够','我当时没有看清原因'],['几个报价 / 市场的大变化','我还要几年才能分清']]
};
const LEDGER_PAGES=[
 ['狂热中的市场','那阵子，买进常赚钱，卖空常赔钱。','我觉得上涨总有尽头，但每次看空，','都得赶快认赔退出，免得亏得更多。','北太平洋却仍像要继续上涨。','它与其他股票不同，我没有做空它。'],
 ['五月八日 · 收盘以后','两大阵营争夺北太平洋的控制权。','抢购引发轧空；交易办公室议论纷纷。','我没有做空北太平洋。纸带告诉我，','它与其他股票不同，还可能继续上涨。'],
 ['巨头们的抢购','后来我听说，摩根一方为保住控制权，','曾让基恩买五万股，又增至十五万股。','基恩派埃迪·诺顿进场，买了十万股，','随后又有约五万股的指令。','抢购相继而来，著名的轧空就此发生。'],
 ['我手中的一千股','不顾办公室里众人的劝告，我持有它。','约一百一十时，我兑现三十点利润。','账户积累到近五万美元。','几个月前，我还在这里输光过一次。','这一次，我相信自己已经找回了本领。'],
 ['五月九日 · 开盘以前','许多股票似乎已经涨到买盘枯竭。','我看空了好几天，终于等到了机会。','急跌，会制造便宜货；随后迅速反弹。','先卖空，再买入：两边都能挣钱。','我把一个判断，当成了稳得不能再稳的机会。'],
 ['市价卖单 · 在途','开盘暴跌，成交量巨大，波动空前。','经纪人有能力，也尽责，但订单太多。','行情纸带落后，成交回报也来得很慢。','我看见一百时发出的卖单，成交在八十。','从昨夜收盘算，已经跌了三十、四十点。'],
 ['卖在了想买的位置','成交比我据纸带判断的低了二十点。','我本想卖在跌势前段，却卖在了低位。','那些股票已是我计划买入的便宜货。','市场总有止跌的时候。','我立刻决定：回补空头，并转为买入。'],
 ['回补与买入 · 在途','我改变了方向，传递订单却仍需时间。','场内经纪人按收到指令时的行情买入。','平均比我预想的又高了十五点。','一天损失三十五点，我被彻底击倒。','看对下跌和反弹，依然可以输光本金。'],
 ['纸带上的朋友','过去我根据它的数字下注，靠它挣钱。','那天，它印着过去，市场却已经到了现在。','单会读纸带不够；执行过程也属于交易。','这个问题以前已击败过我。','我当时连问题本身都没能看清。'],
 ['不寻常的那一天','如果意外永不发生，交易就只剩加减。','我却把判断正确，等同于必然能获利。','我没想到，自己猜中的大跌与反弹，','会在订单真正成交时变成两次损失。','市场按预测走，我的账户却走向了相反的结局。'],
 ['我没有立即学会','我还在反复交易，仍忽略执行差距。','试用限价时，市场又常常离我而去。','我想判断市场，而非守住一个指定价。','几年以后才懂得：盯着随后几个报价，','与提前判断市场的大变化，是两件事。']
];
export class TickerFilm {
 constructor(renderer,{onExit}={}){this.renderer=renderer;this.onExit=onExit;this.active=false;this.paused=false;this.time=0;this.elapsed=0;this.ray=new THREE.Raycaster();this.pointer=new THREE.Vector2(0,0);this.aim=new THREE.Vector2(0,0);this.targets=[];this.actors=[];this.materials=[];this.textures=[];this.motions=[];this.sounds=true;this.lightweight=touchDevice();this.reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;this.camera=new THREE.PerspectiveCamera(54,innerWidth/innerHeight,.06,70);this.cameraPosition=new THREE.Vector3();this.cameraLook=new THREE.Vector3();this.desiredPosition=new THREE.Vector3();this.desiredLook=new THREE.Vector3();
 this.bindControls();}
 bindControls(){$('#filmExit').onclick=()=>this.onExit?.();$('#filmPause').onclick=()=>this.setPaused(!this.paused);for(const [id,command] of [['#bookBack','back'],['#bookForward','forward'],['#bookLanguage','language'],['#bookPutDown','close']])$(id).onclick=()=>this.bookCommand(command);$('#filmAudio').onclick=()=>{if(this.sounds&&this.audio?.state==='running'){this.sounds=false;this.setAudioLevel();this.audioStatus();}else{this.sounds=true;this.initAudio();}};}
 open(){this.lightweight=touchDevice();this.bindControls();this.active=true;this.paused=false;this.time=0;this.elapsed=0;this.pull=0;this.flip=0;this.displayFlip=0;this.aim.set(0,0);this.lookX=0;this.lookY=0;this.drag=null;this.keyHeld=false;this.held=null;this.hover=null;this.page=0;this.caption='';this.audioTick=0;this.keys=new Set();this.freeYaw=-.14;this.freePitch=-.2;this.freePos=new THREE.Vector3(-.15,1.6,2.5);this.build();this.state='entrance';if($('#filmHud').dataset)$('#filmHud').dataset.state='entrance';this.cameraPosition.set(0,1.65,6.8);this.cameraLook.set(0,1.4,-.7);this.camera.position.copy(this.cameraPosition);this.camera.lookAt(this.cameraLook);$('#filmHud').hidden=false;document.body.classList.add('in-film');$('#filmPause').textContent='暂停';$('#filmTitle').textContent='1901年5月9日';$('#filmHint').textContent='';$('#filmThought').textContent='';$('#filmFact').textContent='';$('#world').setAttribute('aria-label','1901年5月9日连续三维样片：直接操作桌上的订单、行情机纸带与成交回报');this.resize();this.initAudio();this.audioStatus();this.manuscriptLanguage='zh';this.manuscriptPages=[];const request=this.manuscriptRequest=(this.manuscriptRequest||0)+1;if(typeof window!=='undefined'&&!this.work)fetch((import.meta.env?.BASE_URL||'./')+'manuscripts/03.json').then(r=>{if(!r.ok)throw Error();return r.json()}).then(data=>{if(this.active&&request===this.manuscriptRequest){this.manuscriptPages=paginate(data.paragraphs,true);if(this.state==='book'&&this.manuscriptLanguage==='en')this.showBook(0);}}).catch(()=>{});}
 close(){this.manuscriptRequest=(this.manuscriptRequest||0)+1;this.active=false;this.paused=false;this.held=null;this.drag=null;$('#filmHud').hidden=true;$('#sceneFade').style.opacity='0';document.body.classList.remove('in-film');document.body.classList.remove('film-walking');$('#bookTools').hidden=true;$('#world').setAttribute('aria-label','可自由探索的三维记忆宫殿');this.dispose();if(this.audio)this.audio.suspend();}
 setPaused(v){this.paused=v;this.setAudioLevel();this.drag=null;this.keyHeld=false;this.keys?.clear();$('#filmPause').textContent=v?'继续':'暂停';$('#filmPause').setAttribute('aria-pressed',String(v));$('#filmHint').textContent=v?'时间停下了。继续，或按 Esc 返回房子。':this.hint();}
 mat(color,extra={}){const key=color+'|'+JSON.stringify({...extra,map:extra.map?.uuid});if(this.matCache?.has(key))return this.matCache.get(key);const m=new THREE.MeshStandardMaterial({color,roughness:.58,...extra});this.materials.push(m);this.matCache?.set(key,m);return m;}
 box(g,w,h,d,x,y,z,m){const o=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),typeof m==='number'?this.mat(m):m);o.position.set(x,y,z);o.castShadow=true;o.receiveShadow=true;g.add(o);return o;}
 cylinder(g,r,h,x,y,z,m,segments=32){const o=new THREE.Mesh(new THREE.CylinderGeometry(r,r,h,segments),typeof m==='number'?this.mat(m):m);o.position.set(x,y,z);o.castShadow=true;o.receiveShadow=true;g.add(o);return o;}
 sphere(g,r,x,y,z,m){const o=new THREE.Mesh(new THREE.SphereGeometry(r,24,16),typeof m==='number'?this.mat(m):m);o.position.set(x,y,z);o.castShadow=true;g.add(o);return o;}
 canvasTexture(draw,w=1024,h=768){const canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;draw(canvas.getContext('2d'),w,h);const texture=new THREE.CanvasTexture(canvas);texture.colorSpace=THREE.SRGBColorSpace;this.textures.push(texture);return texture;}
 print(lines,{w=1024,h=768,dark=false,title='HARDING BROTHERS',footer='NEW YORK · 1901'}={}){return this.canvasTexture((c,w,h)=>{c.fillStyle=dark?'#16342c':'#e5d6b4';c.fillRect(0,0,w,h);c.strokeStyle=dark?'#ad925c':'#8f7b53';c.lineWidth=3;c.strokeRect(38,35,w-76,h-70);c.fillStyle=dark?'#e7d6ae':'#263b32';c.textAlign='center';c.font='30px Georgia';c.fillText(title,w/2,88);c.fillRect(90,112,w-180,2);c.font='48px Microsoft YaHei,serif';lines.forEach((line,i)=>c.fillText(line,w/2,195+i*76,w-150));c.font='22px Georgia';c.fillText(footer,w/2,h-68);},w,h);}
 placard(g,lines,w,h,x,y,z,dark=false){const tex=this.print(lines,{dark,h:Math.round(1024*h/w)});const m=new THREE.MeshBasicMaterial({map:tex});this.materials.push(m);const o=new THREE.Mesh(new THREE.PlaneGeometry(w,h),m);o.position.set(x,y,z);g.add(o);return o;}
 card(front,back){const g=new THREE.Group();const edge=this.box(g,.46,.005,.65,0,0,0,COLORS.paper);const f=new THREE.Mesh(new THREE.PlaneGeometry(.46,.65),new THREE.MeshStandardMaterial({map:this.print(front,{h:1447}),roughness:.95}));f.rotation.x=-Math.PI/2;f.position.y=.004;g.add(f);f.material.emissive.setHex(0xffffff);f.material.emissiveMap=f.material.map;f.material.emissiveIntensity=.14;const b=new THREE.Mesh(new THREE.PlaneGeometry(.46,.65),new THREE.MeshStandardMaterial({map:this.print(back,{h:1447}),roughness:.95}));b.rotation.x=Math.PI/2;b.rotation.z=Math.PI;b.position.y=-.004;g.add(b);b.material.emissive.setHex(0xffffff);b.material.emissiveMap=b.material.map;b.material.emissiveIntensity=.14;this.materials.push(f.material,b.material);g.userData.edge=edge;g.userData.front=f;g.userData.back=b;return g;}
 target(g,id){g.traverse(o=>o.userData.filmTarget=id);this.targets.push(g);g.userData.id=id;return g;}
 woodTexture(){return this.canvasTexture((c,w,h)=>{c.fillStyle='#523724';c.fillRect(0,0,w,h);for(let j=0;j<850;j++){const y=j*h/850;c.strokeStyle=j%4?'#20140a22':'#e6a56015';c.lineWidth=.5+j%3;c.beginPath();c.moveTo(0,y);for(let x=0;x<=w;x+=32)c.lineTo(x,y+Math.sin(x*.007+j)*3);c.stroke();}},512,512);}
 build(){this.scene=new THREE.Scene();this.scene.background=new THREE.Color(0x102322);this.scene.fog=new THREE.FogExp2(0x142b28,.026);this.targets=[];this.actors=[];this.materials=[];this.textures=[];this.motions=[];this.matCache=new Map();this.lastTapePrice=null;this.lastWidth=0;
 const g=this.scene,wood=this.mat(0xb8a38a,{map:this.woodTexture()}),brass=this.mat(COLORS.brass,{metalness:.72,roughness:.28}),dark=this.mat(COLORS.green),paper=this.mat(COLORS.paper);this.brass=brass;this.wood=wood;
 this.scene.add(new THREE.HemisphereLight(0xa7c7d0,0x342115,1.05));this.sun=new THREE.DirectionalLight(0xffd6a0,3.4);this.sun.position.set(-4,7,-12);this.sun.castShadow=!this.lightweight;this.sun.shadow.mapSize.set(512,512);this.sun.shadow.camera.left=-9;this.sun.shadow.camera.right=9;this.sun.shadow.camera.top=9;this.sun.shadow.camera.bottom=-9;this.sun.shadow.normalBias=.03;g.add(this.sun);
 this.lampLight=new THREE.PointLight(0xffb45b,6,8,2);this.lampLight.position.set(-.8,1.9,.1);g.add(this.lampLight);const cold=new THREE.PointLight(0x7ea9bc,30,12,2);cold.position.set(3,3,-4);g.add(cold);
 for(let z=-7;z<7;z+=.42)this.box(g,12,.1,.4,0,-.06,z,wood);this.box(g,12,1.65,.25,0,.8,-7,dark);this.box(g,12,.65,.25,0,4.7,-7,dark);for(const x of[-5.8,-1.9,1.9,5.8])this.box(g,.65,3.2,.25,x,3,-7,dark);this.box(g,.25,5,14,6,2.45,0,dark);this.box(g,.25,5,14,-6,2.45,0,dark);this.box(g,12,.2,14,0,5,0,0x273c35);
 for(const x of[-5.9,5.9]){this.box(g,.08,1.2,14,x,.6,0,wood);for(let z=-6;z<=6;z+=1.4)this.box(g,.09,1.15,.035,x,.62,z,brass);}for(let x=-5;x<6;x+=1.5)this.box(g,.08,1.2,.06,x,.6,-6.82,brass);this.box(g,11.7,.07,.06,0,1.25,-6.8,brass);
 // Windows are actual geometry, with parallax outside rather than a background picture.
 for(let k=0;k<3;k++){const x=-3.8+k*3.8;const pane=this.box(g,2.4,2.35,.11,x,3,-6.66,this.mat(0x8aaeb1,{transparent:true,opacity:.14,roughness:.05}));pane.castShadow=false;for(const dx of[-1.3,0,1.3])this.box(g,.065,2.7,.16,x+dx,3,-6.58,wood);for(const y of[1.7,3,4.3])this.box(g,2.65,.055,.16,x,y,-6.58,wood);}
 for(let i=0;i<18;i++){const x=(i-8.5)*1.3;const h=2.2+(i*7%9)*.4;this.box(g,1.08,h,.8,x,h/2,-9-i%3,0x4d6663);for(let y=.5;y<h;y+=.55)for(const dx of[-.27,.27])this.box(g,.18,.25,.03,x+dx,y,-8.55-i%3,0xbeb49a);}
 this.door=new THREE.Group();this.door.position.set(-2.5,0,5.5);g.add(this.door);this.box(this.door,1.5,2.9,.15,.75,1.45,0,wood);this.sphere(this.door,.06,1.32,1.35,-.13,brass);this.target(this.door,'door');this.door.rotation.y=-.15;this.nextDoor=new THREE.Group();this.nextDoor.position.set(2.5,0,5.5);g.add(this.nextDoor);this.box(this.nextDoor,1.5,2.9,.15,0,1.45,0,wood);this.placard(this.nextDoor,['走向下一段往事'],1.2,.28,0,1.8,-.09).rotation.y=Math.PI;this.target(this.nextDoor,'nextDoor');
 // An office with counter, work desks and continuously animated people.
 this.box(g,8,1.2,.9,0,.6,-3,wood);this.box(g,8.25,.12,1.08,0,1.22,-3,wood);for(let x=-3.5;x<4;x+=.7)this.box(g,.035,1.1,.035,x,.58,-2.52,brass);
 this.box(g,3,.13,1.4,0,.95,.2,wood);for(const x of[-1.28,1.28])for(const z of[-.32,.72])this.box(g,.09,.9,.09,x,.45,z,wood);this.box(g,1,.012,1.15,.12,1.022,.22,this.mat(0x15372d,{roughness:.95}));
 this.slot=new THREE.Group();this.slot.position.set(.38,1.28,-2.35);g.add(this.slot);this.box(this.slot,1,.1,.65,0,0,0,wood);this.box(this.slot,.86,.012,.5,0,.06,0,brass);this.placard(this.slot,['订单'],.62,.3,0,.23,-.12);this.target(this.slot,'slot');
 const lamp=new THREE.Group();lamp.position.set(-.8,1.02,.05);g.add(lamp);this.cylinder(lamp,.18,.055,0,0,0,brass);this.cylinder(lamp,.03,.68,0,.36,0,brass);const shade=new THREE.Mesh(new THREE.ConeGeometry(.3,.25,32,1,true),this.mat(0x285546,{side:THREE.DoubleSide}));shade.rotation.x=Math.PI;shade.position.set(0,.71,0);lamp.add(shade);
 this.sellCard=this.card(['市价卖出','不限定成交价格','先抓住下跌'],['五月九日 · 上午','现金近五万美元','手中没有股票']);this.sellCard.position.set(.12,1.072,.3);this.sellCard.rotation.y=-.16;g.add(this.sellCard);this.target(this.sellCard,'sell');
 this.buyCard=this.card(['回补空头','随后转为买入','市价指令'],['我以为八十附近','已是可以买入的低位','市场不会一直下跌']);this.buyCard.position.set(.12,1.08,.3);this.buyCard.visible=false;g.add(this.buyCard);this.target(this.buyCard,'buy');
 this.receipt=this.card(['卖出成交回报','实际卖出：八十','市价指令 · 已执行'],['我看见的报价：一百','我的卖出成交：八十','相差二十点','卖在了原本想买的低位']);this.receipt.position.set(.65,1.07,.55);this.receipt.visible=false;g.add(this.receipt);this.target(this.receipt,'receipt1');
 this.receipt2=this.card(['买入成交回报','成交比预期高','平均十五点'],['卖出低了二十点','买入又高了十五点','一天损失三十五点','近五万美元 · 全部失去']);this.receipt2.position.set(.4,1.08,.55);this.receipt2.visible=false;g.add(this.receipt2);this.target(this.receipt2,'receipt2');
 this.book=new THREE.Group();this.book.position.set(-.8,1.07,.55);this.book.rotation.y=.12;g.add(this.book);this.box(this.book,.5,.035,.65,0,0,0,dark);this.bookPage=this.placard(this.book,['五月九日','拉里 · 利文斯顿'],.46,.62,0,.023,0);this.bookPage.rotation.x=-Math.PI/2;this.target(this.book,'book');
 this.buildTicker(paper,brass);this.buildBoard();this.buildClock();
 for(let i=0;i<5;i++)this.actors.push(this.person(i-2,0,-4.2,i));this.actors.push(this.person(-4.3,0,1.6,5));this.actors.push(this.person(4.5,0,-.2,6));this.courier=this.person(2.65,0,-2.15,7);this.actors.push(this.courier);
 this.hand=this.buildHand();this.camera.add(this.hand);this.scene.add(this.camera);
 const particles=new THREE.BufferGeometry(),arr=[];for(let i=0;i<160;i++)arr.push((i*37%100)/10-5,(i*17%100)/22,(i*29%100)/8-6);particles.setAttribute('position',new THREE.Float32BufferAttribute(arr,3));this.dust=new THREE.Points(particles,new THREE.PointsMaterial({color:0xf4d099,size:.014,transparent:true,opacity:.22,depthWrite:false}));g.add(this.dust);
 this.mergeArchitecture();if(this.renderer.isWebGLRenderer){this.fpsStart=performance.now();this.fpsFrames=0;this.savedPixelRatio=this.renderer.getPixelRatio();this.renderer.setPixelRatio(pixelBudget(innerWidth,innerHeight,this.lightweight));this.savedShadow=this.renderer.shadowMap.enabled;this.renderer.shadowMap.enabled=!this.lightweight;if(!this.lightweight){this.composer=new EffectComposer(this.renderer);this.composer.addPass(new RenderPass(g,this.camera));this.bloom=new UnrealBloomPass(new THREE.Vector2(innerWidth,innerHeight),.22,.5,.82);this.composer.addPass(this.bloom);this.grade=new ShaderPass(filmShader);this.composer.addPass(this.grade);this.composer.addPass(new OutputPass());}$('#filmHud').dataset.quality=this.lightweight?'light':'full';}
 }

 mergeArchitecture(){const groups=new Map();for(const o of this.scene.children){if(!o.isMesh||o===this.tape||this.paperLoops.includes(o))continue;const key=o.material.uuid+o.castShadow;if(!groups.has(key))groups.set(key,[]);groups.get(key).push(o);}for(const objects of groups.values()){if(objects.length<2)continue;const geo=objects.map(o=>{o.updateMatrix();return o.geometry.clone().applyMatrix4(o.matrix);});const merged=mergeGeometries(geo,false);if(!merged){geo.forEach(g=>g.dispose());continue;}const mesh=new THREE.Mesh(merged,objects[0].material);mesh.castShadow=objects[0].castShadow;mesh.receiveShadow=true;this.scene.add(mesh);for(const o of objects){this.scene.remove(o);o.geometry.dispose();}geo.forEach(g=>g.dispose());}}
 buildTicker(paper,brass){const g=new THREE.Group();g.position.set(1.2,1.02,.05);this.scene.add(g);this.machine=g;this.cylinder(g,.28,.08,0,0,0,brass);this.cylinder(g,.09,.2,0,.12,0,brass);this.cylinder(g,.19,.1,0,.28,0,brass);for(const x of[-.12,.12])this.cylinder(g,.025,.35,x,.29,.02,brass);this.wheel=this.cylinder(g,.14,.08,0,.42,0,brass);this.wheel.rotation.x=Math.PI/2;this.cylinder(g,.012,.25,0,.42,.01,brass).rotation.z=Math.PI/2;const glass=this.sphere(g,.29,0,.32,0,this.mat(0xb8dad0,{transparent:true,opacity:.12,roughness:.08,metalness:.12}));glass.scale.y=1.1;
 this.tapeCanvas=document.createElement('canvas');this.tapeCanvas.width=256;this.tapeCanvas.height=2048;this.tapeContext=this.tapeCanvas.getContext('2d');this.tapeTexture=new THREE.CanvasTexture(this.tapeCanvas);this.tapeTexture.colorSpace=THREE.SRGBColorSpace;this.tapeTexture.wrapT=THREE.RepeatWrapping;this.textures.push(this.tapeTexture);this.tapeMaterial=new THREE.MeshStandardMaterial({map:this.tapeTexture,side:THREE.DoubleSide,roughness:1});this.materials.push(this.tapeMaterial);
 this.tapeGeometry=new THREE.PlaneGeometry(.12,1.4,1,65);this.tape=new THREE.Mesh(this.tapeGeometry,this.tapeMaterial);this.tape.position.set(1.18,1.44,.05);this.scene.add(this.tape);this.target(this.tape,'tape');this.grip=this.sphere(this.scene,.16,1.18,1.28,.6,this.mat(0xffffff,{transparent:true,opacity:0,depthWrite:false}));this.grip.castShadow=false;this.target(this.grip,'tape');this.paperLoops=[];for(let i=0;i<8;i++){const loop=new THREE.Mesh(new THREE.TorusGeometry(.16+i*.016,.009,8,48,Math.PI*1.8),this.mat(COLORS.paper));loop.position.set(1.02+Math.sin(i)*.15,.12+i*.027,1.1+i*.06);loop.rotation.set(.7+i*.21,i*.19,.4);this.scene.add(loop);this.paperLoops.push(loop);}this.paintTape(100);}
 paintTape(value){const c=this.tapeContext;c.fillStyle='#e8dcbf';c.fillRect(0,0,256,2048);c.fillStyle='#273b31';c.font='30px Georgia';c.textAlign='center';for(let i=0;i<24;i++){c.fillText('N.Y.  '+String(value-i%3),128,75+i*84);c.fillRect(24,98+i*84,208,1);}this.tapeTexture.needsUpdate=true;}
 buildBoard(){this.board=new THREE.Group();this.board.position.set(-4.95,2.3,-2);this.board.rotation.y=Math.PI/2.9;this.scene.add(this.board);this.box(this.board,2.9,1.7,.13,0,0,0,this.wood);this.boardDisplay=this.placard(this.board,['交易所 · 此刻','市场正在开盘'],2.7,1.5,0,0,.09,true);this.boardLast='';}
 setBoard(lines){const key=lines.join('|');if(this.boardLast===key)return;this.boardLast=key;const old=this.boardDisplay.material.map;const tx=this.print(lines,{dark:true,h:570,title:'STOCK EXCHANGE',footer:'NEW YORK · MAY 9'});this.boardDisplay.material.map=tx;if(old){old.dispose();this.textures=this.textures.filter(t=>t!==old);}}
 buildClock(){const g=new THREE.Group();g.position.set(3.7,3.85,-6.45);this.scene.add(g);this.cylinder(g,.42,.12,0,0,0,this.brass).rotation.x=Math.PI/2;this.clockFace=this.placard(g,['Ⅻ','Ⅸ      Ⅲ','Ⅵ'],.76,.76,0,0,.085);this.clockLong=this.box(g,.018,.32,.025,0,.13,.11,0x1e2921);this.clockShort=this.box(g,.025,.21,.025,0,.085,.13,0x1e2921);}
 person(x,y,z,seed){const root=new THREE.Group();root.position.set(x,y,z);this.scene.add(root);const suit=this.mat(seed%2?0x26332f:0x373b35),skin=this.mat(seed%2?0xa88364:0xb69577),shirt=this.mat(0xdccfb1);this.box(root,.43,.62,.24,0,1.12,0,suit);this.box(root,.13,.36,.25,0,1.22,.018,shirt);this.box(root,.055,.3,.026,0,1.2,.155,0x3e261e);const head=this.sphere(root,.13,0,1.62,0,skin);head.scale.set(.84,1.1,.82);this.sphere(root,.13,0,1.69,-.015,this.mat(0x29221d)).scale.set(1,.47,1);this.box(root,.065,.07,.07,0,1.61,.11,skin);for(const dx of[-.045,.045])this.sphere(root,.012,dx,1.65,.106,this.mat(0x302a22));
 const arms=[],legs=[];for(const sign of[-1,1]){const arm=new THREE.Group();arm.position.set(sign*.25,1.36,0);root.add(arm);this.box(arm,.12,.3,.13,0,-.14,0,suit);const fore=new THREE.Group();fore.position.y=-.3;arm.add(fore);this.box(fore,.11,.28,.12,0,-.13,0,suit);this.sphere(fore,.066,0,-.3,0,skin);arms.push({arm,fore});const leg=new THREE.Group();leg.position.set(sign*.115,.8,0);root.add(leg);this.box(leg,.15,.73,.17,0,-.35,0,suit);this.box(leg,.17,.09,.29,0,-.73,.045,0x171f1b);legs.push(leg);}return{root,arms,legs,head,seed,base:new THREE.Vector3(x,y,z)};}
 buildHand(){const hand=new THREE.Group(),skin=this.mat(0xb69472),cuff=this.mat(0xe0d4b8),sleeve=this.mat(0x28382f);this.box(hand,.17,.35,.15,0,-.25,0,sleeve);this.box(hand,.18,.07,.15,0,-.045,0,cuff);this.sphere(hand,.105,0,.04,0,skin).scale.set(.8,1,.45);this.fingers=[];for(let i=0;i<4;i++){const finger=new THREE.Group();finger.position.set(-.06+i*.04,.095,-.015);hand.add(finger);this.cylinder(finger,.017,.09,0,.045,0,skin,12);const tip=this.cylinder(finger,.015,.065,0,.105,.018,skin,12);tip.rotation.x=.5;this.fingers.push(finger);}this.sphere(hand,.035,-.095,.03,.035,skin).scale.y=1.5;hand.position.set(.26,-.5,-.65);hand.visible=false;return hand;}
 resize(){if(this.lastWidth===innerWidth&&this.lastHeight===innerHeight)return;this.lastWidth=innerWidth;this.lastHeight=innerHeight;this.camera.aspect=innerWidth/innerHeight;this.camera.fov=innerWidth<600?65:54;this.camera.updateProjectionMatrix();if(this.renderer.isWebGLRenderer)this.renderer.setPixelRatio(pixelBudget(innerWidth,innerHeight,this.lightweight));if(this.composer)this.composer.setSize(innerWidth,innerHeight);}
 hit(x,y){this.pointer.set(x/innerWidth*2-1,-y/innerHeight*2+1);this.ray.setFromCamera(this.pointer,this.camera);const hits=this.ray.intersectObjects(this.targets,true);return hits.find(h=>{let o=h.object;while(o){if(!o.visible)return false;if(['holdingSell','holdingBuy'].includes(this.state)&&o===this.held)return false;o=o.parent;}return true;})?.object.userData.filmTarget||null;}
 actionable(id){return ({order:['sell'],holdingSell:['slot'],tape:['tape'],receipt:['receipt1'],inspectSell:['receipt1'],buy:['buy'],holdingBuy:['slot'],receiptBuy:['receipt2'],inspectBuy:['receipt2'],epilogue:['book','door','nextDoor'],book:['book','door','nextDoor']})[this.state]?.includes(id);}
 pointerDown(x,y){if(this.paused)return;this.initAudio();const id=this.hit(x,y);this.drag={x,y,lastX:x,lastY:y,id,total:0};if(this.state==='book'&&id==='book'){this.drag.bookGesture=true;return;}if(this.state==='book'&&!id){this.putBook();return;}if(!this.actionable(id))return;
 if(id==='sell'){this.pick(this.sellCard);this.setState('holdingSell');}else if(id==='buy'){this.pick(this.buyCard);this.setState('holdingBuy');}else if(id==='slot'&&this.held){this.deliver();}else if(id==='receipt1'&&this.state==='receipt'){this.pick(this.receipt);this.flip=0;this.setState('inspectSell');}else if(id==='receipt2'&&this.state==='receiptBuy'){this.pick(this.receipt2);this.flip=0;this.setState('inspectBuy');}else if(id==='book'){if(this.state==='epilogue'){this.pick(this.book);this.setState('book');this.showBook(0);}else this.showBook((this.page+1)%this.bookCount());}else if(id==='nextDoor')this.onNext?.();else if(id==='door')this.onExit?.();}
 pointerMove(x,y){this.aim.set(clamp(x/innerWidth*2-1,-1,1),clamp(y/innerHeight*2-1,-1,1));if(this.paused)return;if(this.state==='book'&&this.drag?.bookGesture){this.drag.lastX=x;this.drag.lastY=y;return;}if(this.drag){const dx=x-this.drag.lastX,dy=y-this.drag.lastY;this.drag.total+=Math.hypot(dx,dy);this.drag.lastX=x;this.drag.lastY=y;if(this.state==='tape'&&this.drag.id==='tape'){this.pull=clamp(this.pull+(Math.abs(dy)+Math.abs(dx)*.45)/(innerHeight*.38),0,1);if(this.pull>.94)this.setState('falling');}else if(['inspectSell','inspectBuy'].includes(this.state)){this.flip=clamp(this.flip+(Math.abs(dx)+Math.abs(dy)*.5)/(innerWidth*.42),0,1);if(this.flip>.93)this.inspected();}else if(!this.held){if(this.state==='epilogue'){this.freeYaw-=dx*.003;this.freePitch=clamp(this.freePitch-dy*.002,-.65,.65);return;}this.lookX=clamp(this.lookX-dx*.003,-.62,.62);this.lookY=clamp(this.lookY+dy*.002,-.22,.22);}}
 const id=this.hit(x,y);this.hover=this.actionable(id)?id:null;$('#world').style.cursor=this.hover?(this.drag?'grabbing':'grab'):'default';}
 pointerUp(x,y){if(this.state==='book'&&this.drag?.bookGesture){this.finishBookGesture(x,y);return;}if(this.paused){this.drag=null;return;}if(['holdingSell','holdingBuy'].includes(this.state)&&this.hit(x,y)==='slot')this.deliver();this.drag=null;}
 finishBookGesture(x,y){const d=this.drag;this.drag=null;if(this.paused||!d)return;const dx=x-d.x,dy=y-d.y;if(Math.abs(dx)>45&&Math.abs(dx)>Math.abs(dy)*1.2)this.bookCommand(dx<0?'forward':'back');else if(Math.hypot(dx,dy)<18)this.bookCommand(x<innerWidth/2?'back':'forward');}
 bookCommand(command){if(this.state!=='book'||this.paused)return;this.drag=null;if(command==='close'){this.putBook();return;}if(command==='language'){this.keyDown({code:'KeyL',preventDefault(){}});return;}const count=this.work?(this.language==='en'?this.originalPages.length:this.notePages.length):this.bookCount();this.showBook(clamp(this.page+(command==='back'?-1:1),0,Math.max(0,count-1)));}
 syncTouchControls(){document.body.classList[this.active&&this.state==='epilogue'?'add':'remove']('film-walking');$('#bookTools').hidden=this.state!=='book';if(matchMedia('(any-pointer: coarse)').matches){const hint=$('#filmHint');if(this.paused)hint.textContent='时间停下了。轻点“继续”恢复。';else if(this.state==='book')hint.textContent='轻点左右页，或左右滑动翻页 · 下方可换册、放回';else if(this.state==='epilogue')hint.textContent='拖动环顾 · 左下角走动 · 触碰账册或门';else hint.textContent=hint.textContent.replace(/ · (鼠标或 E|也可按住 E|拖过去，或按 E|拖动物件，或按住 E|拖动翻转，或按 E|拖放或按 E)/g,'').replace(/，或按 E/g,'');}}
 keyDown(e){if(this.state==='epilogue'&&['KeyW','KeyA','KeyS','KeyD'].includes(e.code)){e.preventDefault();this.keys.add(e.code);return;}if(e.code==='KeyL'&&this.state==='book'){e.preventDefault();this.manuscriptLanguage=this.manuscriptLanguage==='en'?'zh':'en';this.showBook(0);return;}if(e.code==='Space'&&this.state==='book'){e.preventDefault();this.putBook();return;}if(e.code==='Escape'){this.onExit?.();return;}if(e.code==='KeyP'){e.preventDefault();this.setPaused(!this.paused);return;}if(this.paused)return;if(e.code==='KeyE'||e.code==='Space'){e.preventDefault();this.keyHeld=true;if(e.repeat)return;this.initAudio();if(['holdingSell','holdingBuy'].includes(this.state))this.deliver();else if(this.state==='tape'){}else if(['inspectSell','inspectBuy'].includes(this.state)){}else if(this.state==='book')this.showBook((this.page+(e.shiftKey?-1:1)+this.bookCount())%this.bookCount());else{const id={order:'sell',receipt:'receipt1',buy:'buy',receiptBuy:'receipt2',epilogue:'book'}[this.state];if(id)this.activateById(id);}}
 if(e.code==='KeyR'&&this.state==='epilogue'){this.dispose();this.open();}}
 activateById(id){if(id==='sell'){this.pick(this.sellCard);this.setState('holdingSell');}if(id==='buy'){this.pick(this.buyCard);this.setState('holdingBuy');}if(id==='receipt1'){this.pick(this.receipt);this.flip=0;this.setState('inspectSell');}if(id==='receipt2'){this.pick(this.receipt2);this.flip=0;this.setState('inspectBuy');}if(id==='book'){this.pick(this.book);this.setState('book');this.showBook(0);}}
 pick(obj){this.flip=0;this.displayFlip=0;this.scene.attach(obj);this.held=obj;this.heldStart=obj.position.clone();this.pickTime=this.time;this.hand.visible=true;this.tick(170,.08,.08);}
 release(){if(this.held){this.held.visible=false;this.held=null;}this.hand.visible=false;}
 deliver(){if(!this.held)return;this.deliverObject=this.held;this.deliverStart=this.held.position.clone();this.held=null;this.hand.visible=false;this.setState(this.state==='holdingSell'?'dispatch':'buyDispatch');this.tick(105,.12,.1);}
 inspected(){this.flip=1;if(this.state==='inspectSell')this.setState('sellRevelation');else if(this.state==='inspectBuy')this.setState('ending');this.tick(95,.12,.07);}
 setState(name){this.state=name;if($('#filmHud').dataset)$('#filmHud').dataset.state=name;this.time=0;this.lookX=0;this.lookY=0;if(!['holdingSell','holdingBuy','inspectSell','inspectBuy'].includes(name))this.drag=null;$('#filmHint').textContent=this.hint();if(name==='receipt'){this.receipt.visible=true;}if(name==='buy'){this.release();this.buyCard.visible=true;}if(name==='receiptBuy'){this.receipt2.visible=true;}if(name==='epilogue'){this.release();this.setBoard(['五月九日','收盘以后']);}this.cameraPath=null;}
 hint(){return ({order:'拿起桌上的卖单 · 鼠标或 E',holdingSell:'把手里的订单送到柜台铜盘 · 拖过去，或按 E',tape:'握住行情机伸出的纸带，向自己拉 · 也可按住 E',receipt:'柜台送来回报单。拿起它。',inspectSell:'手里这张纸还有另一面 · 拖动翻转，或按 E',buy:'桌上出现了新的指令。拿起它。',holdingBuy:'把回补与买入指令送到柜台铜盘',receiptBuy:'第二张回报到了。拿起来。',inspectBuy:'翻到另一面，看看这一天留下什么',epilogue:'桌上账册可以翻阅；拖动环顾，WASD 走动。门可以离开。R 重走这一天。',book:'点击账册翻页 · E 往后 / Shift+E 往前 · L 换册 · 空格放回。'})[this.state]||'';}
 putBook(){this.held=null;this.hand.visible=false;this.book.position.set(-.8,1.07,.55);this.book.rotation.set(0,.12,0);this.book.scale.setScalar(1);this.setState('epilogue');}
 bookCount(){return this.manuscriptLanguage==='en'?Math.max(1,this.manuscriptPages.length):LEDGER_PAGES.length;}
 showBook(p){if(this.manuscriptLanguage==='en'){this.page=THREE.MathUtils.clamp(p,0,this.bookCount()-1);const old=this.bookPage.material.map;this.bookPage.material.map=this.canvasTexture((c,w,h)=>{c.fillStyle='#e5d6b4';c.fillRect(0,0,w,h);c.fillStyle='#25382d';c.textAlign='left';c.font='36px Georgia';(this.manuscriptPages[this.page]||['The other notebook is on its way.']).forEach((line,i)=>c.fillText(line,80,150+i*85,w-160));c.textAlign='center';c.font='24px Georgia';c.fillText((this.page+1)+' / '+this.bookCount(),w/2,h-65);},1024,1447);if(old){old.dispose();this.textures=this.textures.filter(t=>t!==old);}return;}this.page=p;const old=this.bookPage.material.map;this.bookPage.material.map=this.print(LEDGER_PAGES[p],{h:1380,title:'PRIVATE NOTES',footer:'LARRY LIVINGSTON · NEW YORK'});if(old){old.dispose();this.textures=this.textures.filter(t=>t!==old);}this.tick(220,.055,.035);}
 audioStatus(){const running=this.sounds&&this.audio?.state==='running';$('#filmAudio').textContent=running?'音效 开':this.sounds?'开启音效':'音效 关';$('#filmAudio').setAttribute('aria-pressed',String(Boolean(running)));if($('#filmHud').dataset)$('#filmHud').dataset.audioState=this.audio?.state||'not-started';}
 setAudioLevel(){if(this.master&&this.audio)this.master.gain.setTargetAtTime(this.sounds&&!this.paused?1:0,this.audio.currentTime,.08);}
 initAudio(){if(!this.sounds||typeof window==='undefined'){this.audioStatus();return;}try{if(!this.audio){this.audio=new(window.AudioContext||window.webkitAudioContext)();this.master=this.audio.createGain();this.master.gain.value=1;this.master.connect(this.audio.destination);this.audio.onstatechange=()=>this.audioStatus();const count=this.audio.sampleRate*2,buffer=this.audio.createBuffer(1,count,this.audio.sampleRate),data=buffer.getChannelData(0);let prev=0;for(let i=0;i<count;i++){prev=(prev+Math.random()*.5-.25)*.98;data[i]=prev;}this.noise=this.audio.createBufferSource();this.noise.buffer=buffer;this.noise.loop=true;const filter=this.audio.createBiquadFilter();filter.type='lowpass';filter.frequency.value=650;this.ambient=this.audio.createGain();this.ambient.gain.value=.08;this.noise.connect(filter).connect(this.ambient).connect(this.master);this.noise.start();}this.setAudioLevel();Promise.resolve(this.audio.resume()).then(()=>this.audioStatus()).catch(()=>this.audioStatus());this.audioStatus();}catch{this.sounds=false;this.audioStatus();$('#filmAudio').textContent='音效不可用';}}
 tick(freq=210,duration=.035,volume=.045){if(!this.audio||!this.sounds||this.paused||this.audio.state!=='running')return;const o=this.audio.createOscillator(),gain=this.audio.createGain();o.type='triangle';o.frequency.setValueAtTime(freq,this.audio.currentTime);o.frequency.exponentialRampToValueAtTime(freq*.45,this.audio.currentTime+duration);gain.gain.setValueAtTime(volume,this.audio.currentTime);gain.gain.exponentialRampToValueAtTime(.0001,this.audio.currentTime+duration);o.connect(gain).connect(this.master);o.start();o.stop(this.audio.currentTime+duration);o.onended=()=>{o.disconnect();gain.disconnect();};}

 narration(){let text='',s=this.state,t=this.time;if(FILM_SCRIPT[s]){const len=FILM_DURATIONS[s];const a=FILM_SCRIPT[s];text=a[Math.min(a.length-1,Math.floor(t/(len/a.length)))];}else text=({order:'纸上的计划看起来很清楚：先卖出，再在下跌后买回来。',tape:'我仍然相信纸带。它的数字，曾经让我一次次挣到钱。',receipt:'我的第一批卖单，终于有了回报。',inspectSell:'“一百”还在纸带上。回报却写着“八十”。',sellRevelation:'我卖空的位置，已经是我原本计划买入的低位。',buy:'我立即改变方向：回补，并转为买入。',receiptBuy:'另一张迟到的纸，从柜台递到了桌上。',inspectBuy:'当指令真正成交时，买入又比预想的高了十五点。',epilogue:'我看对了那一天的市场。却还没学会看清自己所处的时间。',book:''})[s]||'';if(text!==this.caption){this.caption=text;$('#filmCaption').textContent=text;}}
 updateClues(){const beats=FILM_CLUES[this.state],duration=FILM_DURATIONS[this.state];const thought=$('#filmThought'),fact=$('#filmFact');if(!beats){thought.textContent='';fact.textContent='';return;}const span=duration/beats.length,index=Math.min(beats.length-1,Math.floor(this.time/span)),local=this.time-index*span;const opacity=ease(local/.7)*(1-ease((local-span+.9)/.9));thought.textContent=beats[index][0];fact.textContent=beats[index][1];thought.style.opacity=String(opacity);fact.style.opacity=String(ease((local-.8)/.7)*(1-ease((local-span+.7)/.7)));}
 update(dt){if(!this.active)return;this.resize();if(!this.paused&&dt>0){this.time+=dt;this.elapsed+=dt;this.updateState(dt);this.updateScene(dt);this.narration();this.updateClues();}this.render();}
 keyUp(e){this.keys?.delete(e.code);if(e.code==='KeyE'||e.code==='Space')this.keyHeld=false;}
 updateState(dt=1/60){if(this.keyHeld&&this.state==='tape'){this.pull=Math.min(1,this.pull+dt*.6);if(this.pull>.94)this.setState('falling');}if(this.keyHeld&&['inspectSell','inspectBuy'].includes(this.state)){this.flip=Math.min(1,this.flip+dt*.65);if(this.flip>.94)this.inspected();}const s=this.state,t=this.time;const durations=FILM_DURATIONS;const next={entrance:'order',dispatch:'tape',falling:'receipt',sellRevelation:'buy',buyDispatch:'recovery',recovery:'receiptBuy',ending:'epilogue'};if(durations[s]&&t>=durations[s])this.setState(next[s]);}
 cameraPose(){const s=this.state,t=this.time;let pos=[0,1.6,3.4],look=[.15,1.1,.1];if(s==='entrance'){const v=ease(t/FILM_DURATIONS.entrance);pos=[lerp(0,-.15,v),1.64,lerp(6.8,2.4,v)];look=[.12,lerp(1.5,1.13,v),.25];this.door.rotation.y=lerp(-.15,-1.5,ease(t/2));}if(['order','holdingSell','buy','holdingBuy'].includes(s)){pos=[-.08,1.62,2.4];look=[.12,1.07,.15];}if(['dispatch','buyDispatch'].includes(s)){const v=ease(t/7);pos=[lerp(-.08,.55,v),1.65,lerp(2.4,.2,v)];look=[.35,1.45,-3.2];}if(s==='tape'){pos=[1.0,1.55,1.8];look=[1.15,1.07,.35];}if(s==='falling'){const v=ease(t/FILM_DURATIONS.falling);pos=[lerp(1,-1.25,v),lerp(1.55,1.72,v),lerp(1.8,2.2,v)];look=[lerp(1.15,-2.4,v),lerp(1.07,2.05,v),lerp(.35,-2,v)];}if(['receipt','receiptBuy'].includes(s)){pos=[.12,1.5,1.65];look=[.55,1.07,.55];}if(['inspectSell','inspectBuy','sellRevelation','book'].includes(s)){pos=[.12,1.62,2.25];look=[.2,1.36,.3];}if(s==='recovery'){const v=ease(t/FILM_DURATIONS.recovery);pos=[lerp(.55,-.3,v),1.7,lerp(.2,2.6,v)];look=[lerp(.3,-3.8,v),lerp(1.45,2.3,v),-2.4];}if(s==='ending'){const v=ease(t/FILM_DURATIONS.ending);pos=[.12,1.62,lerp(2.25,4.7,v)];look=[.18,1.18,.2];}if(s==='epilogue'){pos=this.freePos.toArray();look=[pos[0]+Math.sin(this.freeYaw)*Math.cos(this.freePitch)*3,pos[1]+Math.sin(this.freePitch)*3,pos[2]-Math.cos(this.freeYaw)*Math.cos(this.freePitch)*3];}this.desiredPosition.set(...pos);this.desiredLook.set(...look);this.desiredLook.x+=this.lookX*1.8;this.desiredLook.y+=this.lookY;}
 updateScene(dt){if(this.state==='epilogue'){const z=(this.keys.has('KeyS')?1:0)-(this.keys.has('KeyW')?1:0),x=(this.keys.has('KeyD')?1:0)-(this.keys.has('KeyA')?1:0);const speed=dt*1.7/(Math.hypot(x,z)||1);const nx=clamp(this.freePos.x+(x*Math.cos(this.freeYaw)-z*Math.sin(this.freeYaw))*speed,-5.2,5.2),nz=clamp(this.freePos.z+(x*Math.sin(this.freeYaw)+z*Math.cos(this.freeYaw))*speed,-2.2,5.2);if(!(Math.abs(nx)<1.65&&this.freePos.z>-.55&&this.freePos.z<1.05))this.freePos.x=nx;if(!(Math.abs(this.freePos.x)<1.65&&nz>-.55&&nz<1.05))this.freePos.z=nz;}const s=this.state,t=this.time,panic=['falling','receipt','inspectSell','sellRevelation','buy','holdingBuy','buyDispatch','recovery','receiptBuy','inspectBuy','ending'].includes(s);this.cameraPose();const blend=1-Math.exp(-dt*3.4);this.cameraPosition.lerp(this.desiredPosition,blend);this.cameraLook.lerp(this.desiredLook,blend);this.camera.position.copy(this.cameraPosition);this.camera.lookAt(this.cameraLook);this.wheel.rotation.z+=dt*(panic?11:3.5);this.clockLong.rotation.z=-this.elapsed*.025;this.clockShort.rotation.z=-this.elapsed*.003;
 const positions=this.tapeGeometry.attributes.position;for(let i=0;i<positions.count;i++){const x=i%2?.06:-.06,row=Math.floor(i/2)/65;const length=1.3+this.pull*.65;positions.setXYZ(i,x+Math.sin(row*Math.PI)*.035,-Math.pow(row,3)*1.3+Math.sin(row*Math.PI*2+this.elapsed*1.5)*.018,row*length); }positions.needsUpdate=true;this.tapeGeometry.computeVertexNormals();this.tapeGeometry.computeBoundingSphere();this.tape.rotation.x=0;this.tapeMaterial.map.offset.y=(this.elapsed*(panic?.018:.008))%1;
 this.paperLoops.forEach((o,i)=>{o.rotation.z+=dt*.03;const growth=panic?clamp(t/15,0,1):0;o.scale.setScalar(1+growth*.45);});
 for(const a of this.actors){const speed=panic?2.8:1.1,phase=this.elapsed*speed+a.seed;const walking=a.seed>=4;a.root.position.x=a.base.x+(walking?Math.sin(phase*.5)*(panic?.75:.35):Math.sin(phase*.4)*.035);a.root.position.y=Math.sin(phase*2)*(walking?.017:.004);a.root.rotation.y=walking?Math.sin(phase*.5)*.5:Math.sin(phase*.2)*.1;a.head.rotation.y=Math.sin(phase*.7)*.15;for(let i=0;i<2;i++){a.legs[i].rotation.x=walking?Math.sin(phase+i*Math.PI)*.28:0;a.arms[i].arm.rotation.x=walking?Math.sin(phase+i*Math.PI)*.25:-.5+Math.sin(phase)*.1;a.arms[i].fore.rotation.x=-.35-Math.sin(phase+i)*.25;}if(a.seed===2&&['dispatch','buyDispatch'].includes(s)){a.arms[0].arm.rotation.x=-ease(t/3)*1.35;a.arms[0].fore.rotation.x=-.65;}}

 if(['falling','recovery'].includes(s)&&t>FILM_DURATIONS[s]-6){const deliveryTime=t-(FILM_DURATIONS[s]-6),v=ease(deliveryTime/5.6),a=this.courier;a.root.position.lerpVectors(a.base,new THREE.Vector3(.95,0,.38),v);a.root.rotation.y=Math.PI;a.arms[0].arm.rotation.x=-.85;a.arms[0].fore.rotation.x=-.7;const card=s==='falling'?this.receipt:this.receipt2;card.visible=true;card.position.set(lerp(2.5,.65,v),lerp(1.28,1.08,ease((deliveryTime-3.5)/2.2)),lerp(-1.85,.55,v));card.rotation.x=lerp(-.9,0,ease((deliveryTime-3.5)/2.2));}
 if(['receipt','receiptBuy'].includes(s)){const a=this.courier;a.root.position.lerpVectors(new THREE.Vector3(.95,0,.38),a.base,ease(t/4));a.root.rotation.y=0;}
 if(this.held){const pick= ease((this.time)/.65);const inspecting=['inspectSell','inspectBuy','sellRevelation','ending','book'].includes(s);const heldScale=innerWidth<600?.7:inspecting?1.02:.68;const halfWidth=.85*Math.tan(this.camera.fov*Math.PI/360)*this.camera.aspect;const handX=inspecting?0:Math.min(.34,Math.max(.035,halfWidth-heldScale*.23-.04));const holder=new THREE.Vector3(clamp(handX+this.aim.x*.06,-Math.max(.01,halfWidth-heldScale*.23-.025),Math.max(.01,halfWidth-heldScale*.23-.025)),-.08-this.aim.y*.04,-.85);this.camera.localToWorld(holder);this.held.position.lerp(holder,1-Math.exp(-dt*8));this.held.quaternion.copy(this.camera.quaternion);this.held.rotateX(Math.PI/2);this.displayFlip=lerp(this.displayFlip,this.flip,1-Math.exp(-dt*12));this.held.rotateZ(this.displayFlip*Math.PI);this.held.scale.setScalar(heldScale);this.hand.position.set(handX+(inspecting?.21:.13)+this.aim.x*.04,-.36-this.aim.y*.025,-.81);this.hand.rotation.z=this.flip*.16;this.fingers.forEach(f=>f.rotation.x=-.45);}
 if(this.deliverObject&&['dispatch','buyDispatch'].includes(s)){const v=ease(t/1.9);this.deliverObject.position.lerpVectors(this.deliverStart,new THREE.Vector3(.38,1.4,-2.35),v);this.deliverObject.rotation.x=-v*.08;this.deliverObject.rotation.z=v*.1;if(t>2.3)this.deliverObject.visible=false;}
 const price=s==='falling'?Math.round(lerp(100,80,ease(t/20))):['recovery','receiptBuy','inspectBuy','ending','epilogue','book'].includes(s)?Math.round(lerp(80,95,s==='recovery'?ease(t/18):1)):100;this.setBoard(['交易所 · 此刻',String(price)]);const tapePrice=['recovery','receiptBuy','inspectBuy','ending','epilogue','book'].includes(s)?80:100;if(this.lastTapePrice!==tapePrice){this.lastTapePrice=tapePrice;this.paintTape(tapePrice);}
 this.sun.intensity=lerp(this.sun.intensity,s==='ending'?.65:panic?1.8:3.4,dt*.5);this.lampLight.intensity=lerp(this.lampLight.intensity,panic?4:6,dt);this.dust.rotation.y=this.elapsed*.003;if(this.grade){this.grade.uniforms.time.value=this.elapsed;this.grade.uniforms.fade.value=s==='entrance'?ease(t/1.8):s==='ending'?1-ease((t-(FILM_DURATIONS.ending-6))/6)*.36:1;}
 this.audioTick+=dt;if(this.audioTick>(panic?.13:.38)){this.audioTick=0;this.tick(panic?320:230,.035,.05);}
 for(const obj of [this.sellCard,this.buyCard,this.receipt,this.receipt2]){const hovered=this.hover===obj.userData.id;obj.traverse(o=>{if(o.material?.emissiveMap)o.material.emissiveIntensity=hovered?.26:.14;});}
 const hint=this.hint();if($('#filmHint').textContent!==hint)$('#filmHint').textContent=hint;
 }
 render(){this.syncTouchControls();if(this.renderer.isWebGLRenderer){this.fpsFrames++;const now=performance.now();if(now-this.fpsStart>1500){$('#filmHud').dataset.fps=String(Math.round(this.fpsFrames*1000/(now-this.fpsStart)));this.fpsStart=now;this.fpsFrames=0;}}if(this.composer)this.composer.render();else this.renderer.render(this.scene,this.camera);if(this.renderer.info){$('#filmHud').dataset.calls=String(this.renderer.info.render.calls);$('#filmHud').dataset.geometries=String(this.renderer.info.memory.geometries);$('#filmHud').dataset.textures=String(this.renderer.info.memory.textures);}}
 dispose(){if(this.composer){for(const p of this.composer.passes)p.dispose?.();this.composer.dispose();this.composer=null;}this.sun?.shadow?.dispose?.();if(this.scene){this.scene.traverse(o=>o.geometry?.dispose());this.scene=null;}for(const m of this.materials)m.dispose();for(const t of this.textures)t.dispose();this.materials=[];this.textures=[];this.targets=[];this.actors=[];this.motions=[];this.renderer.renderLists?.dispose();if(this.savedPixelRatio)this.renderer.setPixelRatio(this.savedPixelRatio);if(this.renderer.shadowMap)this.renderer.shadowMap.enabled=this.savedShadow??false;}
}
