import assert from 'node:assert/strict';
import {Vector3} from 'three';
const elements=new Map();const element=()=>({hidden:false,style:{},textContent:'',classList:{add(){},remove(){}},setAttribute(){},querySelectorAll(){return[]},addEventListener(){}});
const ctx=new Proxy({},{get:(o,k)=>o[k]??(()=>{}),set:(o,k,v)=>{o[k]=v;return true}});
globalThis.document={body:element(),querySelector(s){if(!elements.has(s))elements.set(s,element());return elements.get(s)},createElement(){return{width:0,height:0,getContext(){return ctx},toDataURL(){return'data:image/png;base64,'}}}};
globalThis.innerWidth=1280;globalThis.innerHeight=720;globalThis.matchMedia=()=>({matches:false});
const {TickerFilm,FILM_DURATIONS}=await import('../src/ticker-film.js');let draws=0;
const renderer={render(scene,camera){scene.updateMatrixWorld(true);camera.updateMatrixWorld(true);draws++;scene.traverse(o=>assert(Number.isFinite(o.position.x+o.position.y+o.position.z),'Finite scene transforms'));}};
const film=new TickerFilm(renderer,{onExit(){}});film.sounds=false;
const advance=seconds=>{for(let i=0;i<Math.ceil(seconds*60);i++)film.update(1/60)};
const paperInPlace=()=>{const a=film.tapeGeometry.attributes.position;for(let i=0;i<a.count;i++)assert(Math.abs(a.getX(i))<.11,'Paper remains attached to ticker during long playback');};
const point=obj=>{film.scene.updateMatrixWorld(true);const p=obj.getWorldPosition(new Vector3()).project(film.camera);return[(p.x+1)*640,(1-p.y)*360]};
film.open();advance(FILM_DURATIONS.entrance+1);assert.equal(film.state,'order');advance(20);paperInPlace();assert.equal(film.state,'order','Wait for actual object interaction');
let xy=point(film.sellCard);film.pointerDown(...xy);assert.equal(film.state,'holdingSell','Raycast picks actual paper');advance(1);
xy=point(film.slot);film.pointerUp(...xy);assert.equal(film.state,'dispatch','Dropping into counter delivers order');advance(FILM_DURATIONS.dispatch+1);assert.equal(film.state,'tape');
xy=point(film.grip);film.pointerDown(...xy);film.pointerMove(xy[0],xy[1]+380);film.pointerUp(xy[0],xy[1]+380);assert.equal(film.state,'falling','Direct paper pull advances the film');advance(FILM_DURATIONS.falling+1);assert.equal(film.state,'receipt');
xy=point(film.receipt);film.pointerDown(...xy);assert.equal(film.state,'inspectSell');advance(1);
film.pointerMove(xy[0]+600,xy[1]);assert.equal(film.state,'sellRevelation','Dragging the actual receipt flips it');advance(1);const backUp=new Vector3(0,1,0).transformDirection(film.receipt.userData.back.matrixWorld);const cameraUp=new Vector3(0,1,0).applyQuaternion(film.camera.quaternion);assert(backUp.dot(cameraUp)>.99,'Printed reverse face reads upright after turning');const backNormal=new Vector3(0,0,1).transformDirection(film.receipt.userData.back.matrixWorld);assert(backNormal.dot(new Vector3(0,0,1).applyQuaternion(film.camera.quaternion))>.99,'Back face points toward the reader');advance(FILM_DURATIONS.sellRevelation);assert.equal(film.state,'buy');
xy=point(film.buyCard);film.pointerDown(...xy);assert.equal(film.state,'holdingBuy');advance(1);xy=point(film.slot);film.pointerUp(...xy);assert.equal(film.state,'buyDispatch');advance(FILM_DURATIONS.buyDispatch+1);assert.equal(film.state,'recovery');
film.setPaused(true);const before=film.time;advance(3);assert.equal(film.time,before,'Pause freezes timeline');film.setPaused(false);advance(FILM_DURATIONS.recovery+1);assert.equal(film.state,'receiptBuy');
xy=point(film.receipt2);film.pointerDown(...xy);assert.equal(film.state,'inspectBuy');advance(1);film.pointerMove(xy[0]+600,xy[1]);assert.equal(film.state,'ending');advance(FILM_DURATIONS.ending+1);assert.equal(film.state,'epilogue');
xy=point(film.book);film.pointerDown(...xy);assert.equal(film.state,'book');assert.equal(film.flip,0,'Book opens on its printed face after receipt flip');film.showBook(3);assert.equal(film.page,3);film.close();assert.equal(film.active,false);
film.open();advance(FILM_DURATIONS.entrance+1);assert.equal(film.state,'order','Can reopen cleanly');film.close();
globalThis.innerWidth=390;globalThis.innerHeight=844;film.open();advance(FILM_DURATIONS.entrance+1);film.activateById('sell');advance(2);film.scene.updateMatrixWorld(true);for(const x of[-.23,.23])for(const z of[-.325,.325]){const corner=film.sellCard.localToWorld(new Vector3(x,0,z)).project(film.camera);assert(Math.abs(corner.x)<.99&&Math.abs(corner.y)<.99,'Held paper fits mobile screen');}film.deliver();advance(FILM_DURATIONS.dispatch+1);film.keyDown({code:'KeyE',preventDefault(){}});advance(2);film.keyUp({code:'KeyE'});assert.equal(film.state,'falling','Keyboard hold alternative works');film.close();
console.log('PASS: direct raycast pickup, delivery, receipt flip, continuous two-order timeline, pause, book and reopen. '+draws+' frames simulated.');

// Audio lifecycle: entry starts sound; UI follows actual context state.
let audioContexts=0,oscillatorStarts=0;
const audioNode=()=>({gain:{value:0,setTargetAtTime(v){this.value=v},setValueAtTime(v){this.value=v},exponentialRampToValueAtTime(){}},frequency:{value:0,setValueAtTime(){},exponentialRampToValueAtTime(){}},connect(next){this.connected=next;return next},disconnect(){},start(){oscillatorStarts++},stop(){}});
class TestAudioContext{constructor(){audioContexts++;this.state='suspended';this.sampleRate=100;this.currentTime=0;this.destination=audioNode()}createGain(){return audioNode()}createBuffer(ch,n){return{getChannelData(){return new Float32Array(n)}}}createBufferSource(){return audioNode()}createBiquadFilter(){return audioNode()}createOscillator(){return audioNode()}resume(){this.state='running';this.onstatechange?.();return Promise.resolve()}suspend(){this.state='suspended';this.onstatechange?.();return Promise.resolve()}}
globalThis.window={AudioContext:TestAudioContext};film.sounds=true;film.open();await Promise.resolve();assert.equal(audioContexts,1,'Entry initializes audio without requiring object interaction');assert.equal(elements.get('#filmAudio').textContent,'音效 开');film.tick();assert.equal(oscillatorStarts,2,'Ambient source and ticker oscillator started');elements.get('#filmAudio').onclick();assert.equal(film.master.gain.value,0,'Mute applies to all sound');assert.equal(elements.get('#filmAudio').textContent,'音效 关');elements.get('#filmAudio').onclick();assert.equal(film.master.gain.value,1,'Button starts or resumes audible output');assert.equal(audioContexts,1,'Re-enable reuses context');film.setPaused(true);assert.equal(film.master.gain.value,0,'Pause mutes ambience');film.setPaused(false);assert.equal(film.master.gain.value,1);film.audio.state='suspended';film.audioStatus();assert.equal(elements.get('#filmAudio').textContent,'开启音效','Suspended output is not reported as playing');elements.get('#filmAudio').onclick();assert.equal(film.audio.state,'running');film.close();assert.equal(film.audio.state,'suspended');film.open();assert.equal(audioContexts,1);assert.equal(film.audio.state,'running','Re-entry resumes the existing context');film.close();delete globalThis.window;
console.log('PASS: audio entry, actual-state label, toggle, master mute, pause, resume and re-entry.');
